### ISSUE TITLE
Failed to inline fmod yields KernelFlattening waring with ND-Range kernel

### ISSUE THREAD

**Issue by Aympab** [AdaptiveCpp/AdaptiveCpp#1012]
Hello,
I have an application with several version of the same kernel using different SYCL parallelism paradigms.

When using NDRange, compiling on the CPU with hipSYCL (it was hip at that time) version 0.9.3 (commit 4a04f1c661b7a172ed60e92ecc35fb6c3f1de5a4 on branch develop) yields a warning:

`[hipSYCL Warning] [KernelFlattening] failed to inline function <fmod>: 'external or indirect'`

I use `sycl::fmod` in my kernel.
I built SYCL against llvm 15.0.7 only with the LLVM accelerated-cpu toolchain.

I am not sure where this come from, if you have any hints taht'll be great.

Note: when compiling on another build of hipSYCL (clang-13/cuda-11.5) for the GPU, only with `sm_80` target (no CPU target), I don't get the warning

**Comment by fodinabor** [comment]
The accelerated CPU implementation must be able to find all work-group barriers in kernel code. That includes barriers in any functions used in the kernel.
It currently does identify them by just inlining all functions in a kernel. If there are "external"/undefined functions (aka ones that are linked later from glibc or so), it cannot inline these functions.
Since we don't have the definition of the function available in the compiler, we are unsure if the function might contain a barrier -> we warn. In the case of math functions like `fmod` it's quite obvious that indeed there won't be a barrier inside the function, so you can just ignore the warning.. I guess we could be a bit more selective in emitting that warning / also be a bit more explanatory what that means ...

**Comment by Aympab** [comment]
Ok I see thanks !
