### ISSUE TITLE
Unresolved kernel function

### ISSUE THREAD

**Issue by bsobol** [AdaptiveCpp/AdaptiveCpp#1099]
**Summary**
I'm implementing SYCL kernels as callable objects. Initially, I put all kernel code in header files, but recently I decided to refactor into .cpp/.h, and I encountered an error when compiling for CUDA (cuda-clang) target:

```
ptxas fatal: Unresolved extern function '_ZNK2r29detectors3fts16TrackRecoLineZOYclEN7hipsycl4sycl2idILi1EEE'
```
where the mangled name is the `operator()`.

Is this the expected behavior, are such kernel objects required to be header-only?

**Setup**
* latest hipSYCL develop
* Ubutu 22.04
* Clang 16
* CUDA 11.8

**Comment by illuhad** [comment]
In SYCL, if you implement parts of kernel code in an external translation unit, those functions must be marked as `SYCL_EXTERNAL`. Otherwise, the SYCL compiler cannot know that the functions need to be emitted to device code if it cannot see the `parallel_for` call.

`SYCL_EXTERNAL` is an optional feature according to the SYCL specification. We only support it for the generic SSCP compiler (`--hipsycl-targets=generic`). If you use `--hipsycl-targets=cuda`, this is not supported.

**Comment by bsobol** [comment]
Ok, thanks for the clarification.
