### ISSUE TITLE
Hide non-supported OpenCL devices

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#1203]
**Describe the motivation for the feature request**

OpenCL backend of AdaptiveCpp requires "SPIR-V compatible OpenCL devices" (per README).

Notably, NVIDIA and AMD ROCm platforms don't support SPIR-V, and even correctly report that by returning empty `CL_DEVICE_IL_VERSION`.

Hiding such devices by default seems like a reasonable choice.

**Describe the solution you'd like**

- If the device can't be used via OpenCL backend (e.g., it does not support SPIR-V), it should not be presented.

**Comment by illuhad** [comment]
There's a difference between being able to run kernels and exposing runtimes. For example, we are also expose the CUDA backend even if kernels have only been compiled for HIP target. The idea is that even if you don't want to run kernels, perhaps you are just interested in some interoperability (e.g. interfacing with cuBLAS, while another backend runs your own kernels).

The OpenCL backend currently does not support interop, but perhaps there could be similar use cases here. Perhaps we can formulate some conditions where an OpenCL implementation can be considered "too broken for anything", but I'm not sure.

Note: The user can already hide problematic OpenCL implementations using `ACPP_VISIBILITY_MASK`. For example, `ACPP_VISIBILITY_MASK=omp;ocl:Graphics.*` exposes only devices from Intel GPU OpenCL since it is the only one having "Graphics" in the platform name.

**Comment by al42and** [comment]
> There's a difference between being able to run kernels and exposing runtimes. For example, we are also expose the CUDA backend even if kernels have only been compiled for HIP target. The idea is that even if you don't want to run kernels, perhaps you are just interested in some interoperability (e.g. interfacing with cuBLAS, while another backend runs your own kernels).

> The OpenCL backend currently does not support interop, but perhaps there could be similar use cases here. Perhaps we can formulate some conditions where an OpenCL implementation can be considered "too broken for anythi

With no way to run user kernels and no interop, I struggle to see any benefit of exposing them by default, and requiring every user (if one has CUDA or HIP installed, highly likely they have corresponding OpenCL device too) to set an extra environment variable just to hide broken and useless devices; just in case there might be some possible way to do something with them.

> Note: The user can already hide problematic OpenCL implementations using ACPP_VISIBILITY_MASK. For example, ACPP_VISIBILITY_MASK=omp;ocl:Graphics.* exposes only devices from Intel GPU OpenCL since it is the only one having "Graphics" in the platform name.

I'd expect the opposite, hiding them by default and having an environment variable  `ACPP_SHOW_INCOMPATIBLE_DEVICES` to opt in. The README already says "Supported compilation flows include: [...] SPIR-V compatible OpenCL devices supporting Intel USM extensions or fine-grained system SVM", so I don't think many people would expect non-compatible OpenCL devices to be presented. (one can nitpick that it does not say that *only* those devices are supported, but I don't think that would be the expectation)

More importantly, not only some backends are questionably useful. As discussed in #1202, merely trying to get some info from their devices can lead to undefined behavior. If we follow the logic "if a backend behaves in a non-perfectly-standard-complinant way then we can have no guarantees for the SYCL layer", then exposing these platforms/devices poisons the entire runtime.

This pretty much translates to "don't ever build OpenCL backend, because even enumerating the devices there can break your application".

P.S. Device duplicates are also confusing for the user. Since both CUDA and HIP ship with their OpenCL runtimes, the user would see two copies of their GPU, "NVIDIA GeForce RTX 3060" and "NVIDIA GeForce RTX 3060". Which should they choose? Of course, both! Oh no, an error from "NVIDIA GeForce RTX 3060", could not run code. But I compiled with `cuda:sm_86`, it should support my GPU!". When both devices are usable, the confusion is still there, but at least it is meaningful. Showing two copies of the same physical device, one of them broken, and hoping either for the application developer to implement some filtering logic or for the user to make the right guess...

**Comment by illuhad** [comment]
>   With no way to run user kernels and no interop, I struggle to see any benefit of exposing them by default, and requiring every user (if one has CUDA or HIP installed, highly likely they have corresponding OpenCL device too) to set an extra environment variable just to hide broken and useless devices; just in case there might be some possible way to do something with them.

There's no way *currently* for OpenCL (which is a brand-new backend, after all!). There's also value in having consistent behavior across all backends, because if backends diverge this can also be confusing.

> I'd expect the opposite, hiding them by default and having an environment variable ACPP_SHOW_INCOMPATIBLE_DEVICES to opt in. 

I'm just pointing out that this issue can currently already be circumvented. Visibility mask for specifically for OpenCL can be useful for a load of other reasons, so having it is a must anyway. Whether an additional environment variable could be introduced is another question.

>  "Supported compilation flows include: [...] SPIR-V compatible OpenCL devices supporting Intel USM extensions or fine-grained system SVM", so I don't think many people would expect non-compatible OpenCL devices to be presented. (one can nitpick that it does not say that only those devices are supported, but I don't think that would be the expectation)

This specifically talks about compilation flows, not runtime support. I'm not convinced that coupling compiler and runtime support is a good idea in light of separation of concerns. They are two unrelated features. And you will find similar behavior in other models/compilers too. DPC++ (not the product version, the open source one) does not filter out OpenCL devices that do not support SPIR-V to my knowledge. `rocminfo` shows AMD GPUs independently of whether they are supported by the compiler or other parts of the stack.

>  As discussed in https://github.com/AdaptiveCpp/AdaptiveCpp/issues/1202, merely trying to get some info from their devices can lead to undefined behavior. If we follow the logic "if a backend behaves in a non-perfectly-standard-complinant way then we can have no guarantees for the SYCL layer", then exposing these platforms/devices poisons the entire runtime.

I agree that perhaps we need to drill down a bit more into which requirements we want to impose on OpenCL devices. Not supporting old OpenCL runtimes for example seems reasonable to me, as then fundamental parts of the API (such as some queries) are just not there.

> P.S. Device duplicates are also confusing for the user. Since both CUDA and HIP ship with their OpenCL runtimes, the user would see two copies of their GPU, "NVIDIA GeForce RTX 3060" and "NVIDIA GeForce RTX 3060". Which should they choose? Of course, both! Oh no, an error from "NVIDIA GeForce RTX 3060", could not run code. But I compiled with cuda:sm_86, it should support my GPU!". When both devices are usable, the confusion is still there, but at least it is meaningful. Showing two copies of the same physical device, one of them broken, and hoping either for the application developer to implement some filtering logic or for the user to make the right guess...

It seems a bit unfair to fault AdaptiveCpp for that:
* DPC++ does the exact same thing with Intel GPUs showing up twice (once from OpenCL and once from Level Zero). I expect the same issue with one device boken can happen if it finds AMD OpenCL and the HIP backend.
* Separation of concerns
* Users might just as well be confused that a device does not show up that they expect
* CUDA compilation flow is specifically advertised as focusing on interoperability and integration with CUDA toolchain. Thus the clear expectation should be that it only works for devices from the CUDA backend. You could perhaps construct a better argument for `generic`.
* This is a well known SYCL behavior that is even discussed in introductory materials from e.g. SYCL Academy AFAIR.

**Comment by al42and** [comment]
> There's no way _currently_ for OpenCL (which is a brand-new backend, after all!).

I'm not suggesting to hide *supported* OpenCL devices :)

> DPC++ does the exact same thing with Intel GPUs showing up twice (once from OpenCL and once from Level Zero).

Yes, but in this case both versions of the device are usable. That falls under "confusing, but meaningful".

> I expect the same issue with one device boken can happen if it finds AMD OpenCL and the HIP backend.

No, it explicitly hides broken platforms:

https://github.com/intel/llvm/blob/8fe166fb4431645b6c7a26f4d88c0564e8d1d427/sycl/source/detail/platform_impl.cpp#L75

Admittedly, the AMD filter was added by me :) But they were already filtering out NVIDIA, so the approach of hiding unsupported OpenCL platforms is not my invention.

> rocminfo shows AMD GPUs independently of whether they are supported by the compiler or other parts of the stack.

Yes. But `hipGetDeviceCount` does not list unsupported devices (such as CPUs, or NVIDIA GPUs in case their support is not enabled). I think, typical ACpp usage is high-level enough to be closer to HIP than to ROCm or `hwloc-ls`.

> CUDA compilation flow is specifically advertised as focusing on interoperability and integration with CUDA toolchain. Thus the clear expectation should be that it only works for devices from the CUDA backend. You could perhaps construct a better argument for generic.

As you said, the same argument works. "I compiled it for "generic" target, so it should work on my device! Why it does not work on "NVIDIA GeForce RTX 3060" when it says that NVIDIA GPUs are supported?". And, since the order of device enumeration is not guaranteed to be persistent, the next time they run the application, the first "NVIDIA GeForce RTX 3060" might be from CUDA, it will work fine. Fun.

But, more importantly, I would not expect end users, who just try to run some SYCL-enabled app, to know the difference between CUDA and OpenCL. They have NVIDIA GPU, they pick some option from the installation guide / random googling / ChatGPT. Then they get weird errors. Or maybe the application is smart enough to compile for SSCP and not require any user input, but then the users will still see runtime warnings that their NVIDIA/AMD GPU does not support memory allocations and will think that all is broken and will try to reinstall drivers (we got several questions about perfectly benign CMake status message "checking sm_35: failed" when iterating over all possible compiler flags; we had to change the wording from "failed" to "no" to avoid scaring people into thinking that something is wrong with their drivers/installation).

So, as a developer of an application using SYCL, the most viable option for me is to filter out incompatible devices on the application side. Which can be done, sure. And currently, it would require me to skip OpenCL devices with "NVIDIA" or "AMD" in their vendor string (or ignore all OpenCL devices).

And when the next version of ACpp actually starts fully supporting these devices -- tough luck, one would need to update the application to remove the filter (or, more likely, make it dependent on ACpp version), even if "generic" backend were to work fine on such devices.

I think that would end up reducing portability, not improving it.

The same logic applies if we suggest users to use `ACPP_VISIBILITY_MASK` or just say "don't do X" in the manual: the practical enablement of new devices is delayed by the application developers not updating their user guide. Same for the advice to build ACpp with `WITH_OPENCL_BACKEND=OFF` (although, as Szilárd mentioned over email, we might still have to do it since it causes compilation failures with either amdclang or even some manually-compiled vanilla clang).

> I agree that perhaps we need to drill down a bit more into which requirements we want to impose on OpenCL devices. Not supporting old OpenCL runtimes for example seems reasonable to me, as then fundamental parts of the API (such as some queries) are just not there.

That's pretty much the point of this issue, don't offer what is known to be broken: "If the device can't be used via OpenCL backend (example heuristic; admittedly, not the perfect one), it should not be presented.".

**Comment by illuhad** [comment]
> Admittedly, the AMD filter was added by me :) But they were already filtering out NVIDIA, so the approach of hiding unsupported OpenCL platforms is not my invention.

Ah, so they changed behavior. I distinctly remember posts in their issue tracker where people reported that AMD OpenCL kernel execution failed.

> Yes. But hipGetDeviceCount does not list unsupported devices (such as CPUs, or NVIDIA GPUs in case their support is not enabled). I think, typical ACpp usage is high-level enough to be closer to HIP than to ROCm or hwloc-ls.

I'm pretty sure HIP just lists all AMD GPUs though, regardless of whether they are supported, not-supported-but-work, or don't work at all.

How does DPC++ handle the case when a supported GPU is there, but it was not targeted in compiler flags?
In that case too kernel execution will fail even though the runtime exposes a device, so you would have the same effect.

This is always where we have separated concerns, because different parts of the application (different TUs, or even different shared objects) may have been compiled with different flags or different configurations. So it might be difficult to even determine which device can actually execute kernels across the application.

> But, more importantly, I would not expect end users, who just try to run some SYCL-enabled app, to know the difference between CUDA and OpenCL. They have NVIDIA GPU, they pick some option from the installation guide / random googling / ChatGPT. Then they get weird errors. Or maybe the application is smart enough to compile for SSCP and not require any user input, but then the users will still see runtime warnings that their NVIDIA/AMD GPU does not support memory allocations and will think that all is broken and will try to reinstall drivers (we got several questions about perfectly benign CMake status message "checking sm_35: failed" when iterating over all possible compiler flags; we had to change the wording from "failed" to "no" to avoid scaring people into thinking that something is wrong with their drivers/installation).
So, as a developer of an application using SYCL, the most viable option for me is to filter out incompatible devices on the application side. Which can be done, sure. And currently, it would require me to skip OpenCL devices with "NVIDIA" or "AMD" in their vendor string (or ignore all OpenCL devices).

SYCL, like all of heterogeneous computing, is not a beginner-friendly technology in tiself, so I think we can expect that SYCL developers to some reasonable extent will know what they are doing or at least know the difference between CUDA and OpenCL.
From what you write, it seems to me that most of the concern is for the end user of the application, not the application developer. Perhaps what is really needed here is a mechanism for the application to communicate requirements to the runtime (#860 comes to mind). Then the application developer could e.g. express that they do want to enable some automatic filter to benefit from future improvements, or perhaps do not want this because they want full control or have some specific requirements.

> That's pretty much the point of this issue, don't offer what is known to be broken: "If the device can't be used via OpenCL backend (example heuristic; admittedly, not the perfect one), it should not be presented.".

There are many degrees and definitions of "broken" and requirements may vary. But I understand why this is important to you. I suppose in the timeframe of the 23.10 release we can only reasonably implement some simple solution. Like hide pre-OpenCL 2.0 devices and add an environment variable to override or so.

**Comment by al42and** [comment]
> I'm pretty sure HIP just lists all AMD GPUs though, regardless of whether they are supported, not-supported-but-work, or don't work at all.

> How does DPC++ handle the case when a supported GPU is there, but it was not targeted in compiler flags?

Yes, they both list all devices. I think we are straying away from the point of this issue. I am not suggesting to hide devices not targeted at compile-time. That *is* a useful thing, but not something that should be solved by hiding them altogether. 

What I suggest is to hide device that are known to be broken and which cannot be made to work no matter how much one tries. See #1202:

> IMO none of these queries should ever fail. If they fail, something is broken and you are operating the implementation outside of its supported configurations.

<hr/>

> From what you write, it seems to me that most of the concern is for the end user of the application, not the application developer. Perhaps what is really needed here is a mechanism for the application to communicate requirements to the runtime (https://github.com/AdaptiveCpp/AdaptiveCpp/pull/860 comes to mind). Then the application developer could e.g. express that they do want to enable some automatic filter to benefit from future improvements, or perhaps do not want this because they want full control or have some specific requirements.

Yes. Also, the wording of [`sycl::is_compatible`](https://github.com/KhronosGroup/SYCL-Docs/pull/381) was updated to allow such checks. In GROMACS, we just run a test kernel and do some checks like sub-group sizes. For some cases, `device::has(aspect)` could be used, etc. That's solvable in many ways.

The big problem I'm trying to raise here: if we maintain [the logic that, if a backend is broken, one cannot rely](https://github.com/AdaptiveCpp/AdaptiveCpp/issues/1202#issuecomment-1773090819) on any API call that promises in the spec to throw all exceptions synchronously to actually throw them synchronously, then there is no way for the application to just iterate over devices and do the filtering based on some properties or any sanity checks. So, it's back to crude name/platform based checks. And such filtering, I believe, is better done at the ACpp level rather than at each application's level.

More minor problem is just noise from this extra devices. Sure, the application can run sanity checks on a device. But if there is no way to do anything with it, what's the point of presenting it? If a user sees that a device is incompatible, should they try to update their drivers to use this device? Rebuild the application with different flags? Neither will work.

Per spec,

> device: A SYCL device is an abstraction of a piece of hardware that can execute SYCL kernels.

There are many ways to interpret "can", but I think it implies that there is at least some way to do it with the current software stack. Maybe with right compiler flags or env. variables. But if one needs to hack the binary OpenCL driver to do so, I would not say it "can execute kernels".

<hr/>

> I suppose in the timeframe of the 23.10 release we can only reasonably implement some simple solution. Like hide pre-OpenCL 2.0 devices and add an environment variable to override or so.

If that solves the problem with AMD and Intel FPGA devices, then great.

**Comment by illuhad** [comment]
> Yes, they both list all devices. I think we are straying away from the point of this issue. I am not suggesting to hide devices not targeted at compile-time. That is a useful thing, but not something that should be solved by hiding them altogether.

Understood. I'm just pointing out that, from the user perspective, the exact same situation can appear when compilation targets are set incorrectly compared to OpenCL lacking SPIR-V support.

>   There are many ways to interpret "can", but I think it implies that there is at least some way to do it with the current software stack. Maybe with right compiler flags or env. variables. But if one needs to hack the binary OpenCL driver to do so, I would not say it "can execute kernels".

It's a probably not a good idea to read between the lines of the spec to such an extent. You'll encounter a lot of contradictions. SYCL also has the notion of builtin kernels, which can be launched independently of regular, user-programmable `parallel_for` kernels. The question to what extent SYCL wants to support non-programmable devices is still open, but there are traces for such use cases in the spec.

>  If that solves the problem with AMD and Intel FPGA devices, then great.

FPGA emulator is OpenCL 1.2. AMD is probably 2.0, but I'd have to check. It wouldn't help with NVIDIA OpenCL which exposes OpenCL 3.0.

**Comment by al42and** [comment]
> I'm just pointing out that, from the user perspective, the exact same situation can appear when compilation targets are set incorrectly compared to OpenCL lacking SPIR-V support.

Agree, but the lack of SPIR-V support is just my proposed solution, and I still think it's a good idea.

But whatever allows us to query device info without worrying about asynchronous exceptions or other clearly non-standard things happening is fine.

> AMD is probably 2.0, but I'd have to check.

```
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.1 AMD-APP (3590.0)

  Device Name                                     gfx1034
  Device Vendor                                   Advanced Micro Devices, Inc.
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 2.0
  Driver Version                                  3590.0 (HSA1.1,LC)
```

> It wouldn't help with NVIDIA OpenCL which exposes OpenCL 3.0.

NVIDIA OpenCL behaves well (does not crash on `get_info`, politely refuses to run kernels), so while I don't see any benefit of exposing it (e.g., if it is the only GPU device in the system, I don't think returning it as the default from `gpu_selector` would conform to reasonable expectations?). But I don't see much harm in having it either.

**Comment by illuhad** [comment]
Thanks for the clinfo output!

> I don't think returning it as the default from gpu_selector would conform to reasonable expectations?

Does it do that? From the code (and this is also the intent) it should only return OpenCL devices if `generic` target was used (or there is no other GPU). I think there's a minor bug where CPU selector might return an OpenCL CPU device even if `generic` was not used because that code path seems to not yet be aware that there might be non-OpenMP CPU devices.

**Comment by al42and** [comment]
> Does it do that? From the code (and this is also the intent) it should only return OpenCL devices if generic target was used.

You are right, and that *is* the undesired behavior I meant. With no CUDA/HIP backend built, OpenCL device gets readily selected when using `sycl::queue q{sycl::gpu_selector{})`:

```console
$ acpp -O2 --acpp-targets=generic 1128.cpp && ./a.out
[AdaptiveCpp Warning] OpenCL device NVIDIA GeForce RTX 3060 does not have a valid USM provider. Memory allocations are not possible on that device.
 I have hipSYCL OpenMP host device
 I have NVIDIA GeForce RTX 3060
[AdaptiveCpp Warning] OpenCL device NVIDIA GeForce RTX 3060 does not have a valid USM provider. Memory allocations are not possible on that device.
Running on NVIDIA GeForce RTX 3060
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:42 @ allocate(): ocl_allocator: OpenCL device does not have valid USM provider
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_code_object.cpp:64 @ ocl_executable_object(): ocl_code_object: Construction of CL program failed (error code = CL:-59)
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_code_object.cpp:64 @ ocl_executable_object(): ocl_code_object: Construction of CL program failed (error code = CL:-59)
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/include/hipSYCL/runtime/kernel_cache.hpp:427 @ get_or_construct_code_object_impl(): kernel_cache: code object creation has failed
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_queue.cpp:485 @ submit_sscp_kernel_from_code_object(): ocl_queue: Code object construction failed
[AdaptiveCpp Error] from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:82 @ free(): ocl_allocator: OpenCL device does not have valid USM provider
============== hipSYCL error report ============== 
hipSYCL has caught the following undhandled asynchronous errors: 

   0. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:42 @ allocate(): ocl_allocator: OpenCL device does not have valid USM provider
   1. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_code_object.cpp:64 @ ocl_executable_object(): ocl_code_object: Construction of CL program failed (error code = CL:-59)
   2. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_code_object.cpp:64 @ ocl_executable_object(): ocl_code_object: Construction of CL program failed (error code = CL:-59)
   3. from /home/aland/AdaptiveCpp/include/hipSYCL/runtime/kernel_cache.hpp:427 @ get_or_construct_code_object_impl(): kernel_cache: code object creation has failed
   4. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_queue.cpp:485 @ submit_sscp_kernel_from_code_object(): ocl_queue: Code object construction failed
   5. from /home/aland/AdaptiveCpp/src/runtime/ocl/ocl_allocator.cpp:82 @ free(): ocl_allocator: OpenCL device does not have valid USM provider
The application will now be terminated.
terminate called without an active exception
Aborted (core dumped)
```


If I were a novice SYCL developer just running some hello-world example after installing AdaptiveCpp (which failed to detect CUDA for some reason and did not build the CUDA RT backend), the error above would be quite scary and not too helpful, IMO.

**Comment by biergaizi** [comment]
> If I were a novice SYCL developer just running some hello-world example after installing AdaptiveCpp (which failed to detect CUDA for some reason and did not build the CUDA RT backend), the error above would be quite scary and not too helpful, IMO.

I just hit this problem while attempting to target CUDA. Previously I only had experience on targeting HIP. AdaptiveCpp detects the Nvidia GPU as both an OpenCL and CUDA device, but for some reason that I don't time to investigate, the device selector prefers OpenCL (likely a user problem, not a ACPP problem)... `ACPP_VISIBILITY_MASK="cuda"` was able to force it make the correct choice.

**Comment by illuhad** [comment]
@biergaizi Are you targeting `generic`? If you target generic, it can happen that it selects the OpenCL device because a) both CUDA and OpenCL backends support `generic`, and the device selector checks that and b) The backend that it selects depends on the order in which the runtime backend plugins are loaded, which ultimately depends on the order in which the OS lists the plugins in the filesystem.
The problem is that the device selector is not yet aware that executing on NVIDIA with OpenCL is not possible due to lack of SPIR-V and USM in NVIDIA OpenCL.

If you don't target `generic`, I think it should not select OpenCL.

**Comment by biergaizi** [comment]
Right now the error message due to selecting an incompatible device has become even more incomprehensible than before:

```
$ ./1.elf 
[AdaptiveCpp Warning] ocl_hardware_manager: OpenCL device 'cpu-Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz' does not support SPIR-V; hiding device. Set ACPP_RT_OCL_SHOW_ALL_DEVICES=1 to override.
[AdaptiveCpp Warning] ocl_hardware_manager: OpenCL device 'NVIDIA Graphics Device' does not support SPIR-V; hiding device. Set ACPP_RT_OCL_SHOW_ALL_DEVICES=1 to override.
[AdaptiveCpp Error] from /home/user/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:220 @ insert_event(): cuda_queue: Couldn't record event (error code = CUDA:400)
[AdaptiveCpp Error] from /home/user/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:220 @ insert_event(): cuda_queue: Couldn't record event (error code = CUDA:400)
============== hipSYCL error report ============== 
hipSYCL has caught the following unhandled asynchronous errors: 

   0. from /home/user/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:220 @ insert_event(): cuda_queue: Couldn't record event (error code = CUDA:400)
   1. from /home/user/AdaptiveCpp/src/runtime/cuda/cuda_queue.cpp:220 @ insert_event(): cuda_queue: Couldn't record event (error code = CUDA:400)
The application will now be terminated.
```

The workaround is the same: `export ACPP_VISIBILITY_MASK="cuda"`. Posted here so anyone else has a chance to find it via a search engine.

**Comment by illuhad** [comment]
I think the OpenCL incompatible device message is very clear: `OpenCL device 'NVIDIA Graphics Device' does not support SPIR-V; hiding device. Set ACPP_RT_OCL_SHOW_ALL_DEVICES=1 to override.`

It then correctly falls back to using the CUDA backend. Why this then fails I don't know. Just loading OpenCL should not impact CUDA. If it does, my guess is that there may be a driver issue beyond our control.
