### ISSUE TITLE
Potential bug when using different queues on the same device?

### ISSUE THREAD

**Issue by ManuelCostanzo** [AdaptiveCpp/AdaptiveCpp#1233]
Hi!

This is a small program example but represents the problem I'm having

```
#include <iostream>
#include <sycl/sycl.hpp>

constexpr int table [] = {10, 20, 30, 40};

struct DataStruct {
  sycl::int2* data2;
};

static DataStruct* myDataStruct;

static void funcc() {
  sycl::queue q((sycl::device::get_devices()[0]));

  myDataStruct = (DataStruct*)malloc(sizeof(DataStruct));

  myDataStruct->data2 = sycl::malloc_device<sycl::int2>(1024 * 1024, q);
  q.memset(myDataStruct->data2, 0, 1024 * 1024 * sizeof(sycl::int2))
        .wait();
}

int main()
{
  funcc();
  sycl::queue q((sycl::device::get_devices()[0]));

  sycl::int2* data = myDataStruct->data2;
  q.submit([&](sycl::handler &cgh) {
    cgh.parallel_for(sycl::nd_range<1>(1024, 1024), [=](sycl::nd_item<1> item){
      int idx = item.get_local_id(0);
      data[idx] = sycl::int2(idx + table[idx % 4], 3212);
    });
   })
   .wait();

  sycl::free(myDataStruct->data2, q);
  free(myDataStruct);

  return 1;
}
```

I'm using AdaptiveCPP from develop with LLVM 14 and CUDA 11.4. I'm compiling with:

acpp --acpp-targets="generic" -O3 sample.cpp -o sample -march=native

The error I'm having is:

```
[AdaptiveCpp Error] from /scratch/mcostanzo/AdaptiveCpp/src/runtime/cuda/cuda_allocator.cpp:145 @ query_pointer(): cuda_allocator: query_pointer(): pointer is unknown by backend (error code = CUDA:0)
============== hipSYCL error report ============== 
hipSYCL has caught the following undhandled asynchronous errors: 

   0. from /scratch/mcostanzo/AdaptiveCpp/src/runtime/cuda/cuda_allocator.cpp:145 @ query_pointer(): cuda_allocator: query_pointer(): pointer is unknown by backend (error code = CUDA:0)
The application will now be terminated.
terminate called without an active exception
```

Do you have any ideas? The problem cames when I use structures and that structure has the pointer I need. 

Thank you very much in advance!

**Comment by ManuelCostanzo** [comment]
I found the problem. sycl::device::get_devices()[0] is the same device, but apparently AdaptiveCPP doesn't save the pointer? This error is not happening in oneAPI. 

For example, the following code fixes the problem:

```
#include <iostream>
#include <sycl/sycl.hpp>

constexpr int table [] = {10, 20, 30, 40};

struct DataStruct {
  sycl::int2* data2;
};

static DataStruct* myDataStruct;
sycl::queue dev_q;

static void funcc() {
  sycl::queue q((sycl::device::get_devices()[0]));
  dev_q = q;

  myDataStruct = (DataStruct*)malloc(sizeof(DataStruct));

  myDataStruct->data2 = sycl::malloc_device<sycl::int2>(1024 * 1024, q);
  q.memset(myDataStruct->data2, 0, 1024 * 1024 * sizeof(sycl::int2))
        .wait();
}

int main()
{
  funcc();

  sycl::int2* data = myDataStruct->data2;
  dev_q.submit([&](sycl::handler &cgh) {
    cgh.parallel_for(sycl::nd_range<1>(1024, 1024), [=](sycl::nd_item<1> item){
      int idx = item.get_local_id(0);
      data[idx] = sycl::int2(idx + table[idx % 4], 3212);
    });
   })
   .wait();

  sycl::free(myDataStruct->data2, dev_q);
  free(myDataStruct);

  return 1;
}
```


But in my complete code, I can't use a static variable to save the device.

Any ideas?

Thanks!

**Comment by illuhad** [comment]
Not a bug. This is intended behavior.

Your code violates the SYCL specification. The pointer passed to `sycl::free()` must be from the same `context` as the one of the `queue` passed to `free()`. Since every `sycl::queue` creates a new `context` by default, this is not the case. So this is illegal in oneAPI too.

Now AdaptiveCpp generally does not care about `context` to the same extent as oneAPI because AdaptiveCpp automatically manages `context` internally. I.e. `sycl::context` is not directly coupled to backend context objects. However, the lifetime of the runtime depends on user-facing SYCL objects: The AdaptiveCpp runtime starts up when the first SYCL object is constructed, and it is shutdown when there are no SYCL objects around anymore.

In your code, the runtime starts up at the beginning of `funcc()` and then shuts down at the end of `funcc` because at that point, there is no SYCL object around anymore. When the runtime shuts down, in general it takes everything with it, so pointers may become invalid (this is in line with the SYCL specification, which mandates that pointers can only be used in the same `sycl::context` they were created in).

Consequently, `free()` fails. Note that even if it worked, this pattern is not desirable because a runtime restart can have substantial negative performance impact: Devices are queried again, backends are initialized again, and also the kernel cache is emptied, so JIT is triggered again.
Thus, you should avoid such patterns. There should always be at least one SYCL object alive (e.g. `sycl::context`, as intended by the specification) while your program is not done doing SYCL work.

**Comment by ManuelCostanzo** [comment]
> Not a bug. This is intended behavior.
> 
> Your code violates the SYCL specification. The pointer passed to `sycl::free()` must be from the same `context` as the one of the `queue` passed to `free()`. Since every `sycl::queue` creates a new `context` by default, this is not the case. So this is illegal in oneAPI too.
> 
> Now AdaptiveCpp generally does not care about `context` to the same extent as oneAPI because AdaptiveCpp automatically manages `context` internally. I.e. `sycl::context` is not directly coupled to backend context objects. However, the lifetime of the runtime depends on user-facing SYCL objects: The AdaptiveCpp runtime starts up when the first SYCL object is constructed, and it is shutdown when there are no SYCL objects around anymore.
> 
> In your code, the runtime starts up at the beginning of `funcc()` and then shuts down at the end of `funcc` because at that point, there is no SYCL object around anymore. When the runtime shuts down, in general it takes everything with it, so pointers may become invalid (this is in line with the SYCL specification, which mandates that pointers can only be used in the same `sycl::context` they were created in).
> 
> Consequently, `free()` fails. Note that even if it worked, this pattern is not desirable because a runtime restart can have substantial negative performance impact: Devices are queried again, backends are initialized again, and also the kernel cache is emptied, so JIT is triggered again. Thus, you should avoid such patterns. There should always be at least one SYCL object alive (e.g. `sycl::context`, as intended by the specification) while your program is not done doing SYCL work.

Thank you very much for the excellent explanation! I understood the problem perfectly and was able to solve it. Congratulations on this incredible implementation. Compiling with "generic" is simply impressive. Keep it up, regards.
