### ISSUE TITLE
CUDA Install Documentation Needs Updating

### ISSUE THREAD

**Issue by Kiguli** [AdaptiveCpp/AdaptiveCpp#1238]
**Bug summary**

The documentation recommends the flag:

`-DCUDA_TOOLKIT_ROOT_DIR=/path/to/cuda`

however, this throws an error and the correct flag appears to be:

`-DCUDAToolkit_LIBRARY_ROOT=/path/to/cuda`

**Describe your setup**

Trying to install AdaptiveCPP on Linux machine with NVIDIA GPU.

**Comment by illuhad** [comment]
IIRC, we put logic in place so that both should work. Perhaps @nilsfriess knows more?

**Comment by nilsfriess** [comment]
What exactly is the error you're getting @Kiguli? And which CMake version are you using?

I think passing `-DCUDA_TOOLKIT_ROOT_DIR` _should_ work independent of the CMake version (our FindCUDA.cmake is basically a compatibility module that ensures this). I'm not sure about `-DCUDAToolkit_LIBRARY_ROOT` since we're not doing anything with this variable when trying to find CUDA, this variable should be set by CMake once CUDA has been found. The "correct" variable when using CMake version >= 3.17 would be `CUDAToolkit_ROOT` but as mentioned above we have a compatibility layer that also allows users to use `CUDA_TOOLKIT_ROOT_DIR`

**Comment by Kiguli** [comment]
I found I was having the following error:

`cmake -DCMAKE_INSTALL_PREFIX=./_inst -DCUDA_TOOLKIT_ROOT_DIR=/usr/lib/cuda-11.8/
    CMake Warning:
      No source or binary directory provided.  Both will be assumed to be the
      same as the current working directory, but note that this warning will
      become a fatal error in future CMake releases.
    
    
    CMake Warning at cmake/FindCUDA.cmake:42 (message):
      CUDAToolkit_LIBRARY_ROOT does not point to the correct directory, try
      setting it manually.  Detected CUDA installation cannot be used.
    Call Stack (most recent call first):
      CMakeLists.txt:91 (find_package)`

By setting `CUDAToolkit_LIBRARY_ROOT` directly it then compiled for me. Perhaps the error was only in my case, and both work for others.

**Comment by nilsfriess** [comment]
I think you might have run into an edge case that does indeed require setting `CUDAToolkit_LIBRARY_ROOT` manually. This happens if CMake can find the CUDA Toolkit installation but doesn't set `CUDAToolkit_LIBRARY_ROOT` itself. We try to guess `CUDAToolkit_LIBRARY_ROOT` from other CMake variables in this case but our "guessing" is not very sophisticated and it seems to not always work (as in your case). Glad that it works now!
