### ISSUE TITLE
Consider support for specialization constant and kernel_bundle

### ISSUE THREAD

**Issue by Rbiessy** [AdaptiveCpp/AdaptiveCpp#1296]
**Describe the motivation for the feature request**
In order to be compatible with other SYCL implementation it would be useful if AdaptiveCpp would support features from the SYCL 2020 specifications.

**Describe the solution you'd like**
Features from https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html are supported, in particular spec constant and kernel_bundle.

**Additional context**
I am wondering if there is any plan to support these features in the future? I understand that spec constant are handled differently in AdapatviceCpp with the generic compilation and that kernel_bundle may not fit well with its design. However supporting these features would be needed if we want SYCL libraries to be built with multiple SYCL implementations.
I am working on [portFFT](https://github.com/codeplaysoftware/portFFT) in particular which heavily relies on spec constant to optimize kernels and kernel_bundle to allow us to JIT compile kernels at "commit time" (which is a common step done before computing a DFT).

**Comment by illuhad** [comment]
Both of these features are known to be broken and only work with specific SYCL implementation choices.
They were put into the SYCL specification without any prior implementation experience, and never should have been merged into SYCL 2020 in the first place.  IMO they should be deprecated and turned into optional features, as they hardcode assumptions that only make sense in the DPC++ world.

We have plans to support the optimizations enabled by specialization constants natively. I.e. you will not need any special constructs to benefit from this, as it will automatically specialize kernels automatically. That it is possible to expose this functionality in this way shows that specialization constants as a user-facing concept as currently defined by SYCL 2020 is just a silly concept that adds unnecessary complexity.

**Comment by sommerlukas** [comment]
Thanks for your quick reply @illuhad!

Leaving kernel bundles aside for a second, I wonder if there is still value in implementing specialization constants. 

I agree that automatic specialization of kernels without user intervention is a nice feature, but portability of code relying on such automatic specialization would be limited. 
While an elaborate runtime compiler can perform the specialization, implementations relying on a less elaborate runtime compiler would not be able to support such code.  Specialization constants give such implementations a mechanism to still provide user-driven specialization of kernels. 

Also, it may not always be desirable to use all parameters of a kernel for specialization. For parameters that change frequently between different launches of the same kernel, this would lead to significant overhead due to recompilation. 
With automatic specialization, there is no way for users to express which parameters should be used for specialization and which shouldn't. The specialization constant API solves this problem. 

Given a runtime compiler that already supports automatic specialization, specialization constants could also be implemented on top of such a compiler.

**Comment by illuhad** [comment]
I agree that in some cases there may be value in providing a mechanism to allow for more control. But I don't think the specialization constant API is a good fit here. 

Due to the decoupling of specialization id and specialization value and the type erasure of the `kernel_handler` type, I don't see a way of implementing the current specialization constant API as a zero cost abstraction for compilation flows where it needs to be emulated (particularly in a library-only scenario). This is particularly unfortunate, because spec constants are expected to appear in the hottest code paths, where every bit of additional overhead is strictly undesirable and might have a noticable impact on performance.

I don't think it's a good path forward to recommend an API to users that might have an actively detrimental effect on performance for all compilation flows except `generic`. To me it makes more sense to either have some kind of explicit JIT programming API that only works with the `generic` compiler and exposes all the power of JIT compilation which might even be more powerful than current spec constants, or to have a different API that is a true zero cost abstraction for all compilation flows.


> Also, it may not always be desirable to use all parameters of a kernel for specialization. For parameters that change frequently between different launches of the same kernel, this would lead to significant overhead due to recompilation.

That is true, but is also something I have plans to address in the approach I envision :) The tradeoff between kernel runtime and additional JIT overhead is exactly where this optimization gets interesting.
