### ISSUE TITLE
Insufficient c++ standard c++11 when using acpp as a non-SYCL compiler

### ISSUE THREAD

**Issue by tom91136** [AdaptiveCpp/AdaptiveCpp#1300]
So this is an interesting one, some background:
We happen to use CMake FetchContent a lot and build various subprojects such as oneTBB this way.
oneTBB, among other projects, sets `-std=c++11` in  their CMakeList which is intended because those project supports very old compilers.

Unfortunately, for StdPar where you want  `CXX=acpp`, or even just a mixed-standard SYCL project, we're hit with a check in the wrapper that short circuits early when the standard is too low:

https://github.com/AdaptiveCpp/AdaptiveCpp/blob/2333dc631b38510f43e1c59f23ffc8e05d13daa6/bin/acpp#L610-L611

To validate, I've removed the check and compiled TBB as-is with acpp and everything worked correctly.

I think one way of solving this would be to defer the check to the actual headers that has C++17 requirements.
Maybe a macro using the typical `__cplusplus >= 201703L` check.
That way, normal sources would compile regardless of `-std` value and SYCL or StdPar sources would still work the same.

**Comment by illuhad** [comment]
> I think one way of solving this would be to defer the check to the actual headers that has C++17 requirements.

I'm not sure this would actually work. The reason we check in `acpp` and not in the headers is that we can *fix* things inside `acpp`.  Once the headers are parsed, it's either success or error.
For example, if AdaptiveCpp is built against a C++ compiler that does not default to C++17, `acpp` will automatically add `-std=c++17`. In order to do this, we need to know whether the user has not also set another std version. If it's newer, that's fine, but if it's older, there's a conflict: In this case the user has explicitly requested a configuration that we cannot support.


> or even just a mixed-standard SYCL project

Any SYCL project should use `add_sycl_to_target()`, which circumvents having to set `CMAKE_CXX_COMPILER`, so in this case this should not be an issue.

> Unfortunately, for StdPar where you want CXX=acpp

In that case, I'm not sure I understand how that would actually work: Won't you also have to add `--acpp-stdpar` to `CMAKE_CXX_FLAGS`? As soon as stdpar compilation is requested, we need to compile with C++17 enabled, as some content is included regardless of whether the user actually includes PSTL headers (e.g. in order to properly intercept memory allocations).

> We happen to use CMake FetchContent a lot and build various subprojects such as oneTBB this way.
oneTBB, among other projects, sets -std=c++11 in their CMakeList which is intended because those project supports very old compilers.

Wouldn't the better solution be to use a cmake `ExternalProject` for TBB? This would allow you to have a separate `CMAKE_CXX_COMPILER` for TBB compared to the rest of the project.
I think architecturally, this makes a bit more sense because AdaptiveCpp stdpar effectively has TBB as a dependency too (due to conditional offloading, it also compiles an execution path through host PSTL, which then typically needs TBB). Requiring `acpp` to be able to compile TBB when TBB is a dependency for `acpp` does not seem to make a lot of sense to me.

There's some discussion in #1290 about supporting regular host compilation as a fallback if neither `--acpp-targets` nor `--acpp-stdpar` is provided, and AdaptiveCpp was compiled without the SSCP compiler. However, ultimately I think we still would like to introduce `--acpp-targets=generic` as a default where possible (that's the whole point of generic target - it works everywhere and is thus suitable as a default). In that case there's not way around C++17 either.
