### ISSUE TITLE
include <iostream> error

### ISSUE THREAD

**Issue by Kiguli** [AdaptiveCpp/AdaptiveCpp#1312]
**Bug summary**
A clear and concise description of what the problem is.

Running AdaptiveCPP on Linux using acpp compiler seems to have an error where 'iostream' is no longer included via
`#include <iostream>`. I get the following error:

`fatal error 'iostream' file not found`

I have been running adaptivecpp fine on my machine, I recently then reinstalled and I got this error. I wonder if it relates to a newer version of adaptiveCPP?

I wonder which compiler is being used underneath and I can try and manually include the correct iostream. As far as I know I have all the usual culprits such as gcc, g++, clang, clang++, etc.

**Comment by illuhad** [comment]
Hi, this typically happens if you have `g++-<VERSION>` package installed, but are missing `libstdc++-<VERSION>-dev` or similar.

AdaptiveCpp relies on clang for most compilation flows. Clang does by default not come with C++ headers by itself, but instead tries to use existing system headers. If you have multiple gcc versions installed, it picks the newest toolchain. If you are then missing the `libstdc++` for that gcc version, you get these kinds of issues.

It's very unlikely that this is due to AdaptiveCpp itself, and most likely that this is a problem of the underlying clang. E.g., when reinstalling AdaptiveCpp, cmake might have picked up a different LLVM installation that behaves differently.

In any case, please try to first valdidate whether the underlying compiler that you are using with AdaptiveCpp works correctly. Manually including headers is not a fix for such toolchain issues.

You can find out which compiler it invokes by adding the `--acpp-dryrun` flag, which will print the full compiler invocation.

**Comment by Kiguli** [comment]
I managed to resolve the issue. I'll add it just in case it helps a future reader:

I ran:

`sudo apt install -y libclang-16-dev clang-tools-16 libomp-16-dev llvm-16-dev`

then compiled and explicitly gave several locations:
`sudo cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16 -DLLVM_DIR=/usr/lib/llvm-16/cmake -DCUDAToolkit_LIBRARY_ROOT=/usr/lib/cuda`

My code now runs and compiles :)
