### ISSUE TITLE
installing with nvc++ and no LLVM; bug or confusing documentation?

### ISSUE THREAD

**Issue by hpcpony** [AdaptiveCpp/AdaptiveCpp#1401]
**Bug summary**
Documentation says you can use nvc++ without having to install LLVM  but that didn't work for me.  It still wanted clang.

**To Reproduce**
```
[gpu:build.nvcxx] cmake        \
>   -DBOOST_ROOT=/scr/opt/boost-1.84.0 \
>   -DCMAKE_INSTALL_PREFIX=/scr/opt/acpp-24.02.0-nvcxx        \
>   -DNVCXX_COMPILER=/scr/opt/NVIDIA/nvhpc_2023_239/Linux_x86_64/23.9/compilers/bin     \
>   -DCUDA_TOOLKIT_ROOT_DIR=/scr/opt/NVIDIA/nvhpc_2023_239/Linux_x86_64/23.9/cuda/12.2  \
>   -DWITH_CUDA_BACKEND=ON                                       \
>   -DWITH_CUDA_NVCXX_ONLY=ON                                    \
>   ..
```

**Expected behavior**
no errors

**Describe your setup**
RedHat 8 (gcc 8.5.0)
AdaptiveCpp-24.02.0.tar.gz
CUDA: see cmake above

Running the above cmake command eventually produces:

```
.
.
.
-- Found Threads: TRUE  
-- Found CUDA version 12.2.91 in /scr/opt/NVIDIA/nvhpc_2023_239/Linux_x86_64/23.9/cuda/12.2
-- Could not find HIP cmake integration, falling back to finding hipcc
-- Could not find ROCm installation by looking for hipcc. ROCm support unavailable.
-- Could NOT find LLVM (missing: LLVM_DIR)
-- Building hipSYCL against LLVM configured from LLVM_DIR-NOTFOUND
CMake Error at CMakeLists.txt:227 (message):
  Could not find clang executable


-- Selecting clang: CLANG_EXECUTABLE_PATH-NOTFOUND
CMake Error at CMakeLists.txt:264 (message):
  clang include path does not exist.  Please provide clang's internal include
  path manually: Find the directory where __clang_cuda_runtime_wrapper.h is.
  Provide this directory for older ROCm versions and the parent directory for
  newer ones.


CMake Error at CMakeLists.txt:284 (if):
  if given arguments:

    "LESS" "11" "AND" "false"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
```
The documentation at https://github.com/AdaptiveCpp/AdaptiveCpp/blob/v24.02.0/doc/install-cuda.md (the nvc++ part) says "This will allow you to use nvc++ without having to install LLVM." but I'm guessing that isn't exactly accurate nor precise?

**Comment by illuhad** [comment]
Hi, by default it looks for all backends that it can find on the system, and then attempts to enable them.

Most likely it has found OpenCL (which also typically comes as part of the CUDA SDK), and then tries to enable the SSCP compiler in order to be able to target OpenCL as well. Try `-DWITH_OPENCL_BACKEND=OFF -DWITH_SSCP_COMPILER=OFF`.

PS: LLVM-based compilation flows (in particular using `-DWITH_SSCP_COMPILER=ON` and `--acpp-targets=generic`) are likely to be more robust, have lower compile times, have better portability, and typically deliver higher performance compared to nvc++. The main advantage of nvc++ is deployment simplicity.

**Comment by hpcpony** [comment]
Magic!  Looks like that did the trick.

Thanks.

This is just to get me a chance to try acpp and compare it to dpcpp and some other OpenMP offload stuff.  Eventually (when I'm in the mood to fight with LLVM) I'll try to build a complete version.
