### ISSUE TITLE
Add NDzip benchmark 

### ISSUE THREAD

**Issue by stefano2734** [AdaptiveCpp/AdaptiveCpp#1439]
**Describe the motivation for the feature request**
A clear and concise description of what the problem is that prompted you to request this feature.

Ndzip is a new innovative accelerator for zip compression and decompression at gpu and better than nvComp of Nvidia.
Can you check the actual code in a Benchmark at your actual SYCL-CPP version?

**Describe the solution you'd like**

check run of ndzip with actual hardware comparison of Nvidia, amd and Intel.
https://github.com/celerity/ndzip

**If applicable, describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

https://dps.uibk.ac.at/~fabian/publications/2021-ndzip-a-high-throughput-parallel-lossless-compressor-for-scientific-data.pdf

https://dps.uibk.ac.at/~fabian/slides/2021-sc21-ndzip-gpu-efficient-lossless-compression-of-scientific-floating-point-data-on-gpus.pdf

**Comment by illuhad** [comment]
Hi, I'm not sure what needs to be done here from the perspective of the AdaptiveCpp project. Is there any issue with this particular application? I suggest you to just try it, and if there is a problem, please feel free to open an issue.

**Comment by stefano2734** [comment]
Compression and decompression are important in future gpu simulations.
NDzip is a candidate with sycl code and with benchmark code.

**Comment by illuhad** [comment]
Nobody is disputing the relevance of compression or decompression. But there are thousands of interesting codes out there. When we benchmark AdaptiveCpp again for a publication or just general performance evaluation work, we can consider also using this application.

But since no defect has been reported with respect to AdaptiveCpp's handling of this application, I am going to close this issue since there does not seem to be a problem with AdaptiveCpp.
