### ISSUE TITLE
SMCP for OpenCL?

### ISSUE THREAD

**Issue by yangfengzzz** [AdaptiveCpp/AdaptiveCpp#1443]
I found there olny SSCP for OpenCL, Is it possible to implement OpenCL SMCP compilation flow in the future? I found it difficult to embed OpenCL into Cpp like CUDA

**Comment by illuhad** [comment]
It is not planned to implement SMCP for OpenCL, and there is also no reason or use case to do so. The SSCP compiler is superior in every way to the SMCP approach: It compiles faster, generates faster binaries, allows for additional JIT-time optimizations that are not possible with the SMCP compilers, is more portable and extensible, and is a more elegant design.

Why do you want an SMCP compiler?

The only thing that the SMCP compilers give you is that they allow to mix-and-match CUDA/HIP source code with SYCL. This can be useful when migrating code. For OpenCL, this is irrelevant because OpenCL has a separate source compilation models, so wouldn't get the same benefits from an SMCP compiler either.

**Comment by yangfengzzz** [comment]
Because on my device there is only OpenCL. So I hope there is a SMCP compiler to compile directly. I think SSCP is too troublesome by saving LLVM IR. With SSCP, additional transcoding work has to be done at runtime.

**Comment by illuhad** [comment]
It has a persistent on-disk kernel cache that negates pretty much all of those effects after the first application run. And even in plain OpenCL with ahead of time code generation, the driver would still need to lower SPIR-V at runtime to OpenCL, because this is how OpenCL works.

Please try SSCP first before asking for someone else. Again, it is superior to SMCP compilers in every way.
