### ISSUE TITLE
Is it actually binding to a temporary object

### ISSUE THREAD

**Issue by TheBjoel2** [AdaptiveCpp/AdaptiveCpp#1498]
Consider the following code
```cpp
#include <iostream>
#include <cstdint>
#include <vector>
#include <sycl/sycl.hpp>

class A
{
private:
    using AccessorType = sycl::accessor<uint64_t, 1, sycl::access::mode::read, sycl::access::target::device>;
    const AccessorType& m_Ref;

public:
    A(const auto& ref):
        m_Ref(ref){}
};

int32_t main()
{
    std::vector<uint64_t> yeah(1);
    sycl::buffer<uint64_t, 1> buf{yeah.data(), sycl::range<1>{yeah.size()}};
    
    sycl::queue q;
    q.submit([&](sycl::handler& h)
    {
        sycl::accessor acc{buf, h, sycl::read_only};

        A a(acc);
    });
}
```
Here we have a class ``A`` that takes ``const auto&`` as a parameter to then initialize ``m_Ref`` of type ``const sycl::accessor<...>&``. Having ``auto`` parameters in constructors is legal since c++20.

However, if you try to build this code, you'll get a compilation error
```
<source>:14:15: error: reference member 'm_Ref' binds to a temporary object whose lifetime would be shorter than the lifetime of the constructed object
   14 |         m_Ref(ref){}
      |               ^~~
<source>:27:11: note: in instantiation of function template specialization 'A::A<hipsycl::sycl::accessor<unsigned long, 1, hipsycl::sycl::access_mode::read, hipsycl::sycl::target::device, hipsycl::sycl::accessor_variant::unranged>>' requested here
   27 |         A a(acc);
      |           ^
<source>:10:25: note: reference member declared here
   10 |     const AccessorType& m_Ref;
      |                         ^
1 error generated.
```
which could be fixed by making ``A`` constructor to take ``const AccessorType&`` as a parameter
```cpp
A(const AccessorType& ref):
```
What makes me think that something is abnormal, is the fact that intel oneAPI allows such code to be compiled.

Is it a bug or am I doing something wrong(most probably)?

**Comment by illuhad** [comment]
Define the `ACPP_STRICT_ACCESSOR_DEDUCTION` macro before including `sycl.hpp`, e.g. by compiling with the `-DACPP_STRICT_ACCESSOR_DEDUCTION` flag.
(if you don't have a fairly recent clone of AdaptiveCpp, the macro might be called `HIPSYCL_STRICT_ACCESSOR_DEDUCTION`).

What happens is that AdaptiveCpp by default has an extension enabled that allows accessors to encode in the exact template type how they were constructed, if you rely on the CTAD deduction guides as in your example. This allows the accessor to perform internal storage optimizations which can help performance in some cases. See here for more information:
https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/doc/accessor-variants.md

This means that the accessor type you pass into the class is almost, but not *exactly* the same as the member in your class. There are some implicit conversion operators, so a temporary is created which is why you get this error.

The macro disables this extension.

Unless you have very, very good reason I would recommend to stay clear of the buffer-accessor model. Just use the USM memory management model instead. It's easier to understand, more robust, has less surprising behavior and also has lower overhead, so you get better performance.

**Comment by TheBjoel2** [comment]
thanks dude
