### ISSUE TITLE
Where to find the benchmarks?

### ISSUE THREAD

**Issue by ruben-laso** [AdaptiveCpp/AdaptiveCpp#1671]
Hi,

With the release notes, some benchmarks are shown (e.g. [v24.10](https://github.com/AdaptiveCpp/AdaptiveCpp/releases/tag/v24.10.0)).
I would like to know if the code of these benchmarks is available publicly and, if so, where to find them.

Best,
Ruben Laso

**Comment by illuhad** [comment]
Hi Ruben,

all benchmarks are available publicly.

`cloverleaf` and `minibude` are miniapps from the University of Bristol and can be found on https://github.com/uob-hpc/cloverleaf and https://github.com/uob-hpc/minibude.

There are also publications about those two apps, which you can find using the search engine of your choice.

`nbody`, `FFT`, `easywave`, `XSBench` are from HeCBench (https://github.com/zjin-lcf/HeCBench), which however only collects benchmarks from various other sources. The original XSBench repository is https://github.com/ANL-CESAR/XSBench.

`toybrot` is from here: https://gitlab.com/VileLasagna/toyBrot (`raymarched` directory). Run with `ACPP_PERSISTENT_RUNTIME=1` to prevent unnecessary runtime restarts for every iteration due to the current design of the SYCL version of the benchmark.

**Comment by ruben-laso** [comment]
Thanks so much for the detailed response!
I'll try to run some of these benchmarks in the next few days.

**Comment by illuhad** [comment]
You're welcome :)

**Comment by ruben-laso** [comment]
How do you compile and run the benchmarks? For example, CloverLeaf has different "Input Decks", different compiler options can be passed, etc.

Do you have scripts to automate the benchmarking process so I can check these things?

**Comment by illuhad** [comment]
The compiler flags used are described on the release page (https://github.com/AdaptiveCpp/AdaptiveCpp/releases/tag/v24.10.0) under "benchmark notes".

There's no script yet to automate these. Cloverleaf has a cmake infrastructure, so you just need to follow that (and ensure that `-ffast-math` is used uniformly everywhere).

Note that some benchmarks may need some argument to configure the target device; `cloverleaf` and `minibude` have a `--device` command line argument. The HeCBench benchmarks generally need to be built with `-DUSE_GPU` to offload (which is a pattern I really dislike, but it is what it is).

The cloverleaf input file was `bm64_short.in`.
For `miniBUDE`, use `-w 128 -p 1,2,4` with the default problem.
For `nbody`, I've used problem size `256000` (e.g. run with `./nbody 256000 20` - the second argument is the number of iterations).
FFT was run with the default flags from HeCBench (see the `run` part of the Makefile).
easywave was run with `-time 240`.

For the iGPU benchmark results, I had to reduce problem sizes for some of the benchmarks because that GPU is just too weak compared to the other ones. This might not be necessary for you depending on what hardware you have available.
