### ISSUE TITLE
std::complex multiply in kernel produces wrong result

### ISSUE THREAD

**Issue by bd4** [AdaptiveCpp/AdaptiveCpp#340]
Running [complex.cxx](https://github.com/bd4/sycl-test/blob/master/complex.cxx), which does multiply on std::complex array elements in a kernel, with hipSYCL on AMD RX 570, results in garbage results:

```
$ make -f Makefile.hipsycl
$ ./build-hipsycl/complex gpu
[GPU  ] Device 67df {AMD}
0: (0,0) * (0,0) = (5.51054e+84,3.92651e-261)
1: (1,-1) * (1,1) = (4.88846e-20,8.07758e-276)
2: (2,-2) * (2,2) = (5.51054e+84,3.92651e-261)
3: (3,-3) * (3,3) = (4.88844e-20,8.07758e-276)
4: (4,-4) * (4,4) = (5.51054e+84,3.92651e-261)
5: (5,-5) * (5,5) = (4.88846e-20,8.07758e-276)
6: (6,-6) * (6,6) = (5.51054e+84,3.92651e-261)
7: (7,-7) * (7,7) = (4.88846e-20,8.07758e-276)
8: (8,-8) * (8,8) = (5.51054e+84,3.92651e-261)
9: (9,-9) * (9,9) = (4.88846e-20,8.07758e-276)
10: (10,-10) * (10,10) = (5.51054e+84,3.92651e-261)
11: (11,-11) * (11,11) = (4.88846e-20,8.07758e-276)
12: (12,-12) * (12,12) = (5.51054e+84,3.92651e-261)
13: (13,-13) * (13,13) = (4.88846e-20,8.07758e-276)
14: (14,-14) * (14,14) = (5.51054e+84,3.92651e-261)
15: (15,-15) * (15,15) = (4.88846e-20,8.07758e-276)
```

Addition on the other hand produces the correct result. I built b4d2e1185a86f6fc6ce58828bd9856d120eeb9b7 from source, against ROCm 3.8.0 on Ubuntu 18.04.

Aside: my other simple examples, including a usm test, are working using the ROCm backend. I have not yet been able to get CUDA or CPU backends to work on my test machine.

**Comment by illuhad** [comment]
Well, officially SYCL doesn't support `std::complex` inside kernel code (or any other `std::` stuff really, with only a few exceptions). In general, `std::` code might work, or might not work inside kernels with hipSYCL.

The reason why we cannot really make guarantees about such code is because it depends on the implementation of the standard library. There are restrictions inside SYCL kernels that any kernel code must obey. STL code might violate these restrictions. For example, a simple `assert()` may be enough to cause problems because `assert()` might call `std::terminate()` which is unavailable on device. Or code might make other assumptions that are only true on the host.

gfx80x support in ROCm is shaky in general, independently of hipSYCL. There have been numerous reports of people having encountered compiler bugs with that hardware generation. hipSYCL doesn't touch code generation at all (it mainly does an additional AST pass to make sure that everything required by a kernel is treated as HIP/CUDA `__host__ __device__`), so whatever happens usually happens because of the clang HIP compiler..

I don't see how we could fix this - likely it's either caused by the STL implementation or a bug in clang HIP or the amdgpu LLVM backend (potentially for gfx80x generation specifically). You could try a different clang and/or ROCm version.
If feasible I would also recommend using a custom `complex` implementation which would also be in line with the SYCL specification. With that said, I think there should at least be a `sycl::complex` in the specification for users who need complex numbers.

**Comment by bd4** [comment]
+1 for a `sycl::complex` in the specification, I've been pushing for something like that: https://github.com/intel/llvm/issues/2061. `std::complex` works with Intel's implementation with the `-device-math-lib=fp32,fp64` option and ComputeCPP with `-ffast-math`, but using `sycl` namespace is probably a cleaner way to standardize this.

I see what you mean regarding HIP support - it seems to work on some machines and not others depending on the C library implementation. My [gtensor](https://github.com/wdmapp/gtensor) HIP backend happens to be working with complex numbers on my test machines, but I guess I just got lucky. For CUDA, using `thrust::complex` works well, `std::complex` not so much. Which is fine because `thrust::complex` is included with all recent cuda distributions and with type aliasing I can bring it in to whatever namespace is convenient (gtensor does this with `gt::complex`).

**Comment by illuhad** [comment]
What I could offer you if you are interested in `sycl::complex` is that we add that class in hipSYCL. In general it's always a good idea for standardization if you can point to an implementation that has already successfully prototyped a feature and it might be an incentive for other implementations to follow.
Of course the fastest way to add this would be if you create a PR, otherwise I can work on it at some undetermined point in the future when I have time for it ;)

**Comment by keryell** [comment]
I guess NVIDIA had solved this with their C++ core library. 
Perhaps their implementation can be used here? @brycelelbach

**Comment by brycelelbach** [comment]
Oh Ronan :). You do love asking me questions I cannot answer.

`std::complex`, the class template, is the easy part -  at least functionally. The challenging part is associated math library functions. Fortunately CUDA has an excellent math library team.

My guess would be that the problem here is a miscompile, NOT an issue with `std::complex`. Multiply is fairly "boring". The common standard libraries (including libc++, which my team uses) do typically implement multiply with some intrinsics, but I see no reason why [this code or code like it](https://github.com/llvm/llvm-project/blob/master/libcxx/include/complex#L589-L646) would not work. The fact that the code compiled means that the relevant builtins exist, or at least the compiler is aware of them. It's possible they are defined wrong. Try turning off device code optimizations and see if it repros.

I believe that is the extent to which I can provide assistance in this regard, given my current employer and line of work.

> For CUDA, using thrust::complex works well, std::complex not so much. 

Stay tuned. Everything is `std::`, including `complex`, is coming to an NVIDIA GPU near you soon. And I do mean everything.

**Comment by keryell** [comment]
> My guess would be that the problem here is a miscompile, NOT an issue with `std::complex`. Multiply is fairly "boring". The common standard libraries (including libc++, which my team uses) do typically implement multiply with some intrinsics, but I see no reason why [this code or code like it](https://github.com/llvm/llvm-project/blob/master/libcxx/include/complex?rgh-link-date=2020-10-15T00%3A38%3A44Z#L589-L646) would not work. The fact that the code compiled means that the relevant builtins exist, or at least the compiler is aware of them. It's possible they are defined wrong. Try turning off device code optimizations and see if it repros.

Ouch! :-(

> I believe that is the extent to which I can provide assistance in this regard, given my current employer and line of work.

Thanks for the hints at least, my dear coopetitor! :-)

Since most of the code is open-source, we can probably layer or retarget a lot of things by playing with (inline) namespaces and so on. No need to reimplement things just for the sake of reimplementing things...

> > For CUDA, using thrust::complex works well, std::complex not so much.
> 
> Stay tuned. Everything is `std::`, including `complex`, is coming to an NVIDIA GPU near you soon. And I do mean everything.

You said "everything"... My secret plan is to accelerate all the FPGA bitstream generation by x1000 by using GPU. This is "just" C++ using the STL, right? :-)

**Comment by illuhad** [comment]
I've just had a look at the LLVM IR that comes out, and I can see nothing that would be a problem on device. 

The code also runs fine and produces correct results for me with current hipSYCL and clang 10 on my Radeon VII (with ROCm 3.8) as well as GTX 1080 (with CUDA 11.0). I agree that it is probably a miscompile - likely a bug in the amdgpu LLVM backend for that particular chip.

**Comment by bd4** [comment]
> What I could offer you if you are interested in `sycl::complex` is that we add that class in hipSYCL. In general it's always a good idea for standardization if you can point to an implementation that has already successfully prototyped a feature and it might be an incentive for other implementations to follow.
> Of course the fastest way to add this would be if you create a PR, otherwise I can work on it at some undetermined point in the future when I have time for it ;)

This is a great idea thank you! I am interested to try implementing it, although not sure how soon I will have time (will see who gets to it first I guess? Will let you know before starting work so we don't duplicate effort). I think just implementing conj /norm/plus/minus/multiply/divide is almost trivial, like @brycelelbach said it's all the math functions that get complicated. We could start simple and expand. For the Fusion code I am working on porting to different GPUs, we are actually only using the basic operations - I think that covers a non-trivial number of use cases.

**Comment by bd4** [comment]
My complex.cxx example works on Ubuntu 20.04 with same version of hipSYCL and ROCm, same GPU RX 570 (gfx 803) (in a different chroot). It appears to be an issue with Ubuntu 18.04 and ROCm 3.8 packages, perhaps with gcc7 version of std lib.

I'm going to go ahead an close the issue, and create a new feature request re sycl:complex prototype. In my experience std::complex support is inconsistent and fragile in SYCL implementations, which is a real problem for the application I am working on.
