### ISSUE TITLE
Building instructions not up to date/cmake problem

### ISSUE THREAD

**Issue by DieGoldeneEnte** [AdaptiveCpp/AdaptiveCpp#343]
In the [build instructions](https://github.com/illuhad/hipSYCL/blob/develop/doc/installing.md) the `CLANG_INCLUDE_PATH` is described as
> CLANG_INCLUDE_PATH must be pointed to the clang internal header directory. Typically, this is something like $LLVM_INSTALL_PREFIX/include/clang/\<llvm-version\>/include.

Because the cuda-header are included as `include/cuda_wrappers/*` the path needs to be the parent directory:
[...]/include/clang/\<llvm-version\>/include/..
This is done by cmake if the include path is automatically found \[1\], but not when it is given (`-DCLANG_INCLUDE_PATH=...`).

I think it is enough if this is noted in the build instructions, but it should also be reasonably easy to do in cmake.

\[1\]: https://github.com/illuhad/hipSYCL/blob/f689b1099362df57669496a7b7a44e2e62610533/CMakeLists.txt#L103

**Comment by illuhad** [comment]
The reason for this behavior is that there is a difference between recent ROCm stacks (e.g. 3.8) and older ones such as the one from our packages (I think something like 3.3). 
By default, hipSYCL treats the path as one for newer ROCm stacks in which case we need the parent directory.

For older stacks, you however need the `include` directory, not the parent directory. In order to be able to support both (and consequently not break our packages that rely on an older stack), cmake assumes that if you set it manually you know what you are doing and just takes it as is.

But yeah, maybe we should describe this better in the build instructions.
