### ISSUE TITLE
hipSYCL cuda version detection fails

### ISSUE THREAD

**Issue by jjcasmar** [AdaptiveCpp/AdaptiveCpp#344]
I am trying to do some tests with hipSYCL and CMake but cmake complains about the version I have is just 7.0 and it can't support sm_60. I have double checked my installation and apparently is 11.1.

This is the error I have:
```
clang-10: error: cannot find libdevice for sm_60. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang-10: error: GPU arch sm_60 is supported by CUDA versions between 8.0 and 10.1 (inclusive), but installation at /opt/cuda is 7.0.  Use --cuda-path to specify a different CUDA install, pass a different GPU arch with --cuda-gpu-arch, or pass --no-cuda-version-check.
ninja: build stopped: subcommand failed.
```

I checkec the version I have doing the following:

```
 kdab@archlinux  /opt/cuda  which nvcc
/opt/cuda/bin/nvcc
 kdab@archlinux  /opt/cuda  nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

Am I understanding something wrong here? Why is hipSYCL failing to check correctly my cuda version?

**Comment by illuhad** [comment]
It's a clang issue, not a hipSYCL issue.  The issue is that clang doesn't recognize your CUDA installation's version, in which case it will misleadingly print that it is 7.0.

Officially clang's CUDA toolchain only supports up to CUDA 10.1. It can detect up to CUDA 11.0 in which case it will treat them as if it were 10.1 (which usually works). 
clang does not yet know about 11.1. So, you can either wait until upstream clang adds detection support for 11.1, or downgrade CUDA to 11.0.

**Comment by jjcasmar** [comment]
Downgrading worked fine. Thank you very much for answering so fast!
