### ISSUE TITLE
sycl::stream gives no output

### ISSUE THREAD

**Issue by VictorEijkhout** [AdaptiveCpp/AdaptiveCpp#350]
I've installed hipSycl on an OpenMP platform with the Intel compiler. Using `sycl::stream` inside `parallel_for` gives no output. The same program works correctly on Intel devcloud.

```
#include <CL/sycl.hpp>
#include <vector>

namespace sycl = cl::sycl;

int main(int argc, char **argv) {

  const auto global_range = 4;

  sycl::queue myQueue;
  std::cout << "Hello example running on "
            << myQueue.get_device().get_info<sycl::info::device::name>()
            << std::endl;
  // Create a command_group to issue command to the group
  myQueue.submit([&](sycl::handler &cgh) {
      sycl::stream sout(1024, 256, cgh);
      cgh.parallel_for<class hello_world>
        (
         sycl::range<1>(global_range), [=](sycl::id<1> idx) {
           sout << "Hello, World: World rank " << idx << sycl::endl;
         }); // End of the kernel function
    });       // End of the queue commands.
  return 0;
}

[staff cxx:150] make hello && ./hello
syclcc -c hello.cxx  -std=c++17 -I/opt/apps/intel19/python3_7/boost/1.69/include -O2 -g
syclcc -o hello hello.o -L/opt/apps/intel19/python3_7/boost/1.69/lib
Hello example running on hipSYCL OpenMP host device
```

**Comment by illuhad** [comment]
`sycl::stream` is a no-magic implementation in hipSYCL that just calls `printf()`, so it's unlikely to be the cause of the problem. 

The issue is probably that the SYCL specification does not have implicit synchronization for `queue` in the destructor. Because of this, your program probably just exits before all kernels have completed.

When there's no other synchronization point (e.g. host accessor, or a buffer destructor) you need to call `queue::wait()` in SYCL to make sure that all work is done before the program exits.

**Comment by VictorEijkhout** [comment]
Thanks, that solved. it. Still a little surprised that even running on the host device the IO is not flushed, but I can't pretend to understand those layers, so: so be it.

**Comment by illuhad** [comment]
Probably you are not even getting to the actual IO inside the kernel. A SYCL implementation will construct a DAG in the background and submit operations asynchronously. This means it can happen that your kernel is still enqueued and has not yet run when the application terminates. Whether you are running on host or on some device makes no difference for these mechanisms.
