### ISSUE TITLE
OpenMP backend doesnt flush queue and copy at end of buffer lifetime

### ISSUE THREAD

**Issue by psath** [AdaptiveCpp/AdaptiveCpp#358]
Using the trivial vector add below, if I do not explicitly sync the queue, the results are not guaranteed to be available in `dev_sum` at the end of `sum_buf`'s lifetime as required by Sec. 4.7.2.3 "When the buffer is destroyed, the destructor will block until all work in queues on the buffer have completed, then copy the contents of the buffer back to the host memory (if required) _and then return_." (emphasis mine)

Frequently the data finishes copying during the validation loop.

Edit: the code below has been fixed to reflect @illuhad's answer and no longer exhibits the error, feel free to use it as a test case.
```C++
#include <CL/sycl.hpp>
#include <stdio.h>

int * a, * b, * dev_sum, * host_sum;
int nelem = 1000;

//Forward-declare the kernel
class vecAdd;

int main() {
  //allocate buffers
  a = (int*)malloc(sizeof(int) * nelem);
  b = (int*)malloc(sizeof(int) * nelem);
  dev_sum = (int*)malloc(sizeof(int) * nelem);
  host_sum = (int*)malloc(sizeof(int) * nelem);
  //initialize values
  for (int i = 0; i < nelem; i++) {
    a[i] = b[i] = i;
  }

  //get a default queue
  cl::sycl::queue q{};

  { //Open a data scope for the buffer lifetime
    cl::sycl::buffer<int> a_buf(a, cl::sycl::range<1>(nelem));
    cl::sycl::buffer<int> b_buf(b, cl::sycl::range<1>(nelem));
    cl::sycl::buffer<int> sum_buf(dev_sum, cl::sycl::range<1>(nelem));


    //Submit
    q.submit([&](cl::sycl::handler &cgh) {
      //Declare accessors to host data (outside the submission)
      auto a_acc = a_buf.get_access<cl::sycl::access::mode::read>(cgh);
      auto b_acc = b_buf.get_access<cl::sycl::access::mode::read>(cgh);
      auto sum_acc = sum_buf.get_access<cl::sycl::access::mode::discard_write>(cgh);
      cgh.parallel_for<class vecAdd>(cl::sycl::range<1>(nelem), [=](cl::sycl::id<1> i) {
        sum_acc[i] = a_acc[i] + b_acc[i];
      }); //Close kernel
    }); //Close submission
  } //Close data scope, output should be back on host

  //Compute host result
  for (int i = 0; i < nelem; i++) {
    host_sum[i] = a[i] + b[i];
  }

  //PS explicit wait. hipSYCL disobeys sec 4.7.2.3 buffer semantics
  //q.wait();

  //Validate device result vs host
  for (int i = 0; i < nelem; i ++) {
    if (dev_sum[i] != host_sum[i]) {
      fprintf(stderr, "Failure at element %d, dev=%d host=%d\n", i, dev_sum[i], host_sum[i]);
    }
  }

  //cleanup
  free(a);
  free(b);
  free(dev_sum);
  free(host_sum);
}
```

OS: Debian Buster
Kernel: 4.19.0-12-amd64
hipSYCL version: 4aea57afbd (with #303 merged)
ROCm version: 3.8.0 (using upstream AMD drivers, but that shouldn't matter for CPU-only execution)
Clang versions tried: 9, 10, and GitHub (78ae1f6c90029)
syclcc invocation:
`syclcc -o c-vec-add c-vec-add.cpp -isystem /path/to/hipsycl/install --hipsycl-platform=cpu`

**Comment by illuhad** [comment]
There are two significant issues with this code that violate the SYCL specification and likely explain the observed behavior.

## 1) Kernel captures by reference

> `cgh.parallel_for<class vecAdd>(cl::sycl::range<1>(nelem), [&](cl::sycl::id<1> i) {`

This kernel invocation is undefined behavior because you are capturing by reference.
* On GPU, this means that you are accessing the accessor via a host reference that will in general be not accessible from device.
* On CPU, it's still undefined because the kernel executes asynchronously in another thread. By that point the referenced accessors may have already left the scope, and accessing them is undefined behavior.

Therefore *always* capture by value.

## 2) Host accessors instead of device accessors.

You are constructing accessors without passing them a SYCL handler object (`cgh`). This means they are constructed as host accessors that provide a mechanism to access data outside of kernels. Using them is not allowed inside kernels, and is undefined behavior. This causes for example that the data requirements cannot be associated with the kernel (this connection is supposed to be established by the `handler` object), and the kernel therefore executes without any dependencies as a free node in the DAG. This is *not* the execution order you have intended.

Because the data requirements, and hence the buffer, are not associated with the kernel, a consequence is that the buffer cannot know that it is used by that kernel, and therefore cannot wait for the kernel to complete when it is destroyed at the end of the scope.

Additionally, device accessors must be declared inside the command group scope (i.e. within the lambda passed to `submit()`).

*The accessors used in kernels must always be declared inside the command group scope, and be device accessors constructed using the `handler` object.*

Can you confirm if the problematic behavior is still observed if those issues are fixed?

**Comment by psath** [comment]
Thanks for the quick reply and suggested fixes, they do appear to have corrected the issue on the OpenMP backend! Close it. Sorry for wasting your time; perhaps the explanation will help others migrating from OpenCL should they make a similar rookie mistake.

(Now to figure out why the ROCm backend is emitting an assertion problem deep within LLVM's Nvidia Code Generator... a separate issue to debug more thoroughly before I escalate.)

> There are two significant issues with this code that violate the SYCL specification and likely explain the observed behavior.
> 
> ## 1) Kernel captures by reference
> > `cgh.parallel_for<class vecAdd>(cl::sycl::range<1>(nelem), [&](cl::sycl::id<1> i) {`
> 
> This kernel invocation is undefined behavior because you are capturing by reference.
> 
> * On GPU, this means that you are accessing the accessor via a host reference that will in general be not accessible from device.
> * On CPU, it's still undefined because the kernel executes asynchronously in another thread. By that point the referenced accessors may have already left the scope, and accessing them is undefined behavior.
> Therefore _always_ capture by value.

Hmmm, so the submission lambda can capture by reference because it's still executing on the host, but that makes sense why the kernel would absolutely not want to do that. From an implementation standpoint, is the capture-by-copy when any necessary host-to-device transfers would occur, in order to satisfy the accessors' data requirements? (A side question we've been discussing internally is how to do explicit CUDA/OpenCL-like transfers a priori outside critical loops for profiling purposes, and "know" where the up-to-date copy of the data is.)

> 
> ## 2) Host accessors instead of device accessors.
> You are constructing accessors without passing them a SYCL handler object (`cgh`). This means they are constructed as host accessors that provide a mechanism to access data outside of kernels. Using them is not allowed inside kernels, and is undefined behavior. This causes for example that the data requirements cannot be associated with the kernel (this connection is supposed to be established by the `handler` object), and the kernel therefore executes without any dependencies as a free node in the DAG. This is _not_ the execution order you have intended.
> 
> Additionally, device accessors must be declared inside the command group scope (i.e. within the lambda passed to `submit()`).
> 
> _The accessors used in kernels must always be declared inside the command group scope, and be device accessors constructed using the `handler` object._

Ahh I moved these out because the capture-by-reference above was segfaulting and I missed a fundamental nuance about accessors. They're not "where the data resides", but "where the data is being used".

> 
> Can you confirm if the problematic behavior is still observed if those issues are fixed?

**Comment by illuhad** [comment]
> (Now to figure out why the ROCm backend is emitting an assertion problem deep within LLVM's Nvidia Code Generator... a separate issue to debug more thoroughly before I escalate.)

The amdgpu llvm backend is picky about using recursion in kernels, which sometimes causes problems with our `vec` implementation that relies on `constexpr` recursion. Is it this? This problem disappears when enabling optimizations.

>  Hmmm, so the submission lambda can capture by reference because it's still executing on the host, 

Yes, and because it is evaluated synchronously, unlike the actual kernel.

> but that makes sense why the kernel would absolutely not want to do that. From an implementation standpoint, is the capture-by-copy when any necessary host-to-device transfers would occur, in order to satisfy the accessors' data requirements? 

I'm not sure if I understand the question correctly. The copy-by-value is needed for the reasons that I had mentioned, satisfying the accessor data requirements is done by the SYCL runtime which in general is not able to get access to the captured data of kernel lambdas (because SYCL can also be implemented as a library without dedicated compiler, and C++ lacks reflection support).
The runtime knows which accessors are used by an operation because they are associated with the `handler` object of that operation at construction.

> (A side question we've been discussing internally is how to do explicit CUDA/OpenCL-like transfers a priori outside critical loops for profiling purposes, and "know" where the up-to-date copy of the data is.)

You can use `handler::copy()` and `handler::update_host()` to submit explicit memory operations. Alternatively you can use SYCL 2020 Unified Shared Memory (USM), which provides a more CUDA-like interface with pointers, SYCL malloc functions and potentially explicit memcpy operations between host and device.

> Ahh I moved these out because the capture-by-reference above was segfaulting and I missed a fundamental nuance about accessors. They're not "where the data resides", but "where the data is being used".

Yes, a device accessor basically does 3 things:
* It represents a requirement that must be satisified by the runtime before the kernel can execute (the specified data must be present and up-to-date on the target device);
* By checking for conflicting accessors used by other operations/kernels, it is used by the runtime to construct dependency edges between kernels and construct a task graph automatically;
* Inside kernels it provides a mechanism to access the requested data

The nice thing about the accessor model is that it allows to formulate code independently of whether it is going to run on a GPU (or other accelerator) later on, or on host where data transfers may not even be required at all.

**Comment by psath** [comment]
> > but that makes sense why the kernel would absolutely not want to do that. From an implementation standpoint, is the capture-by-copy when any necessary host-to-device transfers would occur, in order to satisfy the accessors' data requirements?
> 
> I'm not sure if I understand the question correctly. The copy-by-value is needed for the reasons that I had mentioned, satisfying the accessor data requirements is done by the SYCL runtime which in general is not able to get access to the captured data of kernel lambdas (because SYCL can also be implemented as a library without dedicated compiler, and C++ lacks reflection support).
> The runtime knows which accessors are used by an operation because they are associated with the `handler` object of that operation at construction.
> 

So when a new command group is submitted to a queue, the runtime basically has to look at all the accessors it defines, then look back at all previous (possibly completed, possibly not) CGs to see if any of them have touched the buffer(s) being accessed, and if so, insert the equivalent of one or more clEnqueueRead/Write/CopyBuffer if the up-to-date data resides on some other device than where the new CG is going to execute? I assume if those buffers are used by accessors on other queues, those dependencies show up in the DAG as well?

In OpenCL we would have had to manually daisy-chain a bunch of events and wait lists to get something similarly asynchronous. Super tedious. So, the SYCL accessor and task graph are a big win for figuring those dependencies out automatically, while leaving room for the runtime to potentially do clever stuff like pipelining behind the scenes.

I'm trying to figure out how to programmatically identify when those implicit transfers are happening (or force them to be explicit), to isolate them from kernel execution and be able to do an apples-to-apples performance comparisons with older explicit models like OpenCL. In theory, by skipping OpenCL/SPIR there is a chance for the backend code generator to use hardware intrinsics that aren't directly available through those models, so there's exciting room for exploration here.

I know the `info::event_profiling` API exists, but IMO the spec is unclear on whether `command_start` includes the implicit transfers necessary to initialize the accessors declared within the CG, including any possible transfers. In Sec. 4.8.2 of the 1.2.1 spec, it says "It is possible to obtain events for the start of the command group function object, the _kernel starting_, and the command group completing." However I'm unable to find anything the the Event Profiling, Command Group or Kernel specification that says how to get the middle one. (The 2020 Provisional has the same line in 4.10.3, but even with the introduction of the `kernel_hander`, which would be the logical place to provide such kernel-level profiling events, there's still nothing. Unless you perhaps use the new queue convenience functions for simplified kernel submission, but it's unclear how you define accessors for those to get data in/out since the device accessor must be defined within a CG.) The blunt approach that comes to mind then would be just submitting separate CGs for the explicit in/out transfers to make sure data is where you want it, and kernel(s) and then getting the profiling info from each CG's event.

> > (A side question we've been discussing internally is how to do explicit CUDA/OpenCL-like transfers a priori outside critical loops for profiling purposes, and "know" where the up-to-date copy of the data is.)
> 
> You can use `handler::copy()` and `handler::update_host()` to submit explicit memory operations. Alternatively you can use SYCL 2020 Unified Shared Memory (USM), which provides a more CUDA-like interface with pointers, SYCL malloc functions and potentially explicit memcpy operations between host and device.

Thanks for the pointers. We've got some more complicated code that is going to use the copy method that I have to go back and fix for misusing accessors. On re-reading this section of the spec, it also looks like you can directly use a host pointer as src/dst, without having to construct a buffer from it and incurring an extra implicit copy in the associated device accessor.

**Comment by psath** [comment]
> > (Now to figure out why the ROCm backend is emitting an assertion problem deep within LLVM's Nvidia Code Generator... a separate issue to debug more thoroughly before I escalate.)
> 
> The amdgpu llvm backend is picky about using recursion in kernels, which sometimes causes problems with our `vec` implementation that relies on `constexpr` recursion. Is it this? This problem disappears when enabling optimizations.

It's this kernel, so the code generator shouldn't have to be handling any recursion. Turning on -O2 and -O3 do not help. With Clang 9/10 with assertions on it aborts at compile time with an error in

`llvm-9.0.1.src/tools/clang/lib/CodeGen/CGCUDANV.cpp:235: virtual void {anonymous}::CGNVCUDARuntime::emitDeviceStub(clang::CodeGen::CodeGenFunction&, clang::CodeGen::FunctionArgList&): Assertion '(CGF.CGM.getContext().getAuxTargetInfo() && (CGF.CGM.getContext().getAuxTargetInfo()->getCXXABI() != CGF.CGM.getContext().getTargetInfo().getCXXABI())) || getDeviceStubName(getDeviceSideName(CGF.CurFuncDecl)) == CGF.CurFn->getName()' failed.`

The trace indicates it's trying to generate for

`hipSYCL/build-clang-9/install/bin/../include/hipSYCL/glue/hip/../generic/hiplike/hiplike_kernel_launcher.hpp:103:1: Generating code for declaration 'hipsycl::glue::hiplike_dispatch::parallel_for_kernel'`

With up-to-date clang with assertions off, it manages to compile, then fails at runtime with a 

`/src/external/hip-on-vdi/rocclr/hip_code_object.cpp:92: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")`

Same platform/invocation as the original issue, except with the flags changed to `--hipsycl-platform=rocm --hipsycl-gpu-arch=gfx900 -O2`

My just-starting-to-debug guess is that the gfx900 or gfx803 code is just not being produced, but I'm going to keep picking at it to see if I'm doing something wrong. Will file a separate issue if I can't work it out, as the illuminating discussion in this one has diverged enough already :smile:

**Comment by illuhad** [comment]
> So when a new command group is submitted to a queue, the runtime basically has to look at all the accessors it defines, then look back at all previous (possibly completed, possibly not) CGs to see if any of them have touched the buffer(s) being accessed, and if so, insert the equivalent of one or more clEnqueueRead/Write/CopyBuffer if the up-to-date data resides on some other device than where the new CG is going to execute? I assume if those buffers are used by accessors on other queues, those dependencies show up in the DAG as well?

Yes. It even works with queues from other backends or contexts.

> In OpenCL we would have had to manually daisy-chain a bunch of events and wait lists to get something similarly asynchronous. Super tedious. So, the SYCL accessor and task graph are a big win for figuring those dependencies out automatically, while leaving room for the runtime to potentially do clever stuff like pipelining behind the scenes.

Yes :) SYCL tries to make things simpler for the programmer, while simultaneously enabling automatic optimizations.

> I'm trying to figure out how to programmatically identify when those implicit transfers are happening (or force them to be explicit), to isolate them from kernel execution and be able to do an apples-to-apples performance comparisons with older explicit models like OpenCL. 

I think if you only go by the SYCL specification, it's not possible because an implementation would in principle be free to free device allocations after every kernel and perform a copy again for every kernel. Of course, every SYCL implementation that wants to deliver good performance will try to minimize data transfers in practice and won't do this. hipSYCL guarantees the following:
* Once an allocation is made on a device, it will not be released until the buffer is destroyed.
* Data will not be copied again if an up-to-date copy is already present on device.

This means that the copy will take place only for the first kernel that accesses a buffer (assuming the data is not modified afterwards in a kernel on a different device). 
For example, you can submit an empty dummy kernel to trigger the copy. Or, as I had mentioned, you just use the explicit `handler::copy()` functions.

> In theory, by skipping OpenCL/SPIR there is a chance for the backend code generator to use hardware intrinsics that aren't directly available through those models, so there's exciting room for exploration here.

In hipSYCL you can also use backend intrinsics (e.g. CUDA) directly yourself to create optimized code paths. That's was one of the main motivations to design hipSYCL the way it works :)

> I know the info::event_profiling API exists, but IMO the spec is unclear on whether command_start includes the implicit transfers necessary to initialize the accessors declared within the CG, including any possible transfers. In Sec. 4.8.2 of the 1.2.1 spec, it says "It is possible to obtain events for the start of the command group function object, the kernel starting, and the command group completing." However I'm unable to find anything the the Event Profiling, Command Group or Kernel specification that says how to get the middle one. 

the entire profiling API is not yet implemented in SYCL - priority was not super high on this because in hipSYCL you can always use vendor profilers such as the NVIDIA tools.

> Unless you perhaps use the new queue convenience functions for simplified kernel submission, but it's unclear how you define accessors for those to get data in/out since the device accessor must be defined within a CG.) 

They are not meant to be used with accessors. They cover the use case when you access your data using USM pointers. In this case, you will frequently submit empty command group scopes, and the queue shortcuts make these cases a bit shorter.

>  The blunt approach that comes to mind then would be just submitting separate CGs for the explicit in/out transfers to make sure data is where you want it, and kernel(s) and then getting the profiling info from each CG's event.

Use `handler::copy()`

>  (A side question we've been discussing internally is how to do explicit CUDA/OpenCL-like transfers a priori outside critical loops for profiling purposes, and "know" where the up-to-date copy of the data is.)

Use `handler::copy()` :)

> Thanks for the pointers. We've got some more complicated code that is going to use the copy method that I have to go back and fix for misusing accessors. On re-reading this section of the spec, it also looks like you can directly use a host pointer as src/dst, without having to construct a buffer from it and incurring an extra implicit copy in the associated device accessor.

Yes, you can work directly with a host pointer. 
However, if you construct an accessor from a buffer that was constructed from a host pointer (see `buffer` constructors) the SYCL implementation may also just operate on the pointer directly in some cases (so, the buffer takes control of this pointer) instead of copying it into the buffer - so you also only end up with a single copy from host to device (and later, potentially back again).

The first error is indeed a known issue that happens when you use a clang with debug assertions enabled. This is not supported.

The second error I haven't seen so far. Maybe the architecture that you have compiled for doesn't match what you want to run on, so it errors?

**Comment by psath** [comment]
*Really* appreciate the in-depth explanation of how the hipSYCL implementation handles buffer management. Those are the semantics we were expecting/hoping for so the guarantee is good to have.
 
> the entire profiling API is not yet implemented in SYCL - priority was not super high on this because in hipSYCL you can always use vendor profilers such as the NVIDIA tools.
> 

No worries, once we get there we'll look at rocprofiler then for the offline profiling. However, a component of what we're going to be doing in the long run is performance-proportional (re)scheduling across devices, so we will need some vendor-agnostic in situ approach and events make the most sense. We can make due with host wall timers and explicit queue flushes for immediate dev purposes.

> > The blunt approach that comes to mind then would be just submitting separate CGs for the explicit in/out transfers to make sure data is where you want it, and kernel(s) and then getting the profiling info from each CG's event.
> 
> Use `handler::copy()`

My plan was something like
```C
auto copyin_event = q.submit([&](cl::sycl::handler &cgh) {
  cgh.copy(...);
});
auto kern1_event = q.submit([&](cl::sycl::handler &cgh) {
  cgh.paralell_for<kern1>(...);
});
auto kern2_event = q.submit([&](cl::sycl::handler &cgh) {
  cgh.parallel_for<kern2>(...);
});
auto copyout_Event = q.submit([&](cl::sycl::handler &cgh) {
  cgh.copy(...);
});
```

> 
> The first error is indeed a known issue that happens when you use a clang with debug assertions enabled. This is not supported.

Yeah, I noticed it in #169 so turned them off for the Upstream Clang build. FWIW I popped it in the gdb and the assertion is failing in the second half. Both ABIs are `GenericItanium`, but the stub name and the function name disagree, `__hipsycl_Kernel_$vecAdd.stub` vs `__hipsycl_Kernel_$vecAdd`. As long as it's not breaking anything, I won't worry about silencing it then. :shrug:

> 
> The second error I haven't seen so far. Maybe the architecture that you have compiled for doesn't match what you want to run on, so it errors?

Yeah that one's throwing me for a loop. If I don't have any kernels I can see my OpenMP platform/device, and both my R9 Nano and Vega devices on a separate platform, and apparently copy data in and out of device contexts no problem. But as soon as I compile with a kernel, that turns up.

However, I don't believe its hipSYCL's fault, rather HIP's/my install's. I went and tried to sanity check with the HIP matrix transpose sample, and I get the same thing when I compile with either `--amdgpu-target=gfx803` or `gfx900`, which are the two cards I have. They both show up in `rocminfo`, I can run OpenCL codes on them, and `hipconfig` shows the appropriate defines in the `hip-clang-cxxflags`. I've played around with llvm-objdump and compiling with `-save-temps` trying to confirm the device implementation is getting generated, but I must admit I'm a bit out of my depth at that level. 😕

**Comment by psath** [comment]
> > The second error I haven't seen so far. Maybe the architecture that you have compiled for doesn't match what you want to run on, so it errors?
> 
> Yeah that one's throwing me for a loop. If I don't have any kernels I can see my OpenMP platform/device, and both my R9 Nano and Vega devices on a separate platform, and apparently copy data in and out of device contexts no problem. But as soon as I compile with a kernel, that turns up.
> 
> However, I don't believe its hipSYCL's fault, rather HIP's/my install's. I went and tried to sanity check with the HIP matrix transpose sample, and I get the same thing when I compile with either `--amdgpu-target=gfx803` or `gfx900`, which are the two cards I have. They both show up in `rocminfo`, I can run OpenCL codes on them, and `hipconfig` shows the appropriate defines in the `hip-clang-cxxflags`. I've played around with llvm-objdump and compiling with `-save-temps` trying to confirm the device implementation is getting generated, but I must admit I'm a bit out of my depth at that level. 😕

HIP's `extractkernel` gave me the insight I needed to figure out the problem with the HIP code.. *The HIP runtime needs code for **all** GPU architectures in your machine to run **at all**. It can't just run on the subset for which code is available.* I had to change the build to `--amdgpu-target=gfx803,gfx900` and then the matrix transpose sample worked!

While you can't use a combined `--hipsycl-gpu-arch=gfx803,gfx900` like HIP, providing multiple `--hipsycl-gpu-arch=gfx803 --hipsycl-gpu-arch=gfx900` resolves that issue in the hipSYCL-generated code as well!

**Comment by illuhad** [comment]
I see, thanks for the feedback! hipSYCL introduces a nice way to specify multiple targets in PR #337 :)

**Comment by psath** [comment]
Brief correction, multiple `--hipsycl-gpu-arch` flags *do not* get passed through currently, only the first does. But using `--hipsycl-dryrun` to get the raw command and adding an extra `--cuda-gpu-arch` flag is what ends up working. (I extracted kernels from a stale binary in the original reply)

Since you already support this functionality via #337, there's no need to update the old functionality to do the passthrough.

**Comment by illuhad** [comment]
What should work without #337 is to exploit the fact that `syclcc` will just forward any non-hipSYCL-specific flags to clang. So you can just `syclcc --hipsycl-gpu-arch=gfx803 --cuda-gpu-arch=gfx900 ...` (yes, the clang flag really called `--cuda-gpu-arch` even for AMD GPUs...)
