### ISSUE TITLE
Kernel name with variadic parameter pack is not accepted

### ISSUE THREAD

**Issue by bmanga** [AdaptiveCpp/AdaptiveCpp#375]
I am getting the following error: `Not a valid kernel name: 'AnonKern<'.', '.', '<'>'`, but I am not sure what the requirements on the type are.
It seems like some class template instantiations are allowed, while others aren't.

Thanks :)

**Comment by illuhad** [comment]
How is `AnonKern` defined? Something like `template<char, char, char> class AnonKern;`? It might be that it doesn't like non-type template arguments, but I have actually never tried that...
hipSYCL (on `develop` branch when using clang >= 10) supports SYCL 2020 optional kernel naming, so you can just leave out the kernel name altogether :-)

**Comment by bmanga** [comment]
It's defined as follows:
`
template <char... N>
class AnonKern {
};
`
It seems like hipsycl doesn't like parameter packs, as using 3 chars works.

**Comment by illuhad** [comment]
Okay, thank you. Instinctively I would say that this *should* probably be allowed and I can't remember anything from the top of my head in the spec that would forbid this. Is it critical for you that this is fixed? 
In light of SYCL 2020, I would encourage people to move away from kernel names, except maybe for debugging purposes or specialized embedded platforms where the host compiler is not the same as the device compiler.

**Comment by bmanga** [comment]
Yeah it would be pretty useful for me. I can try and fix it if you are open to a PR :).

Is there a specific way to enable SYCL2020? I have tried just omitting the kernel name but that failed also.

**Comment by illuhad** [comment]
> Yeah it would be pretty useful for me. I can try and fix it if you are open to a PR :).

Great :)

> Is there a specific way to enable SYCL2020? I have tried just omitting the kernel name but that failed also.

No, it is automatically active if your hipSYCL version is recent enough and you have built it against clang >= 10. In that case, you can just e.g. `parallel_for(range<1>{...}, ...)` without the kernel name.

**Comment by bmanga** [comment]
Yes it is recent, but it fails with linker errors if I omit the kernel name. I suspect it's because the generated name is too long.

**Comment by illuhad** [comment]
Another thing to try might be a function object instead of lambda. If the mangled lambda name exceeds some internal limits of the clang CUDA/HIP toolchains, you might be able to shorten it somewhat by declaring your kernel as a globally visible function object. (Globally visible function objects also never needed to be named, even before SYCL 2020)

But if your mangled kernel name really is so long that clang's CUDA/HIP toolchains say goodbye, I wonder what the implications are regarding portability to other toolchains or SYCL implementations.

**Comment by bmanga** [comment]
Yeah I manage to shorten the name using some template magic, but I need the support for variadic templates.

I will report back when I have a working solution :)

**Comment by keryell** [comment]
I have the feeling that the spec does not disallows such parameter packs.

**Comment by bd4** [comment]
@illuhad re moving away from specifying names, I think unless the auto-generated names are easy to track down, it will make debugging and profiling very difficult. For gtensor, we don't use variadic templates but we do make use of templated kernel names: https://github.com/wdmapp/gtensor/blob/master/include/gtensor/assign.h#L349. Even these names are horrible though - it's another form of automatic naming really, because an application will have a bunch of different assign kernels with various complex templates. We are thinking to add the option for a user specified name that occurs as the first template sub-type.

**Comment by bmanga** [comment]
@illuhad should be fixed with #377

**Comment by illuhad** [comment]
@bd4 Well, in hipSYCL the auto-generated names are just regular C++ mangled symbol names. So, there is no difference between a kernel and a regular C++ symbol as far as naming goes. As such, you can get the generated kernel name with `typeid`. I think from the perspective of integration with C++, which is one of the prime goals of SYCL, this is the way to go.

If you want to influence naming, it is always a good idea to use function objects instead of lambdas for your kernels since those will have a more easily readable name and don't need to carry such an elaborate declaration scope around with them in the mangled symbol name.

But yeah, debugging purposes is one of the reasons why explicit kernel naming is still available in SYCL 2020 instead of removing it altogether.
