### ISSUE TITLE
Device name doesn't make sense

### ISSUE THREAD

**Issue by mrzv** [AdaptiveCpp/AdaptiveCpp#411]
Running `tests/platform_api/api_test.cpp` on the GPU produces device name that doesn't make sense.

```
hipSYCL/stage/bin/syclcc-clang --hipsycl-targets=cuda:sm_72 -O3 -MMD -MP api_test.cpp -o api_test-cuda
./api_test-cuda 
Found device hipSYCL OpenMP host device
Created queue on GPU: true
```

```
hipSYCL/stage/bin/syclcc-clang --hipsycl-targets=omp -O3 -MMD -MP api_test.cpp -o api_test-cpu
./api_test-cpu 
Found device hipSYCL OpenMP host device
Created queue on GPU: false
```

The second "found device" makes sense, but for the first one (`api_test-cuda`), I would have expected a description that mentions NVIDIA, not OpenMP host device.

**Comment by illuhad** [comment]
That may look confusing, but I've just had a look and it seems to me everything works correctly. The code in question:
```
#include <iostream>
#include <CL/sycl.hpp>

int main()
{
  cl::sycl::platform platform;
  auto devs = platform.get_devices();

  for(const auto& d : devs)
    std::cout << "Found device "
              << d.get_info<cl::sycl::info::device::name>()
              << std::endl;

  cl::sycl::queue q;
  std::cout << "Created queue on GPU: " << ((q.is_host() == false) ? "true" : "false")
                                        << std::endl;
}
```
was written back in a time when hipSYCL was hardcoded to only expose a single platform (the one you compile for). This is no longer the case: The runtime now supports having multiple backends active simultaneously. In particular, support for the CPU/host backend is always enabled even if you don't compile your kernels for CPU (the SYCL specification actually requires this, but hipSYCL has previously not honored this).

What is happening here is that the default constructed platform as used here just defaults to the CPU backend. What you would actually need to do is iterate over all available platforms to discover all available devices. This is why it doesn't print the NVIDIA GPU.

Now, as you may have noted, it says that it is running on GPU nevertheless. This is because the default device selector (as used by the default-constructed queue) prefers GPUs if you have compiled kernels for GPU, so in the first example it would select your GPU.
If you extract the device that is associated with this queue using `q.get_device()` and print its name, you should see the NVIDIA GPU.

**Comment by mrzv** [comment]
Ah. Thanks for the explanation. It makes sense.

It would be great to have an example somewhere with the proper runtime use of the device selector. So I guess this is a feature request, not a bug.

**Comment by illuhad** [comment]
Maybe this section of code from a Multi-GPU benchmark from the Parallel Research Kernels is helpful:
https://github.com/ParRes/Kernels/blob/23ea508c7a94e6a203e21d7375d7ddbbf88a0634/Cxx11/nstream-multigpu-dpcpp.cc#L110

**Comment by illuhad** [comment]
This might also be interesting for you: https://github.com/illuhad/syclinfo

**Comment by mrzv** [comment]
`syclinfo` is perfect. Exactly what I was looking for.

It's reporting both GPU and CPU on my machine, even though I compile it just for a single `--hipsycl-targets`, which throws me off a little, but I guess this will become irrelevant to me once both targets are compiled into a single executable.

Thanks again.

**Comment by illuhad** [comment]
> It's reporting both GPU and CPU on my machine, even though I compile it just for a single --hipsycl-targets, which throws me off a little, but I guess this will become irrelevant to me once both targets are compiled into a single executable.

I think compilation targets and device discovery are two very different things.

If you query the available platforms and devices, you are asking the SYCL implementation which devices it can see. But this is not the same as asking for devices for which kernels have been compiled. There may be additional devices in the system for which you have not compiled, and you may have compiled for devices that are not present in the system.

But of course it can also be interesting to query for which devices kernels have been compiled. SYCL 2020 introduces a quite elaborate mechanism that can, among other things do that (hipSYCL will only be able to partially support it). In the meantime, hipSYCL has a `sycl::device` member function `bool device::hipSYCL_has_compiled_kernels()` that can tell you if kernels have been compiled for this backend and are expected to be able to execute successfully on that device.

Note that even if you don't explicitly specify `omp` as target, a CPU version of the kernels will always be compiled (but without multithreading if you don't target `omp`). This is required to implement the host fallback device as required by the SYCL spec.

**Comment by mrzv** [comment]
That's great. Thanks for the explanation. `hipSYCL_has_compiled_kernels` is what I need.
