### ISSUE TITLE
Consider adding option to bail on error

### ISSUE THREAD

**Issue by psalz** [AdaptiveCpp/AdaptiveCpp#456]
In my usage of hipSYCL I'm seldomly `wait()`-ing on tasks to finish, and instead repeatedly query the `command_execution_status` on an event to see if a particular command has finished. This currently presents a problem whenever something unexpected happens, such as an out-of-bounds memory access within a CUDA kernel, which will manifest as CUDA error 700 on the host. I then basically get pages upon pages of this:

![image](https://user-images.githubusercontent.com/791348/106719669-df76ba80-6602-11eb-9a24-efc413edbdc8.png)

I've worked around this by adding a `std::terminate` in the error handler, but that got me thinking that maybe a canonical solution should exist for this problem. For example, an environment variable such as `HIPSYCL_BAIL_ON_ERROR` or `HIPSYCL_EXIT_ON_ERROR`.

**Comment by illuhad** [comment]
The default asynchronous error handler already terminates in accordance with SYCL 2020:
https://github.com/illuhad/hipSYCL/blob/0217b30a90b7c5889712bf7790b6be692c7f5bc4/include/hipSYCL/glue/error.hpp#L82

By not calling `queue::wait_and_throw()` or `event::wait_and_throw()`, or `queue::throw_asynchronous()` you are asserting that you do *not* want that behavior imho. I'm not sure adding another user-facing mechanism for error handling is the right approach.

I think the main issue here is that hipSYCL does not yet clear the CUDA error state. Because of this, a single error usually means that all subsequent operations fail as well, even if they are unrelated.

**Comment by psalz** [comment]
> `queue::throw_asynchronous()`

Huh, TIL. Using `wait_and_throw` is not an option, but periodically calling `throw_asynchronous` might be. This just has to be a cheap operation then. I checked and it looks like hipSYCL is always creating two `std::vector`s and locking a mutex in `async_error_list::pop_each_error`. Both should be reasonably cheap I think (if the mutex is contended I will abort anyway), but I will look into this some more. Thanks for the time being and sorry for the noise!
