### ISSUE TITLE
Status of predictive scheduler

### ISSUE THREAD

**Issue by isZumpo** [AdaptiveCpp/AdaptiveCpp#463]
We are looking to implement something similar to what was done in the previous predictive scheduler, the one that was removed with pull request #443. We were wondering what led to this scheduler being removed? The pull request also mentioned that it will be replaced with a new approach in the future, has any work been done on this so far?

What we are looking to do is to implement some form of hybrid scheduler as a part of a master thesis project. A scheduler that has the ability to decide which device each node should be assigned to during runtime, among other things. It would be a great insight to know what problems occurred with the one being removed.

**Comment by illuhad** [comment]
It was removed because it was never fully functional. This is challenging from a software engineering point of view, because SYCL already requires a lot of decisions from the runtime. The old design effectively attempted to predict how the layers underneath (e.g. decisions done by hipSYCL runtime backends) would behave, which doesn't scale and led to unsustainable complexity. The future is a self-observing design in conjunction with rewinding runtime state.
