### ISSUE TITLE
CPU SIMD parallelization?

### ISSUE THREAD

**Issue by eschnett** [AdaptiveCpp/AdaptiveCpp#468]
How does hipSYCL address CPU SIMD parallelization? In CUDA, this would be the equivalent of a warp, where thread divergence is an issue. Is there a way to get hipSYCL generate respective CPU code that converts "inner threads" to SIMD instructions, using masked load/stores etc. to handle inactive vector lanes (i.e. the equivalent of thread divergence)?

**Comment by illuhad** [comment]
The OpenMP backend uses `#pragma omp simd` for intra-work group parallelism in the scoped and hierarchical parallel for execution models. This is not possible for `nd_range` parallel for (which is not performance portable). Basic parallel for is mapped to `omp parallel for collapse()` clauses, which might be vectorized.
Since the CPU backend is a pure-library implementation, vectorization is mostly handled by the host OpenMP compiler and hipSYCL has no control over it.
