### ISSUE TITLE
Packed half precision support

### ISSUE THREAD

**Issue by ekondis** [AdaptiveCpp/AdaptiveCpp#475]
I'm intending to utilize packed half precision computations on architectures that support it (e.g. Vega GPU).

It seems that `sycl::half2` data type is missing. Of course it can be aliased to `sycl::vec<sycl::detail::hp_float, 2>` but then it seems that the multiply-add operations are not applied as packed but as scalar instead. I would expect `sycl::fma(...)` to map to `__hfma2(...)` function calls under HIP/CUDA. But that looks like it is not the case, is it?

**Comment by illuhad** [comment]
Half support is not yet really implemented. `sycl::detail::hp_float` is more of a placeholder that does not map to a proper fp16 type. In order to implement half support we need to add some C++ library for half support as additional dependency for the host compilation path.

EDIT: Of course you can exploit hipSYCL CUDA/HIP interop functionality and insert those intrinsics manually as a target specific optimization. Here's an example, although you might also want to `#ifdef` the `__host__ __device__` to support the case when compiling for CPU exclusively: https://github.com/illuhad/hipSYCL/blob/develop/doc/hip-source-interop.md

**Comment by ekondis** [comment]
Thank you, this is clear.

This workaround is sufficient till support for half precision is added.
