### ISSUE TITLE
The mechanism of hipsycl compiled from source code to ISA

### ISSUE THREAD

**Issue by malixian** [AdaptiveCpp/AdaptiveCpp#477]
I found a picture about compilation model of hipsycl in [this](https://twitter.com/illuhad/status/1127662349303918593), but I can't figure out the detail  mechanism.
I guess the compilation model is that sycl source code is transformed to LLVM IR by clang front and then transform IR to AMD GCN or Nvidia PTX with LLVM backend code generation.
Is my guess correct?

**Comment by illuhad** [comment]
That picture is outdated in some aspects and was hence removed from `doc/` a couple of weeks ago.

hipSYCL focuses on integrating various existing toolchains such as CUDA or HIP under a single interface (SYCL). If we focus on device compilation for a moment, what happens is that it loads a clang plugin into the CUDA/HIP clang frontends which teaches them to understand SYCL code.
After this, what happens is basically the same as when compiling code with `clang -x cuda` or `clang -x hip` - you can find more information in the LLVM documentation.
Because the clang CUDA and HIP frontends are incompatible and cannot be used at the same time, hipSYCL invokes separate device passes for them with those different clang drivers, so different LLVM IR comes out which is then translated by clang CUDA/HIP drivers to amdgcn/NVPTX.
In the end the resulting device binaries are bundled into the host binary with a hipSYCL-custom mechanism.

See also [here](https://github.com/illuhad/hipSYCL/blob/develop/doc/compilation.md) for more information.

**Comment by malixian** [comment]
Thanks @illuhad , you help me a lot.

**Comment by malixian** [comment]
And I want to summarize your answer @illuhad. Hipsycl does not use source to source (e.g. sycl to HIp) and this method need nvcc and hipcc.  But Hipsycl uses llvm to generate the IR through the clang plugin and the IR is consumed by target backend and this method don't need nvcc or hipcc compiler. Is my understanding correct?

**Comment by illuhad** [comment]
Yes, this is correct.

Very early versions of hipSYCL used source-to-source transformation, but this is no longer the case anymore (that was a long time ago).

**Comment by keryell** [comment]
@malixian If you are looking for a source-to-source implementation, there is neoSYCL https://dl.acm.org/doi/fullHtml/10.1145/3432261.3432268
