### ISSUE TITLE
Can we add a new backend with the help of hipsycl

### ISSUE THREAD

**Issue by malixian** [AdaptiveCpp/AdaptiveCpp#481]
We have a new backend for NPU(neural network unit) and it has the corresponding toolchain which is similar to cuda and hip. 
We wish using SYCL frontend to support our backend with the help of hipsycl. Is this possible？
My idea is to call the toolchain of the new device after the device IR is generated. There are maybe two parts to be developed: **Part1**. Generate the IR of the new device with the help of the SYCLfrontend; **Part2**. Adapt the runtime of the new device to the SYCL runtime.  
But in the Part1 of generating IR, I did not find any part in the hipSYCL source code that can specify the clang triple-target. I hope to generate the expected device IR by specifying the triple-target. Can you provide me with some help, thank you very much.

**Comment by illuhad** [comment]
So you want to create a new hipSYCL backend? That's great! Please provide some more information about the target hardware, toolchain and runtime API. 

Do you want to upstream your new new backend? In order for your work to be considered for merging, I think it at least documentation about it has to be publicly available, and you would have to be willing to maintain your hipSYCL backend in the long term.

hipSYCL doesn't directly use target triplet because it doesn't need them as it is even more general. hipSYCL can invoke arbitrary  commands for compilation. What you need to do is find any clang command (with or without target triplets) that can take C++ code, extract kernels and produce whatever IR/binary your backend wants. Please look at the internals of `syclcc` for more details.
For this you can either reuse the existing hipSYCL clang plugin for the CUDA/HIP backends, use the clang SYCL frontend or build something yourself.
hipSYCL does not have a unified SYCL frontend for all backends (and does not need one).

Since hipSYCL can interface with arbitrary backend runtimes, you probably wouldn't have to change your runtime.

**Comment by malixian** [comment]
This work is still in its infancy, and I am planning to consider using hipSYCL as our foundation.  You said don't use target-triple to distinguish the device toolchains, so does hipSYCL just call different device toolchains by setting environment variables in syclcc? The details of the syclcc code look like this.

**Comment by illuhad** [comment]
The user can either set environment variables or command line arguments to specify targets, e.g. `syclcc --hipsycl-targets="omp;cuda:sm_60;hip:gfx906"` compiles for CPU, nvptx for `sm_60` and `gfx906` amdgcn. Internally, `syclcc` expands this specification into multiple clang invocations, e.g. `clang -x cuda --cuda-gpu-arch=sm_60` for the CUDA GPU. The clang CUDA driver then controls the exact target triplet to compile for, so `syclcc` does not need to care.
Of course you can change the clang command that `syclcc` invokes if you need it to do something else.

**Comment by malixian** [comment]
> The user can either set environment variables or command line arguments to specify targets, e.g. `syclcc --hipsycl-targets="omp;cuda:sm_60;hip:gfx906"` compiles for CPU, nvptx for `sm_60` and `gfx906` amdgcn. Internally, `syclcc` expands this specification into multiple clang invocations, e.g. `clang -x cuda --cuda-gpu-arch=sm_60` for the CUDA GPU. The clang CUDA driver then controls the exact target triplet to compile for, so `syclcc` does not need to care.
> Of course you can change the clang command that `syclcc` invokes if you need it to do something else.

The description is very detailed,  thanks.
