### ISSUE TITLE
Backends used by hipSYCL compiled program

### ISSUE THREAD

**Issue by FilipVaverka** [AdaptiveCpp/AdaptiveCpp#483]
Does hipSYCL initialize or otherwise make use of backends outside of ones specified during binary compilation?
For example, if I compile binary with "syclcc --hipsycl-targets=cuda:sm_75" the resulting binary seems to also access HIP/ROCm, unless its associated devices are hidden using HIP_VISIBLE_DEVICES={some_non_existent_id}. In my case this causes immediate crash due to issues with ROCm on Ryzen 7 4800H APU.

**Comment by illuhad** [comment]
You need to distinguish between
1. Compiling and embedding kernels for a particular backend/device
2. Runtime support to talk to the particular backend.

Both are completely unrelated. For example, there could be a case where you don't want to compile your SYCL kernels for HIP, but just want to use some external HIP/ROCm library (e.g. rocBLAS) with hipSYCL's HIP interoperability mechanics. In this case you would need runtime support, but no compilation for HIP would take place.
The other direction is of course also possible, i.e. you compile for a lot of different targets, some of which are unavailable in the target machine.

What happens is that when the hipSYCL runtime is loaded, it loads and initializes all its backends. The backends will then query which devices are available and prepare them for execution of SYCL work. On HIP, this includes querying device properties and constructing a pool of `hipStream_t` objects.

If the setup of one of the backends is broken, you can
1. Just disable this particular backend when building hipSYCL, e.g. `cmake -DWITH_ROCM_BACKEND=OFF`.
2. Remove runtime support for a backend after the hipSYCL installation. Because the hipSYCL runtime loads backends dynamically by loading separate backend plugin libraries, you can also just remove the runtime's backend plugin for HIP from `$HIPSYCL_INSTALL_PREFIX/lib/hipSYCL/`.

There are various use cases however where I can see something like a `HIPSYCL_BACKENDS=` environment variable (e.g. debugging, testing) being useful to filter the runtime backends that will be loaded. This might be a good additional feature for the future.

**Comment by illuhad** [comment]
Closing as I assume this was solved.
