### ISSUE TITLE
State of runtime - CPU + GPU coprocessing?

### ISSUE THREAD

**Issue by jon-chuang** [AdaptiveCpp/AdaptiveCpp#515]
Just a simple qn as there was talk in the past of intermingling backends and letting the runtime handle the scheduling. Also multi device Systems. Asking as a reference for a similar potential project in rust.

**Comment by illuhad** [comment]
CPU+GPU and multi GPU is all supported. As is targeting multiple backends simultaneously, and e.g. running on AMD and NVIDIA GPU simultaneously.

The only limitation I am aware of is that "triangle copies" are not yet supported: When a copy between different device backends is required, e.g. between AMD and NVIDIA GPU, it is in general not possible to peform the data copy directly (CUDA does not know how to talk to AMD GPUs, and ROCm does not know how to talk to NVIDIA GPUs).
Instead, data has to be copied first to CPU and then with a second copy to the other device. Currently this requires the user manually triggering a copy back to host as a workaround.

Additionally, automatic concurrency of kernels using multiple streams on one device is supported since #512, but still very new. Automatic work distribution across multiple devices is not yet supported (but area of research and beyond the scope of a regular SYCL implementation anyway).

**Comment by jon-chuang** [comment]
Thanks @illuhad , could I ask if there is a high level overview of how the scheduler balances the load between the various devices? Is it primarily a data-oriented scheduling e.g. work-stealing? If so, how does it handle/reason about data copy latencies (10s of us I believe for GPU for non-pinned memory, which is still faster than SSD R/W latency at least)? 

Also, as a question for myself, what are the minimal latencies offered by upcoming or cutting edge commercial tech? (As in, what are the limitations to achieving latencies similar to RAM data movement?).

Is there any inspiration from Dask or similar?

**Comment by illuhad** [comment]
>  could I ask if there is a high level overview of how the scheduler balances the load between the various devices? Is it primarily a data-oriented scheduling e.g. work-stealing?

The SYCL specification requires that users explicitly specify on which device to execute operations. Therefore, load balancing between multiple devices is not of primary concern for a regular SYCL implementation. (Classical) work stealing is usually not employed so much in the heterogeneous world because of latencies and the extremely high cost of potential data transfers when moving computation to a different device.

> Is there any inspiration from Dask or similar?

Not so much dask, but there are other heterogeneous task-graph schedulers for heterogeneous HPC such as StarPU.
