### ISSUE TITLE
[Doubt] Vulkan backend

### ISSUE THREAD

**Issue by jjcasmar** [AdaptiveCpp/AdaptiveCpp#516]
Are there any plans to provide a Vulkan backend for hipSYCL?
That would allow to run hipSYCL on a great amount of hardware (basically everything which supports Vulkan) and also in MacOS, thanks to MoltenVK.

**Comment by illuhad** [comment]
SYCL on top of Vulkan is not as straight-forward as people seem to think. Vulkan does not allow the kernel execution model, so it speaks a different variant of SPIR-V compared to OpenCL that has certain restrictions. It is probably not possible to implement all of SYCL on top of Vulkan.

See e.g. https://github.com/google/clspv/blob/master/docs/OpenCLCOnVulkan.md#opencl-c-restrictions
for restrictions w.r.t mapping OpenCL to Vulkan.

There are no active efforts to port hipSYCL to Vulkan.

This is an area of research, see e.g. the talk on "Sylkan" here: https://www.iwocl.org/iwocl-2021/conference-program/

EDIT: hipSYCL already has sollid support for AMD and NVIDIA GPUs, and experimental support for Intel GPUs. Hardware coverage would not increase much by adding a Vulkan backend (except maybe some embedded GPUs?). AMD has announced that they will support RDNA in ROCm this year, so hipSYCL AMD hardware coverage is expected to grow on its own.
I don't see hipSYCL getting official Mac support anytime soon in any case since none of the developers even has a Mac development system.

**Comment by jjcasmar** [comment]
Thanks for the points. I thought that with Vulkan support you could easily do any compute stuff, but looks like its not possible. Well, that is how it is. More than hardware support, a Vulkan port would have allowed more OS. 

Regarding your edit, I have a RX 5700XT and hipSYCL works fine. At least for the tests I have done. Apparently ROCm is supported although unoficially (and maybe incomplete?). Ill try to submit some results in case you want to publish unoficial support.

**Comment by illuhad** [comment]
> Thanks for the points. I thought that with Vulkan support you could easily do any compute stuff, but looks like its not possible. 

At least it's not something that is straight-forward and can just be done. Maybe it will get better in the future as Vulkan progresses.

> Regarding your edit, I have a RX 5700XT and hipSYCL works fine. At least for the tests I have done. Apparently ROCm is supported although unoficially (and maybe incomplete?). Ill try to submit some results in case you want to publish unoficial support.

I know that for some people it works. I also have an AMD 4750u APU that is not officially supported, but most of ROCm (and hipSYCL) happens to work. Unfortunately, there seem to be also people for whom it doesn't work. I'm not sure we can announce hipSYCL support for hardware not officially supported in ROCm because if things don't work because of ROCm issues, there is little we can do to fix them on the hipSYCL side.
