### ISSUE TITLE
How to launch kernel in rocm runtime

### ISSUE THREAD

**Issue by malixian** [AdaptiveCpp/AdaptiveCpp#533]
I found that `submit_kernel_from_module` calling `cuModuleGetFunction` and `cuLaunchKernel` driver API to launch kernel. But in hip_runime/queue.cpp, it seems that only the function  `submit_kernel` can submit the kernel. And I can't find any rocm runtime API being called, like `hipModuleGetFunction`.  That makes me a little confused. Can you tell me whether hipsycl calls a function similar to `hipLoadModule` , `hipModuleGetFunction` ?

**Comment by illuhad** [comment]
hipSYCL supports two modes of compilation: explicit multipass and integrated multipass.
https://github.com/illuhad/hipSYCL/blob/develop/doc/compilation.md

`submit_kernel_from_module` and `cuLaunchKernel` are only used in explicit multipass (which is not the default). The HIP backend does not support explicit multipass because it's not really necessary for now. In integrated multipass something like this happens (simplified):

```c++

template<class F>
__sycl_kernel void invoker(F f){ f(); }

template<class F>
void submit_kernel(F f){
  __hipPushCallConfiguration(grid, blocks);
  invoker(f);
}

```
Our clang plugin replaces `__sycl_kernel` with CUDA/HIP `__global__` attribute during compilation. The combination of `__hipPushCallConfiguration()` and call to a `__global__` function causes clang to emit the exact same kernel invocation code as when calling `invoker<<<grid, blocks>>>(f)`.
In integrated multipass mode we don't need HIP runtime calls to launch kernels because the clang HIP/CUDA toolchains generates these calls for us.

Explicit multipass using `hipLoadModule` or `hipModuleGetFunction` could be also implemented for HIP in analogy to the CUDA implementation, but it's not really necessary. The main use case for explicit multipass is if you want to compile for *both* CUDA and HIP. But even in this case we can still have one backend run in integrated multipass mode as long as all other backends run in explicit multipass.
