### ISSUE TITLE
Confusion regarding the repositories

### ISSUE THREAD

**Issue by invexed** [AdaptiveCpp/AdaptiveCpp#586]
Hi everyone.

I'm in the process of updating my hipSYCL Dockerfiles (based on ```archlinux```) for the first time in a while and I'm a little confused about how the repositories are structured now.

The packages listed [here](https://github.com/illuhad/hipSYCL/blob/develop/doc/installing.md#repositories) make sense. I only need the ```OpenMP``` and ```CUDA``` backends so I (successfully) installed the ```hipSYCL-nightly``` and ```hipSYCL-base-nightly``` packages. What is confusing me are the packages listed [here](https://github.com/illuhad/hipSYCL/blob/develop/install/scripts/README.md#installing-from-repositories). I tried installing ```hipSYCL-omp-cuda-nightly``` instead of ```hipSYCL-nightly``` but that didn't work.

Also - given the name of that package - does that mean it is no longer necessary to run the ```install/scripts/install-cuda.sh``` script separately?

Thanks a lot.

P.S. I noticed the nightly Arch packages are not being updated as frequently as the Ubuntu/CentOS ones. Is that intentional? I just wanted to mention it in case there is a problem somewhere.

**Comment by illuhad** [comment]
Starting with hipSYCL 0.9.1, we have moved to a plugin system where the various hipSYCL backends are provided by plugin libraries that are detected and loaded at runtime. Previously, the supported backends had to be selected at compile time which is why we ended up with combinations like `omp-cuda` etc.

This means you can now install both `hipSYCL-omp-nightly` (which installs the basic hipSYCL stack + OpenMP backend) and `hipSYCL-cuda-nightly` which adds CUDA support to the hipSYCL installation by adding the CUDA plugin.

`hipSYCL-nightly` afaik is a meta-package that installs support for everything. `hipSYCL-omp-cuda-nightly` is a meta-package that is there for backwards compatibility reasons.

(ping @sbalint98 to verify what I say ;) )

You will still need to run `install-cuda.sh` as our packages only install the hipSYCL CUDA backend, not the actual CUDA toolkit which is also needed.

> P.S. I noticed the nightly Arch packages are not being updated as frequently as the Ubuntu/CentOS ones. Is that intentional? I just wanted to mention it in case there is a problem somewhere.

Thanks for the info. @sbalint98 can you check?

**Comment by sbalint98** [comment]
Hi @invexed, 

Thank you for posting, currently, we have some trouble rolling out new archlinux packages due to the new gcc version on arch that conflicts with building ~~llvm10~~ llvm11. ~~see here: https://github.com/spack/spack/pull/24281~~ . And unfortunately In order to support explicit multipass we need to stick to ~~llvm10.1.0~~ llvm11

I am sorry for the confusion with regard to the documentation. I'll have to look into that. the current state is described by your second link eg: https://github.com/illuhad/hipSYCL/blob/develop/install/scripts/README.md#installing-from-repositories . 

> I tried installing hipSYCL-omp-cuda-nightly instead of hipSYCL-nightly but that didn't work.

Mhmm that shouldn't be the case `hipSYCL-nightly` should only be a meta-package for `hipSYCL-omp-cuda-nightly`, can you check the actual name of the installed package? 

> Also - given the name of that package - does that mean it is no longer necessary to run the install/scripts/install-cuda.sh script separately?

No, unfortunately, we cannot distribute the Cuda toolkit in our packages for legal reasons therefore you will still have to run that script. 

By the way, in case you are familiar with singularity containers, and they are a good match for use case, they might be the easiest way to get you started using hipSYCL. you can get them from here: http://repo.urz.uni-heidelberg.de/sycl/singularity/ . (you still need to run the cuda-install script case for a Cuda container though...)

EDIT:
the proper spack issue : https://github.com/spack/spack/issues/24435

**Comment by invexed** [comment]
Thank you both for your replies, that clears a lot of it up.

@sbalint98 

> Thank you for posting, currently, we have some trouble rolling out new archlinux packages due to the new gcc version on arch that conflicts with building llvm11. And unfortunately In order to support explicit multipass we need to stick to llvm11

No worries. Forgive me for pointing out the obvious, but might upgrading to LLVM 12 do the trick? Or is there a blocker elsewhere?


> Mhmm that shouldn't be the case hipSYCL-nightly should only be a meta-package for hipSYCL-omp-cuda-nightly, can you check the actual name of the installed package?

I had this in my Dockerfile
```
RUN pacman -S --noconfirm hipSYCL-base-nightly hipSYCL-omp-cuda-nightly
```
which gave: ```error: target not found: hipSYCL-omp-cuda-nightly```

From what @illuhad said above, it sounds like installing ```hipSYCL-omp-nightly``` and ```hipSYCL-cuda-nightly``` (in addition to ```hipSYCL-base-nightly```) is the way to go to enable support for the OpenMP and CUDA backends only?

**Comment by illuhad** [comment]
>  No worries. Forgive me for pointing out the obvious, but might upgrading to LLVM 12 do the trick? Or is there a blocker elsewhere?

LLVM 12 currently cannot support all of hipSYCL's functionality. Namely, it cannot support the explicit multipass compilation flow. Explicit multipass is explained a bit more in depth here: https://github.com/illuhad/hipSYCL/blob/develop/doc/compilation.md
Basically, it is what allows you to target CUDA and HIP simultaneously if you want to run on devices from different vendors with a single binary. If you are only interested in a single device backend at a time (e.g. CUDA in your case), explicit multipass is not relevant for you.

The background here is that for something like explicit multipass, you need a mechanism that can generate consistent names for lambdas in all compilation passes, so that the host can find and invoke the right compiled kernel in a compiled device image. C++ does not define a mangling for lambdas, so this requires dedicated compiler support.

clang 11 has introduced `__builtin_unique_stable_name()` exactly for this purpose, which was an upstreamed component of Intel's DPC++. We use this functionality for explicit multipass in hipSYCL.

Unfortunately, `__builtin_unique_stable_name()` was reverted again in clang 12 because of disagreements between the Intel contributors and the clang maintainers about the correct process for merging and upstreaming. As a consequence, we cannot support explicit multipass with clang 12.

It looks like clang 13 has again support for this functionality to some extent, although it's not "as nice" as the previous `__builtin_unique_stable_name()`. We will therefore probably directly jump to clang 13 at some point and skip clang 12.

With that said, clang 12 *is* supported for everything but explicit multipass. If you don't need this functionality, you can just compile hipSYCL against clang 12 and it will work.

> From what @illuhad said above, it sounds like installing hipSYCL-omp-nightly and hipSYCL-cuda-nightly (in addition to hipSYCL-base-nightly) is the way to go to enable support for the OpenMP and CUDA backends only?

IMO yes, but @sbalint98 is the expert here :)

**Comment by invexed** [comment]
Thanks again for another comprehensive reply. It's a shame ```__builtin_unique_stable_name()``` had to go but I look forward to targeting multiple backends simultaneously. Excellent work!

**Comment by invexed** [comment]
I've just noticed that there is also a ```hipSYCL-core-nightly``` package. May I ask what that is for?

**Comment by illuhad** [comment]
The core package contains core hipSYCL without any backend plugins. Since hipSYCL is not usable without backends, this package also pulls in `hipSYCL-omp-nightly` as dependency to add the OpenMP backend.

On the other hand, `hipSYCL-omp-nightly` also pulls in `hipSYCL-core-nightly` to provide the core hipSYCL installation. I would consider the core package an implementation detail; just install the packages for the backends you want and the rest should be installed automatically as dependency.
