### ISSUE TITLE
hipSYCL is treating C sources as C++

### ISSUE THREAD

**Issue by Michoumichmich** [AdaptiveCpp/AdaptiveCpp#597]
Hello, 
I am working on a SYCL backend for a C/CUDA/OpenMP library. Turns out that some targets where SYCL is needed are also using C libraries, but when using hipSYCL's `add_sycl_to_target`, the C files are getting compiled as C++ ones (by syclcc) which does not work. 

I tried using CMAKE_CXX_COMPILER_LAUNCHER instead of RULE_LAUNCH_COMPILE, in the cmake, but when targeting openMP the executable do not work. I'm not really sure of to fix that. Maybe, in `syclcc-clang`, if the input file ends in .c, add the `-x c` flag to the clang++/omp invocation?

**Comment by illuhad** [comment]
SYCL is a C++ model. It's not possible to compile any sources that need SYCL as C. If you don't use SYCL in some source, don't compile as SYCL. If you tell it to compile things as SYCL, it *has* to compile as C++ to comply with the SYCL specification and to make the SYCL headers work, which are C++.

I don't see a bug here.

**Comment by Michoumichmich** [comment]
Thanks for your answer, so I guess the only solution to support hipSYCL would be to build a shared object even if the SYCL backend exposes a C api to the rest of the library

**Comment by illuhad** [comment]
You need some sort of interface layer, but I'm not sure you'd need a shared library. It's probably sufficient if you can separate translation units of code that needs SYCL and code that needs the C libraries.

This is a problem that I would expect with any SYCL implementation though since the SYCL headers are always going to require C++.
