### ISSUE TITLE
Slow kernel submission in loop

### ISSUE THREAD

**Issue by almightyvats** [AdaptiveCpp/AdaptiveCpp#630]
**Bug summary**
A seemingly simple time series kernel gets considerably slow after couple hundred timesteps.

**To Reproduce**
Compile and execute the attached code. On my system, it usually starts to slow down after approximately 200 timesteps, in which some time steps taking up to 2 seconds.

A reset in the time taken to submit a new kernel can also be observed periodically.
```
Timestep 0 submission took 0 ms
...
Timestep 100 submission took 14 ms
...
Timestep 202 submission took 181 ms
...
Timestep 303 submission took 544 ms
...
Timestep 304 submission took 28 ms
...
Timestep 413 submission took 1658 ms
```

```cpp
#include <chrono>
#include <sycl/sycl.hpp>

int main() {
  float ha = 42;
  float hr = 1337;
  sycl::buffer<float, 1> ba(&ha, 1);
  sycl::buffer<float, 1> br(&hr, 1);

  sycl::queue queue;

  for (size_t t = 0; t < 1000; t++) {
    const auto before = std::chrono::steady_clock::now();
    queue.submit([&](sycl::handler &cgh) {
      auto a = ba.get_access<sycl::access::mode::read>(cgh);
      auto r = br.get_access<sycl::access::mode::read_write>(cgh);
      cgh.parallel_for(ba.get_range(), [=](sycl::id<1>) {
        (void)a;
        (void)r;
      });
    });
    std::cout << "Timestep " << t << " submission took "
              << std::chrono::duration_cast<std::chrono::milliseconds>(
                     std::chrono::steady_clock::now() - before)
                     .count()
              << " ms\n";
    //  queue.wait_and_throw(); // Makes things faster
  }
  return 0;
}
```

**Describe your setup**
hipSYCL @ 22e94f2
NVIDIA RTX 2070

**Optional additional diagnostic information**
On running with `perf`, the function `recursive_find` appears to be taking most of the time:
```
Children      Self        Shared Object             Symbol 
98.13%       66.33%    libhipSYCL-rt.so          [.] hipsycl::rt::(anonymous namespace)::recursive_find
```

However, the program seems to work as expected with manual queue synchronization.
Also, please note this behavior happens most of the time while sometimes the program works as expected even without manual synchronization.

**Comment by illuhad** [comment]
Can you please try setting the environment variable `HIPSYCL_RT_DAG_REQ_OPTIMIZATION_DEPTH` to a much lower value, e.g. `1` or a much larger value such as `100`?
(See https://github.com/illuhad/hipSYCL/blob/develop/doc/env_variables.md )

The method you have mentioned is used in the DAG optimization phase where hipSYCL descends into the DAG to elide unnecessary dependencies. This environment variable controls how far it descends into the DAG. If it does not descend far enough, it can happen that old dependencies accumulate if new work comes in before old kernels finish. A symptom is that new kernels are executed with a lot of dependencies, which can hurt performance.
If the the depth is set too high, it will spend a lot of time analyzing dependencies which will also hurt performance. This is particularly an issue with very wide DAG trees.

Also please post output when setting the environment variable `HIPSYCL_DEBUG_LEVEL=3`. It should then tell you how many dependencies are considered in the execution.

EDIT: The `wait()` most likely improves performance because hipSYCL only considers running operations in the dependency analysis. Completed operations are purged from all tracking and analysis. So, after you `wait()`, everything is complete, will be purged and you start with a clean slate.

**Comment by almightyvats** [comment]
For `HIPSYCL_RT_DAG_REQ_OPTIMIZATION_DEPTH=1..5` I'm getting clearly improved times around `~0-1ms`, although still with occasional spikes up to `~55ms`. For HIPSYCL_RT_DAG_REQ_OPTIMIZATION_DEPTH=100 times are a lot slower, around `3 seconds`.
`Timestep 656 submission took 2929 ms`

 I'm not certain which parts of the debug log you are referring to, here are some excerpts for different configurations:
 1. `HIPSYCL_RT_DAG_REQ_OPTIMIZATION_DEPTH=1 HIPSYCL_DEBUG_LEVEL=3`
 
![image](https://user-images.githubusercontent.com/77398940/133284405-850f35fb-7446-4e46-bb8d-b407eea4010f.png)

2. `HIPSYCL_DEBUG_LEVEL=3`

![image](https://user-images.githubusercontent.com/77398940/133284551-0a33751f-01f7-43b9-bf84-af115dd25326.png)
![image](https://user-images.githubusercontent.com/77398940/133284592-70d21029-36f6-452f-bfc7-ef363e8c38fe.png)

**Comment by almightyvats** [comment]
After multiple tries with your previous suggestion `HIPSYCL_RT_DAG_REQ_OPTIMIZATION_DEPTH=1`, I am still getting occasional spikes. I tried replacing `queue.wait_and_throw();` with `hipsycl::rt::application::dag().flush_async();`, with no luck.

**Comment by illuhad** [comment]
Hi,

I've just returned this week from vacation and looking into this in more detail is on my todo list.

I'm not sure if it is a reasonable expectation that all submissions take the same time. You are throwing a huge amount of work at the runtime, and at some point that work needs to be processed, and the associated resource management needs to be performed.
I will check if we can improve things, but some spikes will always be expected.

**Comment by illuhad** [comment]
@almightyvats Can you verify if PR #645 resolves the issue for you?

**Comment by almightyvats** [comment]
Yes, that fixed it, thank you!
