### ISSUE TITLE
LLVM backend error when compiling tests with Clang 12.0.1

### ISSUE THREAD

**Issue by fknorr** [AdaptiveCpp/AdaptiveCpp#638]
Compiling `sycl_tests` from develop with Clang 12.0.1 produces the following error in `tests/sycl/atomic.cpp`:

```
fatal error: error in backend: Cannot select: 0x559e4ab2ff10: i64,ch = AtomicLoad<(load seq_cst 8 from %ir.71)> 0x559e3af685c8, 0x559e4aa1ce20, /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:83:10 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:392:1 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:405:30 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/atomic_ref.hpp:454:23 ] ] ]
  0x559e4aa1ce20: i64,ch = CopyFromReg 0x559e3af685c8, Register:i64 %0, /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:83:10 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:392:1 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/generic/hiplike/atomic_builtins.hpp:405:30 @[ /data/install/hipSYCL-develop/bin/../include/CL/../hipSYCL/sycl/libkernel/atomic_ref.hpp:454:23 ] ] ]
    0x559e4aa1c460: i64 = Register %0
In function: _ZNK7hipsycl4sycl10atomic_refIPiLNS0_12memory_orderE0ELNS0_12memory_scopeE3ELNS0_6access13address_spaceE4EE9fetch_subElS3_S4_
clang-12: error: clang frontend command failed with exit code 70 (use -v to see invocation)
```

The CUDA version is 11.4. I do not know what happens for other Clang or CUDA versions.

hipSYCL cmake invocation:
```
 cmake -B build -DCMAKE_INSTALL_PREFIX=/data/install/hipSYCL-develop -DWITH_CUDA_BACKEND=YES
```

Test suite cmake invocation:

```
 cmake -B build -DCMAKE_PREFIX_PATH=/data/install/hipSYCL-develop/lib/cmake -DHIPSYCL_TARGETS=cuda:sm_75
```

Clang info:
```
clang version 12.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

git bisect:
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
bb7930a4f075726667aeea3629f939830dc9d326
406d97a67ef8d3b4d115d4ea901982d0dd82d2a1
b08ea98cc63d9c0ad1309c54c7ebafdfed3786f1
04f67e46f7a92840fc4114937938d98e8d541832
b99dd82d02a0a8345824720fc48d06d761122f23
4ff64a1511da8901938a04f53f684e5225069be5
We cannot bisect more!
```

Not all commits between the last-working version and now can be compiled because of other errors, so they were skipped. The remaining commit ids correspond to PR #584 .

**Comment by illuhad** [comment]
Cannot reproduce with clang 12.0.1 and CUDA 11.4 for `sm_75`. The atomic tests compile for me. However, due to clang's partial support for CUDA newer than 10.1, it's quite possible that PTX support for atomic operation on `sm_75` might be partial or experimental as well. Does it work when targeting older architectures?

According to your error log, the error is triggered by the `long` overload of `fetch_sub`. The PR you mention has introduced support for this in the first place, as previously this overload just was not supported at all. As it is not natively supported by CUDA's `atomicSub`, we do a CAS loop the implemention of which also requires calls to the `__atomic_load()` builtin. My guess is that this is being miscompiled by clang for your target architecture.

**Comment by fknorr** [comment]
Embarrassingly, this was fixed by a clean checkout of the hipSYCL repo, so the culprit seems to have been some dependency tracking hole in the CMake setup. I'm closing this until I manage to reproduce it in a reliable way. Thanks for giving it a try!
