### ISSUE TITLE
malloc inside the kernel

### ISSUE THREAD

**Issue by mrzv** [AdaptiveCpp/AdaptiveCpp#646]
This question stems from my ignorance about SYCL 2020. Is it supposed to be possible to call `malloc_device` from inside a kernel (e.g., from a lambda passed to `parallel_for`)? If the answer is yes, then there is a bug below. If not, it's too bad.

```
      cgh.parallel_for<class vector_add>(work_items,
                                         [=] (cl::sycl::id<1> tid) {
        auto* p = cl::sycl::malloc_device<int>(10, q);
      });
```
produces
```
clang-12: warning: Unknown CUDA version. cuda.h: CUDA_VERSION=11040. Assuming the latest supported version 10.1 [-Wunknown-cuda-version]
ptxas fatal   : Unresolved extern function 'strlen'
clang-12: error: ptxas command failed with exit code 255 (use -v to see invocation)
clang version 12.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-12: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-12: note: diagnostic msg: /tmp/example-4b2286.cu
clang-12: note: diagnostic msg: /tmp/example-a44f1a.cu
clang-12: note: diagnostic msg: /tmp/example-4b2286.sh
clang-12: note: diagnostic msg: 

********************
make: *** [Makefile.common:12: example] Error 255
```

**Comment by illuhad** [comment]
Hi!

this has always been illegal and is still illegal in SYCL 2020. There's currently no way in SYCL to allocate memory from within a kernel. You could rely on hipSYCL's CUDA/HIP source interoperability which would allow you to use `malloc()` in kernels for those backends. In that case, the same caveats apply as in CUDA or HIP regarding performance and allocation sizes of this functionality.

The technical reason why your code in particular does not compile is because hipSYCL follows a multi-backend architecture. This means that `malloc_device()` extracts the `sycl::device` from the `sycl::queue` and then communicates with the hipSYCL runtime to allocate on that particular device. On device, the SYCL runtime is generally unavailable, and SYCL runtime classes such as `queue` and `device` are also unavailable. In fact, the SYCL specification already forbids using a `queue` or `device` object inside a kernel. As a consequence, the kernel compiler tries to pull all sorts of runtime code into the kernel which cannot work there. The first hard problem that it seems to hit is that `strlen()` (which presumably is used in some classes like `std::string` that hipSYCL uses) is unavailable on device, because it's defined inside libc, which is not available on device.

**Comment by mrzv** [comment]
Got it. Thanks a lot for the explanation. It's a pity that SYCL doesn't support this. I'm guessing it's safer to avoid this mechanism entirely (even via CUDA/HIP interoperability).
