### ISSUE TITLE
No synchronization between tasks in copies of an in-order queue

### ISSUE THREAD

**Issue by al42and** [AdaptiveCpp/AdaptiveCpp#655]
**Bug summary**

Per [specs](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:reference-semantics), working with a copy of a SYCL runtime object should be the same as working with the original object itself:

> T must be copy constructible and copy assignable on the host application and within SYCL kernel functions in the case that T is a valid kernel argument. Any instance of T that is constructed as a copy of another instance, via either the copy constructor or copy assignment operator, must behave as-if it were the original instance and as-if any action performed on it were also performed on the original instance and must represent the same underlying native backend object as the original instance where applicable.

However, when one makes copies of an in-order `sycl::queue`, and submits tasks to those copies, the order of operations is not preserved. Apparently, the copy-constructor of `sycl::queue` object copies the `_previous_submission` field, and thus each copy of the queue object only ensures the order of operations submitted to that copy.

**To Reproduce**

- https://gist.github.com/al42and/b1a93f23922a1a5de563064451c85588

The code has a loop and an overcomplicated kernel to increase the chance of clearly demonstrating the problem. The essence is submitting tasks to two queue objects which are copies of the original in-order queue.

- Compile: `syclcc -O3 in_order_not_really.cpp -o in_order_not_really --hipsycl-targets=hip:gfx906`

- Get the runtime trace: `rocprof --stats --hip-trace --parallel-kernels ./in_order_not_really`

- Visualize it with https://ui.perfetto.dev/

![image](https://user-images.githubusercontent.com/933873/140058843-3ffd329f-21e1-48e0-9141-8370a419aac4.png)

**Expected behavior**

H2D copy, kernel, and D2H copy are executed in that particular order without overlapping,

**Describe your setup**
* hipSYCL develop (9ebaa0af), 
* ROCm 4.3, clang-13 from ROCm installation, and with MI50 GPU

**Comment by illuhad** [comment]
thanks for reporting!

> Apparently, the copy-constructor of sycl::queue object copies the _previous_submission field, and thus each copy of the queue object only ensures the order of operations submitted to that copy.

For a moment I was a bit confused because `_previous_submission` is already a `std::weak_ptr`, so the default copy constructor should only copy the pointer. However, it's a `std::weak_ptr<dag_node>`, not a `std::weak_ptr<event>` or `std::weak_ptr<dag_node_ptr>`. I think you are right with your assessment, and I think we need to change it to `std::shared_ptr<std::weak_ptr<dag_node>>` for the best resource management behavior.

**Comment by al42and** [comment]
> For a moment I was a bit confused because _previous_submission is already a std::weak_ptr, so the default copy constructor should only copy the pointer. However, it's a std::weak_ptr<dag_node>, not a std::weak_ptr<event> or std::weak_ptr<dag_node_ptr>. I think you are right with your assessment, and I think we need to change it to std::shared_ptr<std::weak_ptr<dag_node>> for the best resource management behavior.

I think it's not about weak vs. shared ptr. It is about this field being unique to each `sycl::queue` object, rather than being shared by all copies of the original queue. So, if we have `sycl::queue q1(q)`, the `_previous_submission` are different in `q1` and `q`, while the spec requires operations on `q1` to behave the same as if they were performed on `q`. And if we submit one operation to `q`, and then another to `q1`, the second operation won't "see" the first one.

--

Note: I thought that `hipSYCL_prefer_execution_lane` might help here, but it still uses different lanes for data copies and kernels, so it does not seem to be a viable workaround.

**Comment by illuhad** [comment]
> I think it's not about weak vs. shared ptr. It is about this field being unique to each sycl::queue object, rather than being shared by all copies of the original queue. So, if we have sycl::queue q1(q), the _previous_submission are different in q1 and q, while the spec requires operations on q1 to behave the same as if they were performed on q. And if we submit one operation to q, and then another to q1, the second operation won't "see" the first one.

I agree, my point was not about weak vs `shared_ptr`, but that we need to wrap the existing `weak_ptr` in an additional `shared_ptr`. hipSYCL internally works mostly in terms of `dag_node_ptr` which is `shared_ptr<dag_node>`. A SYCL event is effectively just a wrapper around `dag_node_ptr`. Since we don't want to keep alive old operations indefinitely, it makes sense to use a `weak_ptr<dag_node>` for previous submission inside queue instead. However, we still need to wrap it in a `shared_ptr` (`shared_ptr<weak_ptr<dag_node>>`) which was omitted in the current implementation to make sure that all copies see the same `weak_ptr<dag_node>`.

> Note: I thought that hipSYCL_prefer_execution_lane might help here, but it still uses different lanes for data copies and kernels, so it does not seem to be a viable workaround.

Yes, currently it has dedicated streams for kernels and for memcpys and tracks them separately.

**Comment by al42and** [comment]
Thanks for the quick fix!

Slightly related question: is there any benefit of using multiple lanes for an in-order queue instead of a single dedicated lane? It seems like the current approach of emulating an in-order queue over an out-of-order queue emulated over several in-order queues incurs a mild overhead of allocating multiple device streams/queues and inserting extra barriers.

**Comment by illuhad** [comment]
> Slightly related question: is there any benefit of using multiple lanes for an in-order queue instead of a single dedicated lane? 

Yes, there are benefits. It allows us to overlap implicit operations (e.g. data transfers from kernels) with independent operations. The in-order property only affects the actual user-submitted operations, not any additional work that might be submitted as part of implicit data transfers.
Additionally, this enables the `hipSYCL_retarget` extension, which would not be possible otherwise.

>  It seems like the current approach of emulating an in-order queue over an out-of-order queue emulated over several in-order queues incurs a mild overhead of allocating multiple device streams/queues and inserting extra barriers.

The scheduler will try to put operations on the same stream as most of its dependencies. So there should not be a substantial amoun of additional synchronization between streams.
The in-order property should be seen as a convenience feature to avoid putting in dependencies manually. It does not make the required guarantees to implement something like a "low-latency queue". For this, the programmer would additionally need to assert that there are no dependencies with work on other devices or queues. Because we don't have this guarantee it still needs to go through the entire dependency analysis etc which usually makes up the bulk of the latency.

**Comment by al42and** [comment]
I see, thank you for the explanation!
