### ISSUE TITLE
Statically sized local memory allocation

### ISSUE THREAD

**Issue by rolandschulz** [AdaptiveCpp/AdaptiveCpp#669]
For GROMACS we see a a small performance gain from using a static instead of a dynamic local memory allocation. See https://gitlab.com/anton.gorshkov/gromacs/-/commit/3d2cd4cfa8fad627fbbd4d8c193ebdd108a84bb1#note_742928023 for the discussion. The DPC++ extension is https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/LocalMemory/LocalMemory.asciidoc. It would be nice if hipSYCL also had such an extension. This would allow to add this improvement to GROMACS without adding too much code divergence (even if the hipSYCL extension would be slightly different).

**Comment by rolandschulz** [comment]
@mabraham @anton-v-gorshkov @al42and anything to add?

**Comment by illuhad** [comment]
Hi Roland!

unfortunately, this cannot work across all backends in `nd_range` parallel for as we are now also adding support for library-only device backends using nvc++. Because of this, the `sycl::local_memory` wrapper class that we already have has been deprecated. It also never worked on CPU inside `nd_range` parallel for due to these issues.

This functionality is however already available as part of scoped parallelism using `sycl::memory_environment()`:
https://github.com/illuhad/hipSYCL/blob/develop/doc/scoped-parallelism.md
There it works in a portable way across all backends. I don't know how to implement this functionality in a way that can work across all backends in `nd_range` parallel for.

Alternatively, if you are okay with some code divergence and only care about some backends, you could also just rely on hipSYCL's HIP/CUDA source interop and use the HIP/CUDA `__shared__` attribute.

**Comment by al42and** [comment]
> Alternatively, if you are okay with some code divergence and only care about some backends, you could also just rely on hipSYCL's HIP/CUDA source interop and use the HIP/CUDA __shared__ attribute.

I think that would be the easiest option if we decide to adopt the static allocation approach.
