### ISSUE TITLE
Clang compilation failures

### ISSUE THREAD

**Issue by EricAtORS** [AdaptiveCpp/AdaptiveCpp#670]
Hi,

I'm sorry for the very generic title. I wasn't sure what to put.

**Bug summary**
I get this error when compiling my code:
```
fatal error: error in backend: Cannot select: 0x5558cc6e28d0: i16,ch = AtomicLoad<(dereferenceable load acquire (s8) from `i8 addrspace(1)* bitcast (i64 addrspace(1)* @_ZGVZN7hipsycl6common13output_stream3getEvE4ostr to i8 addrspace(1)*)`, align 8, addrspace 1)> 0x5558b2d82098, 0x5558c94cc2c8, git/hipsycl/install/bin/../include/hipSYCL/common/debug.hpp:55:5 @[ git/hipsycl/install/bin/../include/hipSYCL/glue/error.hpp:138:9 ]
  0x5558c94cc2c8: i64 = NVPTXISD::Wrapper TargetGlobalAddress:i64<i64 addrspace(1)* @_ZGVZN7hipsycl6common13output_stream3getEvE4ostr> 0, git/hipsycl/install/bin/../include/hipSYCL/common/debug.hpp:55:5 @[ git/hipsycl/install/bin/../include/hipSYCL/glue/error.hpp:138:9 ]
    0x5558ca2fdfd0: i64 = TargetGlobalAddress<i64 addrspace(1)* @_ZGVZN7hipsycl6common13output_stream3getEvE4ostr> 0, git/hipsycl/install/bin/../include/hipSYCL/common/debug.hpp:55:5 @[ git/hipsycl/install/bin/../include/hipSYCL/glue/error.hpp:138:9 ]
In function: _ZN7hipsycl4glue12throw_resultERKNS_2rt6resultE
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

I was getting similar errors when I would use `pow` or `exp` from cmath instead of sycl. I fixed those and now I have this one left but it is not clear why my code is producing this error.

**To Reproduce**
Compiling with cmake causes the issue. 
Using the diagnostic .sh file does not reproduce the issue.

Unfortunately, I'm not able to reproduce a minimal example and I cannot share the source code.

**Expected behavior**
For it compile without error

**Describe your setup**
* how you have installed hipSYCL, and which version/branch/git commit
On Fedora 35. I pulled the code and followed the instructions.
Git commit: 8756087f60fce5328b95ec097f9ad652e16b23cb

* Describe the dependencies that hipSYCL sits on top of in your setup: 
   * clang version and how clang was installed
     clang version 13.0.0 (Fedora 13.0.0-3.fc35). I installed it from the fedora 35 repo.. I am on Fedora 35.
   * host compiler:
   gcc 11.2.1
   * CUDA version (if applicable)
   11.1
   * ROCm version and how ROCm was installed (if applicable)
   not applicable
* How you have compiled your application and which arguments you have passed to `syclcc`. In particular, which backends and hardware you have compiled for.
I compiled for openmp, cuda sm_60 and sm_61. 

**Optional additional diagnostic information**
The following information can potentially help us:
* For compilation/toolchain or setup-related issues: Setting the environment variable `HIPSYCL_DRYRUN=1` during compilation will cause `syclcc` to print the commands it would execute instead of actually executing. This can help verify the sanity of your setup.
This would be the command generated from HIPSYCL_DRYRUN that fails:
```
/usr/bin/clang++ -I/home/eric/git/hipsycl/install/bin/../include/ -D__HIPSYCL__ -x cuda --cuda-path=/usr/local/cuda -D__HIPSYCL_ENABLE_CUDA_TARGET__ -fplugin=/home/eric/git/hipsycl/install/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_CLANG__ -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem /home/eric/git/hipsycl/install/bin/../include/hipSYCL/std/hiplike --cuda-gpu-arch=sm_60 --cuda-gpu-arch=sm_61 -fpass-plugin=/home/eric/git/hipsycl/install/bin/../lib/libhipSYCL_clang.so -D__HIPSYCL_ENABLE_OMPHOST_TARGET__ -I/home/eric/miniconda3/envs/dragonfly_development/include -fopenmp -I/home/eric/gpucode/build -I/home/eric/gpucode -I/home/eric/code/SDK -I/home/eric/code/SDK/COM/include -I/home/eric/gpucode/external/tinymt -I/home/eric/miniconda3/envs/dragonfly_development/include -isystem /home/eric/git/hipsycl/install/include -O2 -g -DNDEBUG -fconstexpr-steps=10000000 -std=gnu++20 -MD -MT CMakeFiles/OrsLibGPU.dir/simulation/SimulationManager.cpp.o -MF CMakeFiles/OrsLibGPU.dir/simulation/SimulationManager.cpp.o.d -o CMakeFiles/OrsLibGPU.dir/simulation/SimulationManager.cpp.o -c /home/eric/gpucode/simulation/SimulationManager.cpp
```
This passes from the dianostic sh file:
```
 "/usr/bin/clang-13" "-cc1" "-triple" "nvptx64-nvidia-cuda" "-aux-triple" "x86_64-redhat-linux-gnu" "-S" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "SimulationManager.cpp" "-mrelocation-model" "static" "-mframe-pointer=all" "-fno-rounding-math" "-fno-verbose-asm" "-no-integrated-as" "-aux-target-cpu" "x86-64" "-fcuda-is-device" "-mlink-builtin-bitcode" "/usr/local/cuda/nvvm/libdevice/libdevice.10.bc" "-target-feature" "+ptx71" "-target-sdk-version=11.1" "-target-cpu" "sm_60" "-mllvm" "-treat-scalable-fixed-error-as-warning" "-debug-info-kind=line-directives-only" "-dwarf-version=2" "-debugger-tuning=gdb" "-fno-dwarf-directory-asm" "-sys-header-deps" "-D" "__HIPSYCL__" "-D" "__HIPSYCL_ENABLE_CUDA_TARGET__" "-D" "__HIPSYCL_CLANG__" "-U" "__FLOAT128__" "-U" "__SIZEOF_FLOAT128__" "-D" "__HIPSYCL_ENABLE_OMPHOST_TARGET__" "-D" "NDEBUG" "-O2" "-std=gnu++20" "-fdeprecated-macro" "-fno-autolink" "-fdebug-compilation-dir=/home/eric/gpucode/build" "-fconstexpr-steps" "10000000" "-ferror-limit" "19" "-fgnuc-version=4.2.1" "-fcxx-exceptions" "-fexceptions" "-vectorize-loops" "-vectorize-slp" "-load" "/home/eric/git/hipsycl/install/bin/../lib/libhipSYCL_clang.so" "-fpass-plugin=/home/eric/git/hipsycl/install/bin/../lib/libhipSYCL_clang.so" "-cuid=5ffc29734e597f8" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "cuda" "SimulationManager-ee759a.cu"
```
 

**Additional context**

I do use USM in my code as that's where the throw_result seems to be coming from. I also use `sycl::atomic_ref` on my usm pointers. One thing that I wasn't sure about is that I have a `sycl::queue` object in some of my objects that do get sent to the device. For those objects, is it safe to have different memory layouts for host and device? As in, can I exclude the `sycl::queue` member variable to some of my classes with a `#ifndef __SYCL_DEVICE_ONLY__`. That's the only thing that I can think of. All of the actual memory allocation/deallocation are already wrapped around with the not `__SYCL_DEVICE_ONLY__`

**Comment by illuhad** [comment]
Hi!

to me it looks like the issue is that code that is only intended for the host side and uses functionality not supported on device gets pulled into the device code.

Since `queue` in general will not have trivial copy constructor/destructors (reference-counted resource management, error handling), host code gets pulled into device code even if you don't explicitly call any `queue` member functions, because those functions are still triggered when copying an object or when one leaves scope. This is probably why host error handling is compiled in your device code, which likely causes the issue.

 The SYCL spec absolutely does not allow using `queue` inside kernel code, so technically such code is not legal SYCL. 

>  As in, can I exclude the sycl::queue member variable to some of my classes with a #ifndef __SYCL_DEVICE_ONLY__. That's the only thing that I can think of. All of the actual memory allocation/deallocation are already wrapped around with the not __SYCL_DEVICE_ONLY__

In general this is very unsafe to do, as this can cause mismatches in the data layout of the kernel functor between host and device. This can then cause very hard to debug issues if what is plugged in on the host side doesn't match what is expected by the kernel.

If the queue absolutely has to be part of your kernel classes, can you make it a type that can safely be copied without triggering any queue code, such as a `queue*`?

**Comment by illuhad** [comment]
Another thing you could do is wrap the `queue` in an object that prevents copy constructors and destructors from firing, and manually invokes them on the host side. This can be done with a `union` and placement new. 

Here's an example on one of my branches that uses it. This implements a `shared_ptr` that can safely be pulled into data layouts that are used in device code without compiling any of its functionality for device:
https://github.com/illuhad/hipSYCL/blob/baf2723d3af785624c98d1fa67dc4762ab301a84/include/hipSYCL/sycl/libkernel/detail/mobile_shared_ptr.hpp#L52

(note that the develop branch does not yet have `__hipsycl_if_target_*`, but you can use `__SYCL_DEVICE_ONLY__` to achieve the same thing)

**Comment by EricAtORS** [comment]
Thanks @illuhad 
I was able to get further by replacing the `sycl::queue` with a pointer to it. Your explanation makes sense to why that was the issue.

I feel like I'm getting very close to end. 
I have one last issue , but I'm not sure how to debug it.
This is the error I get now:
```
ptxas error   : File uses too much global constant data (0x21108 bytes, 0x10000 max)
```

I don't know what gets put in to constant memory as I don't explicitly create any `sycl::buffer` that uses constant memory.
I assume some constexpr values go there, but also some function pointers too.

So the 2 things that I think that might be problematic in my code are: consteval and std::visit.
One (very unlikely)  possibility is that consteval intermediates are being stored in constant  memory instead of remaining within the compile time scope.

The other possibility is that each kernel invocation is really 72 invocations as my kernel is derived from a class template with 72 different combinations of template parameters. All 72 variants are stored in a `std::variant`, on which I call `std::visit` with a lambda that executes the kernel. Would this pattern be consistent with me implicitly using so much constant memory? If that's the case,  would splitting each of my kernel invocation in to a separate cpp resolve the issue?

**Comment by illuhad** [comment]
> So the 2 things that I think that might be problematic in my code are: consteval and std::visit.
One (very unlikely) possibility is that consteval intermediates are being stored in constant memory instead of remaining within the compile time scope.

I agree that this is a rather unlikely explanation.

> The other possibility is that each kernel invocation is really 72 invocations as my kernel is derived from a class template with 72 different combinations of template parameters. All 72 variants are stored in a std::variant, on which I call std::visit with a lambda that executes the kernel. Would this pattern be consistent with me implicitly using so much constant memory? If that's the case, would splitting each of my kernel invocation in to a separate cpp resolve the issue?

I would expect resources to be allocated per kernel, not per compilation unit. If a lot of kernels are instantiated (as I understood your description), I would expect them all to have their own independent resources and so splitting to separate cpp files wouldn't help.

The first thing I would look at however is something else: As far as I know, CUDA passes kernel arguments via constant memory. In the SYCL world, kernel arguments correspond to the kernel functor. Can you check the `sizeof()` of the kernel functor?

**Comment by EricAtORS** [comment]
The `sizeof(my_kernel_functor)` is 1096 bytes. 

I tried something else: I tried to skip the `std::visit` and just use a "std::get_if" for a specific variant and that got passed the ptxas but I get link errors now on the host, likely due to the improper instantiation of my templates . So if I'm at this stage, I assume that the ptxas stage has passed.

I'm going to continue investigating  this.  Hopefully it's not because of `std::visit` that is causing issue as I don't want to resort to python to generate code to avoid using std::visit. I think it's a cool pattern.

Thanks for the help Aksel. I really appreciate it.

**Comment by illuhad** [comment]
Hmm, if you can find a reproducer I'd be interested in that! Thanks for investigating :-)

**Comment by EricAtORS** [comment]
Programmer at fault:
I had ~140kb `static constexpr std::array`. That explains why the constant memory was using about (0x20000) bytes as it was presumably copying this array to constant memory. The reason why it worked in the simple non `std::visist` case is that the 140kb array is in one of the class template parameters and the version without std::visit just happened to not be using that class.

I changed it to `static constinit std::array` and that "works", but seems funny to do. I'm not sure if there's really anything better. I was thinking of using macros to use the `constinit` on the device and `constexpr` on the host but I could see it causing a mess. Maybe SYCL needs a mechanism where I can specify where to place data that are automatically copied? Or is it simply more of an implementation detail and hipSYCL should check the size of my `constexpr` array and put it in global memory instead if it's too big? My understanding is that this probably more of an issue for the clang compiler to deal with than hipSYCL so I'll leave it at that.

Anyways,
Thanks for the help @illuhad 
I really appreciate it.

**Comment by illuhad** [comment]
Interesting, thanks for the update!

> Maybe SYCL needs a mechanism where I can specify where to place data that are automatically copied? Or is it simply more of an implementation detail and hipSYCL should check the size of my constexpr array and put it in global memory instead if it's too big? My understanding is that this probably more of an issue for the clang compiler to deal with than hipSYCL so I'll leave it at that.

Yes, I believe actually that this is not even a clang thing but more of an LLVM nvptx backend thing, so nothing we could fix on the hipSYCL side.

Here's what I suspect happens based on what you've said:

I believe this boils down to a registerization issue. Even though the array *content* is known at compile time, the indices that are used to *access* the array may not be known at compile time in general (unless LLVM can figure those out at compile time, which I'm assuming is not the case for you). Because it needs to be able to provide random access indexing, LLVM therefore cannot place the array content in registers when they are needed, and instead needs to put them in actual memory. 
Usually this would go in a special section of global memory, however LLVM capitalizes on the fact that the array is constant and therefore puts it into constant memory instead.
This is a fairly fundamental issue on GPUs that is difficult to solve. One thing that might fix it is to not use random access arrays but something like
```c++
template<class T>
struct table {
  T v00;
  T v01;
  T v02;
  ....
};
```
But obviously this is cumbersome and does not work for all use cases.

If this is the reason, it would arise during registerization which happens in the LLVM backend, and would similarly affect any other programming model targeting NVIDIA GPUs through LLVM (and maybe even other compilers).
