### ISSUE TITLE
Unrecognized command line option ‘-sycl-std=2020’ if only the OpenMP backend is enabled

### ISSUE THREAD

**Issue by breyerml** [AdaptiveCpp/AdaptiveCpp#700]
**Bug summary**
If hipSYCL is compiled only for the CPU using the OpenMP backend, the SYCL2020 flag `-sycl-std` isn't recognized.
If any other backend is enabled additionally, the flag is correctly recognized.

**To Reproduce**
Build hipSYCL without CUDA, HIP, or Level Zero support and try compiling any file using `syclcc` with the `-sycl-std` flag.

**Expected behavior**
The `-sycl-std` flag shouldn't cause a compilation error if only OpenMP is available as backend.

**Describe your setup**
Compiled using GCC 9.3.0 with hipSYCL installed from commit 6962942c430a7b221eb167b4272c29cf397cda06.
The full command to reproduce the issue: `syclcc -sycl-std=2020 --hipsycl-targets="omp" main.cpp`

**Optional additional diagnostic information**
Complete error message: `c++: error: unrecognized command line option ‘-sycl-std=2020’`

**Comment by illuhad** [comment]
`-sycl-std` is not a hipSYCL flag - all hipSYCL options start with `--hipsycl-*`.

What happens is that you are seeing parts of DPC++ that have already been upstreamed to clang. So, if you compile with clang, you can set it (but it will have no effect, because it is part of DPC++ and only affects DPC++ compilation). If you build exclusively for CPU, hipSYCL can be configured to use any other OpenMP compiler. If this compiler is not clang (in your case it seems to be g++), this flag doesn't exist.

So, not really a hipSYCL bug ;)

**Comment by breyerml** [comment]
Ahh for some reason I thought the `-sycl-std` flag has been standardized by the SYCL spec. 
But apparently, that's not the case.
