### ISSUE TITLE
Reference to build path after installation

### ISSUE THREAD

**Issue by alexschroeter** [AdaptiveCpp/AdaptiveCpp#708]
Hello,

I build hipSYCL using cmake (with cmake -DCMAKE_INSTALL_PREFIX=/opt/hipSYCL/ -DCMAKE_CXX_COMPILER=clang-13 .. ) and installed using "make install".

A small test program was created and compiled with cmake (by another user on the server). Running the program throws the following warning (the referenced file is from the build path, not the program or the installation path):

[hipSYCL Warning] from /home/aschroeter/hipSYCL/src/runtime/hip/hip_hardware_manager.cpp:49 @ hip_hardware_manager(): hip_hardware_manager: Could not obtain number of devices (error code = HIP:101)
 
I am a bit confused on why there is a reference to that folder at all. When I run the binary with the user that has access to the home directory of the user who installed hipSYCL there is no issue, since the file still exists and is accessible.

The file reference I believe should point to  /opt/hipSYCL/include/hipSYCL/runtime/hip/hip_hardware_manager.hpp and that file exists.

ldd
        linux-vdso.so.1 (0x00007ffd1a595000)
        libhipSYCL-rt.so => /opt/hipSYCL/lib/libhipSYCL-rt.so (0x00007fdab9cd5000)
        libboost_context.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_context.so.1.65.1 (0x00007fdab9ad2000)
        libboost_fiber.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_fiber.so.1.65.1 (0x00007fdab987b000)
        libcudart.so.11.0 => /usr/local/cuda/lib64/libcudart.so.11.0 (0x00007fdab95d7000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fdab91ca000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fdab8e2c000)
        libomp.so.5 => /usr/lib/x86_64-linux-gnu/libomp.so.5 (0x00007fdaba004000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fdab8c14000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdab89f5000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdab8604000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdab8400000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdab9f17000)
        libboost_filesystem.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.65.1 (0x00007fdab81e6000)
        libboost_system.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_system.so.1.65.1 (0x00007fdab7fe1000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdab7dd9000)

Thank you

**Comment by illuhad** [comment]
Hi Alex!

this path is mainly there to help us devs quickly find the place in the code where the error was emitted. As such, it points to the position in the hipSYCL source where the error was first detected.

In your case, this happens inside the runtime library's source code, not in the header files. Therefore it points to a cpp file, not a header file. Since there's no point installing cpp files, you cannot see them anymore in the final hipSYCL installation. This is not an issue by itself.

This is the place where the warning is emitted: https://github.com/illuhad/hipSYCL/blob/49fd02499841ae884c61c738610e58c27ab51fdb/src/runtime/hip/hip_hardware_manager.cpp#L50

The warning you are getting is because `hipGetDeviceCount()` fails. Whether the source file is inaccessible is irrelevant to this warning, but if it works with another user as you say you might want to check the user permissions to access the GPU.
With HIP you usually need to be in the `video` group.

**Comment by alexschroeter** [comment]
Thank you. You are correct, the other user wasn't in the video group needed for ROCm. I was confused by the path but not having access to the device count makes sense and is very much what the warning was about.
