### ISSUE TITLE
Warning when using buffers initialized with host_accessors

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#721]
I was trying to create a buffer and initialize it after the construction with an host_accessor, but I get this warning:
```
dag_direct_scheduler: Detected a requirement that is neither of discard access mode (SYCL 1.2.1) nor noinit property (SYCL 2020) that accesses uninitialized data. Consider changing to discard/noinit. Optimizing potential data transfers away
```
But the data accessed on the device are initialized correctly looking at the output of my application.
This is an example code:
```c++
int main(){
	queue q{gpu_selector()};

	buffer<int,1> b(10);
	std::vector<int> h_data(10,1);

	{
	  host_accessor acc{b};
	  int* ptr = acc.get_pointer();
	  std::copy(h_data.begin(), h_data.end(), ptr);
	}
	
	q.submit([&](handler &cgh) {
		accessor<int,1> acc{b, cgh};
		cgh.parallel_for<class Init>(range<1>(10), [=](item<1> idx) { acc[idx] = acc[idx] * 2; });
	});
}
```
My question is: why hipSYCL notifies me of accessing uninitialized data? Is there a more correct way to initialize a buffer on the host after the construction?

**Comment by illuhad** [comment]
Yes, you can give the `host_accessor` the `no_init` property: `host_accessor acc{b, sycl::no_init}`.

`no_init` tells the SYCL runtime that you do not want any data transfers to take place because you don't care about previous data. Without `no_init`, you rely on the SYCL runtime to detect that no data transfers are necessary because the buffer is used for the first time. Most implementations probably will be doing that optimizations, but you can be more certain with `no_init`.

For a `host_accessor` that initializes the buffer, it's less likely that data transfers would be emitted, but there can still be some corner cases, e.g. when constructing a buffer on top of an existing USM pointer (using our buffer-USM interop extension).

hipSYCL reliably detects such optimization opportunities when first using a buffer, which is why you get this warning, and optimizes data transfers away. But I would say it is good practice to still add `no_init` whenever you use a buffer for the first time to make sure nothing unexpected happens. This is what this warning is about.

**Comment by Luigi-Crisci** [comment]
It's clear now, thank you!
