### ISSUE TITLE
How to use hipSYCL + MPI?

### ISSUE THREAD

**Issue by sbalint98** [AdaptiveCpp/AdaptiveCpp#725]
My approach to compiling an application with MPI and hipSYCL was to set the `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` cmake options to `mpicc` and `mpicxx` wrappers when compiling hipSYCL. like this:

```
cmake -D CMAKE_BUILD_TYPE=Release \
      -D CMAKE_C_COMPILER=/opt/openmpi4/bin/mpicc \
      -D CMAKE_CXX_COMPILER=/opt/openmpi4/bin/mpicxx \
      -D LLVM_DIR=/opt/rocm/llvm/lib/cmake/llvm \
      -D ROCM_PATH=/opt/rocm \
      -D WITH_ACCELERATED_CPU=OFF \
      -S /home/rocm-user/hipSYCL/ \
      -B /home/rocm-user/hipSYCL/build 
```

However after successful installation, in the syclcc.json only the default cxx compiler is set to mpicxx. This results in the MPI specific flags not being added to the compilation arguments. I wonder if there is a better approach to use MPI+hipSYCL or this is a bug or a missing feature in hipSYCL.

**Comment by illuhad** [comment]
Why do you want to build hipSYCL with MPI? hipSYCL does not use any MPI specific functionality. I would recommend going the other way (as it's usually handled with MPI):
Tell `mpicxx` to use `syclcc` as compiler rather than the other way round.

I think you probably wanted `syclcc` to invoke `mpic++` by setting `CMAKE_CXX_COMPILER` - but remember that this only affects `HIPSYCL_CPU_CXX` which is only used in the `omp.library-only` flow. If you target GPUs, hipSYCL will be forced to switch to using its configured clang.

**Comment by al42and** [comment]
I had some success with hipSYCL + OpenMPI by manually setting the flags reported by `mpicxx --showme:compile` and `mpicxx --showme:link`, and not using `mpicc`/`mpicxx` at all.

**Comment by sbalint98** [comment]
Thank you both for your quick response. As @illuhad figured out my intention was to use `mpicxx` as the compiler that `syclcc` invokes. And as pointed out, setting the compiler to `mpicxx` and `mpicc` for the compilation of hipSYCL didn't change anything with regard to the targeting GPUs. 

I tested both approaches suggested:

Setting the compiler for OMPI with `OMPI_CC` and `OMPI_CXX` didn't work since some files in the project were explicitly passed the `--std=c++11` flag which broke `syclcc`

Copying the options into the `syclcc.json` suggested by @al42and caused some link failures in the hipSYCL runtime because of missing pthreads symbols. (While compiling application code) Although I had to append `-pthreads` to the compile flags, I  don't understand how this issue could arise.

The approach that eventually seems to have worked was to set OMPI to use clang, and set the `default-clang` option in `syclcc.json` manually to `mpicxx`.

**Comment by illuhad** [comment]
> Setting the compiler for OMPI with OMPI_CC and OMPI_CXX didn't work since some files in the project were explicitly passed the --std=c++11 flag which broke syclcc

Well, if something is explicitly C++ 11 it cannot with SYCL because SYCL requires C++ 17 or newer.

The project in question should move to a newer standard, or at least allow compilation with newer standards.

As a workaround, we could add some option to `syclcc` to tell it that it can automatically promote older `-std` arguments to newer standards - but the proper solution would be to fix that in the project.

**Comment by sbalint98** [comment]
Actually why syclcc is not promoting automatically? I believe if we are compiling with syclcc there must be a c++17 capable compiler available. The current behaviour of syclcc seems to be quite restrictive to me.

**Comment by illuhad** [comment]
Because if the user explicitly passes `-std=c++11`, they explicitly request a configuration that we cannot support. Since there are some (but not many) changes in C++ that prevent full forward-compatibility, the rationale is that in this case the user should get an error.

If you explicitly request something that is unsupported, I think you should get informed by default :)

**Comment by sbalint98** [comment]
Thank you for all the comments and help. The final solution was to install a recent MPI with proper configuration file-based cmake integration. That way one did not have to set `mpicc` and `mpicxx` as compilers, and everything worked out of the box.
