### ISSUE TITLE
CUDA error 4 on buffer deallocation

### ISSUE THREAD

**Issue by Luigi-Crisci** [AdaptiveCpp/AdaptiveCpp#740]
**Bug summary**
Not sure if this is a bug or a control flow issue. I have a static map in which I put multiple structures, each composed of several sycl::buffers. The program works fine, but on termination I get this `[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event.cpp:65 @ wait(): cuda_node_event: cudaEventSynchronize() failed (error code = CUDA:4)`, probably due to some deallocation issue. 
I tried also DPC++ and I didn't get any errors.

**To Reproduce**
I made a simple example to reproduce this error
```C++
#include <iostream>
#include <CL/sycl.hpp>
using namespace cl::sycl; // (optional) avoids need for "sycl::" before SYCL names

struct test_error_cuda4{
    buffer<int, 1> n;
    test_error_cuda4(int x):n(x) {}
	void init() { n.get_host_access()[0] = 100; }
};

static std::unordered_map<int,std::shared_ptr<test_error_cuda4>> p;

void g(queue &myQueue){
	
  p.emplace(1, std::move(std::make_shared<test_error_cuda4>(53)));
  auto& buff = p.find(1)->second;
  buff->init();
 {
    myQueue.submit([&](handler& cgh) {
      const accessor test_eva_error_cuda4 {buff->n, cgh, read_only}; 
      cgh.parallel_for(nd_range<2>{range<2>{4,32},range<2>{4,32}}, [=](nd_item<2> it) {
          if(it.get_local_linear_id() == 0) printf("%d\n", test_eva_error_cuda4[0]);
      });
    }).wait_and_throw();
  }
}


int main() {
  queue myQueue{gpu_selector{}};
  g(myQueue);
}
```
Output:
```bash
100
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event.cpp:65 @ wait(): cuda_node_event: cudaEventSynchronize() failed (error code = CUDA:4)
```

**Describe your setup**
* hipSYCL develop (1046a78777a23ca75c6ea4e92291f1dbe36169ca)
* Built with
   * Clang 13 (manually built)
   * GCC 11
   * Boost 1.68
   * CUDA 11.4 (target arch = sm_70)
* DPC++ release: https://github.com/intel/llvm/releases/tag/2021-12

**Comment by illuhad** [comment]
This is probably caused by the unload order of libraries/shutdown order of backends.
Probably the buffer destructor is triggered when CUDA or the hipSYCL CUDA backend is already in the process of being unloaded. In the buffer destructor, it tries to ensure that all operations that need the buffer have completed. However for CUDA the query fails at that point.
We can only do so much here; unload behavior of CUDA drivers other shared libraries that might be involved is highly implementation-specific.

Workaround incoming.

**Comment by Luigi-Crisci** [comment]
Failing again on develop (bb1db13ca3d73f24c5f99b566c5066e05e668ff1)

New output:
```
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_allocator.cpp:134 @ query_pointer(): cuda_allocator: query_pointer(): query failed (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_queue.cpp:160 @ ~cuda_queue(): cuda_queue: Couldn't destroy stream (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_queue.cpp:160 @ ~cuda_queue(): cuda_queue: Couldn't destroy stream (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_queue.cpp:160 @ ~cuda_queue(): cuda_queue: Couldn't destroy stream (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_queue.cpp:160 @ ~cuda_queue(): cuda_queue: Couldn't destroy stream (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
[hipSYCL Error] from /hipSYCL/src/runtime/cuda/cuda_event_pool.cpp:59 @ destroy(): cuda_event_factory: Couldn't destroy event (error code = CUDA:4)
```

**Comment by illuhad** [comment]
Not sure what can be done at this point. Probably it will always be borderline undefined behavior if you have to perform backend operations (such as deallocations) inside destructors of global objects. 
If you write any CUDA application with this pattern, you might run into the exact same issue because CUDA might enter its shutdown phase and deinitialize before static destructors of your application are executed.
