### ISSUE TITLE
cmake options to select the ROCm LLVM 

### ISSUE THREAD

**Issue by zjin-lcf** [AdaptiveCpp/AdaptiveCpp#797]
What is the cmake command options for selecting ROCm's LLVM (/opt/rocm/llvm/) instead of the LLVM installed by default ?  Thanks.

-- Building hipSYCL against LLVM configured from /usr/lib/llvm-10/cmake
-- Selecting clang: /usr/lib/llvm-10/bin/clang++

**Comment by illuhad** [comment]
Hi, this is described here: https://github.com/illuhad/hipSYCL/blob/develop/doc/install-rocm.md

**Comment by zjin-lcf** [comment]
It selects the default. Am I doing right ? 

cmake ../ -DCMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/clang++ -DCMAKE_C_COMPILER=/opt/rocm/llvm/bin/clang -DWITH_ROCM_BACKEND=ON

```
-- The C compiler identification is Clang 13.0.0
-- The CXX compiler identification is Clang 13.0.0
-- Check for working C compiler: /opt/rocm/llvm/bin/clang
-- Check for working C compiler: /opt/rocm/llvm/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rocm/llvm/bin/clang++
-- Check for working CXX compiler: /opt/rocm/llvm/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: context fiber
-- hip::amdhip64 is SHARED_LIBRARY
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- Building hipSYCL against LLVM configured from /usr/lib/llvm-10/cmake
-- Selecting clang: /usr/lib/llvm-10/bin/clang++
CMake Warning at CMakeLists.txt:169 (message):
  clang version to old (10 < 11) to be used with CPU acceleration support,
  disabling WITH_ACCELERATED_CPU


-- Using clang include directory: /usr/lib/llvm-10/lib/clang/10.0.0/include/..
```

**Comment by illuhad** [comment]
You are not using `-DROCM_PATH` as described in the documentation I have linked. Also, why are you using the clang from the default ROCm as C++ compiler, when you want to build against a different ROCm?

In case you want to build hipSYCL against the clang/LLVM that comes with ROCm, setting the cmake C++ compiler is not the right thing to do, as it will just set the compiler that hipSYCL will be compiled with.

Please refer to the installation documentation: https://github.com/illuhad/hipSYCL/blob/develop/doc/installing.md
in particular including the previously mentioned bits about ROCm: https://github.com/illuhad/hipSYCL/blob/develop/doc/install-rocm.md
and also LLVM, since it is required by ROCm: https://github.com/illuhad/hipSYCL/blob/develop/doc/install-llvm.md

**Comment by illuhad** [comment]
I would also recommend using a newer clang. Your build is currently configured for a clang/LLVM 10 which might not result in best performance, and will not work with newer ROCm versions.

**Comment by illuhad** [comment]
Apologies, I misread your question as how to select a different ROCm. You can select a different LLVM using `-DLLVM_DIR`:
https://github.com/illuhad/hipSYCL/blob/develop/doc/install-llvm.md

Note that building hipSYCL against ROCm's clang/LLVM is only partially supported. From https://github.com/illuhad/hipSYCL/blob/develop/doc/install-rocm.md:
>  Such configurations typically work, but are generally less tested.
    Also note that the LLVM distributions shipping with ROCm are not official LLVM releases, and depending on when the upstream development was last merged, may have slightly diverging functionality. There are multiple known cases where this causes problems [...]:

**Comment by zjin-lcf** [comment]
I got the following error.   Thanks for the suggestion.

/home/user/hipSYCL/src/compiler/cbs/VectorShapeTransformer.cpp:74:8: error: no member named 'isOpaquePointerTy' in 'llvm::PointerType'
    if IS_OPAQUE (PtrTy)

**Comment by illuhad** [comment]
Yes: https://github.com/illuhad/hipSYCL/pull/765#discussion_r936610122

It's one of the cases where the LLVM that comes with ROCm does not provide the APIs that regular upstream LLVM has for a given LLVM version. This is because the ROCm developers just randomly branch off their LLVM, and then don't merge in features that get merged in upstream LLVM. There is also currently no way for us to detect this.
We have reported this issue to AMD, but they are not very responsive unfortunately: https://github.com/RadeonOpenCompute/ROCm/issues/1680

As I've said, because of such issues, building hipSYCL against ROCm LLVM is only semi-supported. I know that it works out-of-the-box with ROCm 5.2 though. These issues do not happen when building hipSYCL against regular clang of the same version, which is also more tested in general than whatever comes with ROCm.

The error you get is part of the CPU compiler acceleration. If you are not interested in performance on CPU, you can try to disable this feature using `-DWITH_ACCELERATED_CPU=OFF`, or manually change it here so that it also takes the path for pre-LLVM 13 for your compiler: https://github.com/illuhad/hipSYCL/blob/cc2e3556151d5b5c65a1811111c62308d06ceb50/src/compiler/cbs/VectorShapeTransformer.cpp#L28
