### ISSUE TITLE
hipSYCL with ROCm provided clang - __oclc_ABI_version

### ISSUE THREAD

**Issue by alexschroeter** [AdaptiveCpp/AdaptiveCpp#808]
Hello,

I have compiled hipSYCL with the clang-14 included in the ROCm 5.2.1 installation.

When I compile I get:

```
lld: error: undefined symbol: __oclc_ABI_version
>>> referenced by /tmp/mwe-5ede8f.o:(__assert_fail)
>>> referenced by /tmp/mwe-5ede8f.o:(__assert_fail)
>>> referenced by /tmp/mwe-5ede8f.o:(__assert_fail)
>>> referenced 17 more times
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)
CMakeFiles/mwe-hipsycl-fft.dir/build.make:77: recipe for target 'CMakeFiles/mwe-hipsycl-fft.dir/src/mwe.cpp.o' failed
make[2]: *** [CMakeFiles/mwe-hipsycl-fft.dir/src/mwe.cpp.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/mwe-hipsycl-fft.dir/all' failed
make[1]: *** [CMakeFiles/mwe-hipsycl-fft.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2
```

I found [this post](https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html) which suggests using amdclang/amdclang++ to compile since in all current versions other than that one, the OCLC version is missing/not set correctly.

But if I follow this advice, I get the following error:
```
error: unable to load plugin '/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so': '/opt/hipSYCL/bin/../lib/libhipSYCL_clang.so: undefined symbol: _ZTIN5clang15PluginASTActionE'
```

Should I be using clang-15 or what could be the problem here?

**Comment by illuhad** [comment]
Interesting, I am using hipSYCL with ROCm clang 5.2.1 on my local machine, and it works flawlessly. However, I did have to build hipSYCL against the ROCm LLVM/clang because with regular clang 14 I get the error you describe. Such issues can happen sometimes with very new ROCm releases if required functionality for a particular ROCm version is not yet available in upstream clang.

With ROCm 5.2.1 clang it works out of the box for me.

Are you positive that you are actually building hipSYCL against the ROCm clang? Can you share the commands you have used to build and/or your `syclcc.json`?

Which operating system are you using? The post you mention specifically refers to Cray environments, so maybe this is the difference.

The post also says that both `hipcc` as well as `amdclang` work:
> There are multiple workarounds, including:
>    Build with amdclang/hipcc from the ROCm 5.2.0 release.

AFAIK `hipcc` just invokes ROCm clang with a couple of additional flags. According to this post, the issue seems to occur when mixing compiler and ROCm versions, i.e. if you do *not* use one of the compilers that are part of ROCm. This should not be the case for you.

> But if I follow this advice, I get the following error:

This error means that the hipSYCL clang plugin cannot be loaded into the clang you want to use because the plugin and clang have incompatible ABI. This happens if you attempt to use a clang that is not exactly the same as the clang/LLVM that you have built hipSYCL against.
If you wish to use `amdclang` (no idea if it works, never tried it), you need to build hipSYCL against the exact LLVM libraries using `-DLLVM_DIR=` that were used to build `amdclang`.

You could also try the second workaround:
```
CFLAGS += --hip-device-lib=hip.bc
CFLAGS += --hip-device-lib=ocml.bc
CFLAGS += --hip-device-lib=ockl.bc
CFLAGS += --hip-device-lib=oclc_daz_opt_off.bc
CFLAGS += --hip-device-lib=oclc_unsafe_math_off.bc
CFLAGS += --hip-device-lib=oclc_finite_only_off.bc
CFLAGS += --hip-device-lib=oclc_correctly_rounded_sqrt_on.bc
CFLAGS += --hip-device-lib=oclc_wavefrontsize64_on.bc
CFLAGS += --hip-device-lib=oclc_isa_version_90a.bc
CFLAGS += --hip-device-lib=oclc_abi_version_400.b
```
You could add these flags to the ones hipSYCL uses for HIP compilation by editing `syclcc.json` accordingly.

**Comment by alexschroeter** [comment]
I have figured out the issue.
Looking at the json I found a reference to llvm-13, which I didn't understand where that was coming from since I build with `cmake -DCMAKE_INSTALL_PREFIX=/opt/hipSYCL/ -DLLVM_DIR=/opt/rocm/llvm/lib/cmake/llvm ..`

I still had some remnants of an old installation linking to llvm-13. After removing everything from /usr/local it now correctly shows the rocm clang in the syclcc.json everywhere.
