### ISSUE TITLE
Incomplete Launch Groups Creates group_barrier deadlock.

### ISSUE THREAD

**Issue by frobnitzem** [AdaptiveCpp/AdaptiveCpp#809]
**Bug summary**
Kernel launches do not start all threads within a thread group simultaneously - resulting in deadlock.  I encountered this error launching an nd_range kernel with shape (1,256,4) by (1,1,4) -- using the last index as an intra-group index.  I don't think this is the expected behavior, but it's hard to find an explicit requirement for "all threads in a group are launched" in the spec.

**To Reproduce**
```
/* test.cc */
#include <stdio.h>
#include <CL/sycl.hpp>

namespace sycl = cl::sycl;

int main() {
    sycl::queue queue;
    queue.submit([&](sycl::handler &cgh) {
        cgh.parallel_for(sycl::nd_range<3>(
                         sycl::range(1, 128*2, 4),
                         sycl::range(1, 1, 4)),
                        [=](sycl::nd_item<3> item) {
            const size_t cid = item.get_group(0);
            const size_t a = item.get_group(1);
            const size_t k = item.get_local_id(2);

            printf("Started thread %d / %d\n", a, k);
            if(a%128 > 4) {
                return;
            }
            printf("Continuing thread %d / %d\n", a, k);
            sycl::group_barrier(item.get_group());
        });
    });
    queue.wait();
    return 0;
}
```

    $SYCL/bin/syclcc -o test test.cc
    $ ./test

**Expected behavior**
The program should complete without error.

**Describe your setup**

hipSYCL version "0.9.2", commit="49fd02499841ae884c61c738610e58c27ab51fdb"
installed via spack on OSX 11.6.8 using brew libomp.
```
$ $SYCL/bin/syclcc --version
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ otool -L ./test
./test:
	@rpath/libhipSYCL-rt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/spack/opt/spack/darwin-bigsur-skylake/apple-clang-13.0.0/boost-1.69.0-5viwyttojzzlsdaq7w7xbaah4pynbxlw/lib/libboost_context.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/spack/opt/spack/darwin-bigsur-skylake/apple-clang-13.0.0/boost-1.69.0-5viwyttojzzlsdaq7w7xbaah4pynbxlw/lib/libboost_fiber-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)

$ brew info libomp
libomp: stable 14.0.6 (bottled)
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/usr/local/Cellar/libomp/14.0.6 (7 files, 1.6MB) *
  Poured from bottle on 2022-07-03 at 17:25:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libomp.rb
License: MIT
```

**Optional additional diagnostic information**

Output of test code - showing only "continued" work items and sorting for clarity:
```
$ ./test | grep Continu
Continuing thread 0 / 0
Continuing thread 0 / 1
Continuing thread 0 / 2
Continuing thread 0 / 3
Continuing thread 1 / 0
Continuing thread 1 / 1
Continuing thread 1 / 2
Continuing thread 1 / 3
Continuing thread 2 / 0
Continuing thread 2 / 1
Continuing thread 2 / 2
Continuing thread 2 / 3
Continuing thread 3 / 0
Continuing thread 3 / 1
Continuing thread 3 / 2
Continuing thread 3 / 3
Continuing thread 4 / 0
Continuing thread 4 / 1
Continuing thread 4 / 2
Continuing thread 4 / 3
Continuing thread 128 / 0 # <- note: this actually printed last.
Continuing thread 130 / 0
Continuing thread 130 / 1
Continuing thread 130 / 2
Continuing thread 130 / 3
Continuing thread 131 / 0
Continuing thread 131 / 1
Continuing thread 131 / 2
Continuing thread 131 / 3
Continuing thread 132 / 0
Continuing thread 132 / 1
Continuing thread 132 / 2
Continuing thread 132 / 3

^C
```

**Additional context**

**Comment by illuhad** [comment]
Does this happen both for `--hipsycl-targetes="omp.library-only"` as well as for `--hipsycl-targets="omp.accelerated"`?

What do you mean by "thread"? Note that what you call thread in your program output is unrelated to what is usually called a thread.

It is not required that all work items be launched at once, however the semantics of collective group algorithms such as barriers must be preserved. For example, in `omp.library-only`, hipSYCL first launches a single work item to probe whether a group contains a barrier, because the presence of barriers may require switching to a different less efficient execution model with different forward progress guarantees for each work item.

EDIT: At least for `omp.library-only`, I cannot reproduce the deadlock. I could not yet test with `omp.accelerated`.

**Comment by frobnitzem** [comment]
I'm thinking about the CUDA sense, where my kernel uses a group of 4 CUDA threads (or hopes for a 4-element wide SIMD on CPU).

Compiling with `omp.library-only` is the only one that works for me as well.  However it deadlocks for me.

Its behavior appears to depend on the kernel launch bounds.  For example, if I use 
`nd_range<2>({128*3/2, 4}, {1, 4})` I don't see the issue, but with `nd_range<2>({128*2, 4}, {1, 4})` I do.

Higher numbers seem to be more prone to causing trouble.  `nd_range<2>({73, 4}, {1, 4})` was OK `nd_range<2>({373, 4}, {1, 4})` was bad.

**Comment by illuhad** [comment]
Thank you, I can reproduce with `nd_range<3>{1,373,4}` for the global work size. It seems to be related to the early exit - removing the return statement fixes the issue for me.  I believe the return statement is legal though, since it only depends on the group id, not the local id.

**Comment by illuhad** [comment]
I believe I have a fix in #814. Please let me know if this resolves the issue (It does for me :-) ).

> I'm thinking about the CUDA sense, where my kernel uses a group of 4 CUDA threads (or hopes for a 4-element wide SIMD on CPU).

For the sake of completeness, please note that in the `omp.library-only` flow, if there are barriers present, you will not get vectorization across work items, so your hope that the 4-element work group is spread across a 4-element SIMD unit will not be true, and you might not get the performance you are expecting with this approach.

*Background:* The reason is that it is not possible to implement the SYCL `nd_range` model purely as a C++ library (as done by `omp.library-only`) without giving each work item its own stack (e.g. one OS thread per work item, or in our case, one fiber per work item). This is required to ensure that barriers can be implemented with the correct semantics and all work items can reach a barrier at the same time.
However, this prevents any vectorization across work items.

If you want to use `omp.library-only` and `nd_range` parallel for with barriers, for best performance I recommend
* putting inner loops inside the work items which might then be vectorized (to compensate for lack of cross-work-item vectorization), 
* and increasing the computational load per work item and barrier invocation such that the relative cost of stack context switches caused by barrier invocations is reduced.
 
It is possible to get good performance with `omp.library-only`, but might require structuring your code somewhat differently than you might generally do on, say, a GPU.

Vectorization across work items with barriers and `nd_range` parallel for is only possible with dedicated compiler magic; if you want this (and typical GPU-like code perform well on CPU) please use `omp.accelerated` which provides additional compiler logic exactly for this purpose :-)

Of course, if you just want to use `omp.library-only` for development in order to later run with a different backend on e.g. GPUs all of  these performance considerations won't matter :-)

**Comment by frobnitzem** [comment]
Hooray! This fixes the issue for me.

Yes - I'm developing on my laptop and running on MI250x in production.  Eventually I'll try and improve CPU performance as well, but it's not a priority at present.

**Comment by illuhad** [comment]
Alright, thanks for the feedback! :)
