### ISSUE TITLE
Compilation error using nvc++ compilation flow

### ISSUE THREAD

**Issue by nmnobre** [AdaptiveCpp/AdaptiveCpp#811]
Hi @illuhad,

I'm getting an error, use of undefined value, when compiling this:

```
#include <SYCL/sycl.hpp>

template <typename L>
void ParallelFor (L&& f) noexcept
{
    sycl::queue q;
    q.submit([&] (sycl::handler& h) {
        h.parallel_for(sycl::nd_range<1>(sycl::range<1>(266240), sycl::range<1>(256)),
        [=] (sycl::nd_item<1> item) { f(); });
    });
}

void carrots()
{
    ParallelFor([=] __attribute__((device)) () noexcept {});
}
```

with `syclcc --hipsycl-targets=cuda-nvcxx -c carrots.cpp`.

Is it me, nvc++ or hipSYCL?

**Comment by illuhad** [comment]
Thank you, it works for me if I remove the `__device__` attribute. I believe this is probably because in SYCL, your kernels will in general always be compiled for CPU as well. The spec requires that there always must be at least *some* device available. So, in order to guarantee this even if you don't have a GPU in your system, we have to compile the kernel at least for sequential CPU execution as fallback.

This doesn't work if some of your code is explicitly device-only. You can have such code constructs if you guard them as backend-specific, and indeed the following compiles:
```
#include <SYCL/sycl.hpp>

template <typename L>
void ParallelFor (L&& f) noexcept
{
    sycl::queue q;
    q.submit([&] (sycl::handler& h) {
        h.parallel_for(sycl::nd_range<1>(sycl::range<1>(266240), sycl::range<1>(256)),
        [=] (sycl::nd_item<1> item) { __hipsycl_if_target_cuda(f();) });
    });
}

void carrots()
{
    ParallelFor([=] __attribute__((device)) () noexcept {});
}

```

Note that outside of the nvc++ world, you need to be careful with this, as it can lead to to `f` only being captured in the device compilation pass (because it's unused on the host) which can then lead to a mismatch of the data layout of the kernel lambda between host and device, when the kernel is invoked.

**Comment by nmnobre** [comment]
Thank you, that does make sense. Could you just please clarify your ending note, in particular the data layout mismatch?

**Comment by illuhad** [comment]
Firstly, it is important to realize that nvc++ is different from the other hipSYCL compilation flows (or indeed, any other SYCL implementation, or clang-based heterogeneous models) in that it only parses the code once, and then separates the device code from the host code at the IR level. So, there's only a single invocation of the compiler and everything happens in that one compiler invocation. In the SYCL terminology, we call this compilation model "single-source, single compilation pass" (SSCP).

Outside of the nvc++ world, everybody uses the SMCP model (single-source, multiple compilation passes). In the SMCP model, you have at least two distinct compilation steps:
1. Invoke device compiler, which parses code, detects and extracts kernels and generates the device binary
2. Invoke host compiler, which parses code again, compiles as regular host application and embeds the previously compiled device binary.

In SMCP, the way to specialize code for host or device is through macros, since each of the compiler invocations will generally have some macros defined to detect in which compilation pass you are. For example, in SYCL implementations following the SMCP model `__SYCL_DEVICE_ONLY__` is defined only during the invocation of the device compiler, and can hence be used to guard code for device/host and create specialized code paths.

Now, since nvc++ parses the code only once, it is not possible to have any macros to detect if you are targeting host or device, because macros would alter the code before the C++ parser even sees it.
Instead, nvc++ has the `if target()` mechanism, which allows code specialization inside control flow by using magic in the compiler code generation backend.

The `__hipsycl_if_target_*()` statements are built to generalize both to our SMCP compilation flows, in which they use macros such as `__SYCL_DEVICE_ONLY__` under the hood, as well as to the nvc++ SSCP case.

Now consider the following pesudo code:

```c++
int var = 0;
int* device_ptr = sycl::malloc_device(...);

q.parallel_for(myrange, [=](auto idx){
__hipsycl_if_target_device(
  device_ptr[idx] += var;
);
});
```

If you compile this with one of our SMCP compilation flows, you would effectively get something like this:
```c++
int var = 0;
int* device_ptr = sycl::malloc_device(...);

q.parallel_for(myrange, [=](auto idx){
#ifdef __SYCL_DEVICE_ONLY__
  device_ptr[idx] += var;
#endif
});
```
But now there's a problem: The SMCP device compiler would see the kernel invocation:
```c++
q.parallel_for(myrange, [=](auto idx){
  device_ptr[idx] += var;
});
```
while the host compiler would see:
```c++
q.parallel_for(myrange, [=](auto idx){});
```
Because the lambda as seen by the host compiler does not actually use any data, the automatic capture-by-value clause would lead to the compiler deducing that nothing needs to be captured -- even though the device side compiler expects that `device_ptr` and `var` are captured, but the host compiler cannot know that.
Now when the host tries to invoke the kernel, it would not pass in any arguments, because it thinks that the lambda does not capture any data. You have a mismatch between the expected data layout of the lambda between the host and device compiler.

In the nvc++ world, all of this is not an issue, because the SSCP approach guarantees a unified data layout by design since code is only parsed once. (This can also be a disadvantage, e.g. because you cannot do any device-specific storage optimizations for classes used both by the host and device).

The exact same issue would also trigger with your example.

So, the bottom line is:
**If you want to be portable to SMCP compilation flows, always make sure to explicitly capture data in kernel lambdas that are not used at all on some targets due to usage of macros like `__SYCL_DEVICE_ONLY__` or `__hipsycl_if_target_*()` statements.**

This will then ensure that your kernel lambdas have the same data layout everywhere :-)
