### ISSUE TITLE
Define `SYCL_LANGUAGE_VERSION` even without including `CL/sycl.hpp`

### ISSUE THREAD

**Issue by BenBrock** [AdaptiveCpp/AdaptiveCpp#816]
I want a quick way to test whether my code is being compiled by a SYCL compiler or not.  This would allow me to use compile-time directives to only compile SYCL code when using a SYCL compiler and fall back to vanilla C++ otherwise.

The DPC++ compiler defines the macro `SYCL_LANGUAGE_VERSION` even if `CL/sycl.hpp` has not been included yet.  This allows me to test whether `SYCL_LANGUAGE_VERSION` is defined without trying to including SYCL first.  Here's a minimal example of what I would like to work.

```cpp
#if defined(SYCL_LANGUAGE_VERSION) || defined(CL_SYCL_LANGUAGE_VERSION)
  #include <CL/sycl.hpp>
  // include other SYCL code
#else
  static_assert(false, "Not using SYCL compiler.");
#endif

int main(int argc, char** argv) { return 0; }
```

The above example works as I would expect with the DPC++ compiler.  In hipSYCL, it fails with the static assert case because `SYCL_LANGUAGE_VERSION` and `CL_SYCL_LANGUAGE_VERSION` have not yet been defined.  They will only be defined once `CL/sycl.hpp` is included, as far as I can tell.

**If applicable, describe alternatives you've considered**
Another macro or workaround would be fine, although I would prefer to have a cross-platform solution so I don't have to test a separate define for each compiler.

**Comment by BenBrock** [comment]
After a bit more experimentation, I see that `__HIPSYCL__` is defined.  This works for my use case, but I would still prefer a cross-platform solution.  (Maybe this would require an update in the standard?)

**Comment by illuhad** [comment]
I don't think the standard can guarantee that this works, because the standard explicitly allows library-only implementations. In such an implementation, the SYCL implementation is just a library for third-party compilers, and in this case the only way you can define macros is inside the header (unless you want to rely on specific build systems).

As such, I don't think there can be a solution that is guaranteed to work across all implementations in the way you intend.

Generally, `syclcc` only defines macros starting with `__`. We can consider whether it makes sense to pull  that macro definition inside `syclcc`, but I *think* it's better placed where it currently is:
* hipSYCL supports library-only use cases. In principle the supported SYCL standard might then also depend on the third-party compiler that is chosen by the user, which may be more reliably detected from the header file instead of `syclcc`.
* Currently `SYCL_*` macros are all set in the header files, while `__*` macros are set by `syclcc` (with the exception of `__SYCL_DEVICE_ONLY__`, which is beyond the control of `syclcc` in some cases`), so keeping it inside the header will be more consistent. 

Another approach could be to test with `#if __has_include()` whether the SYCL header exists, and only then include it. `__has_include` is widely supported on basically any C++ compiler.

**Comment by BenBrock** [comment]
All excellent points.  I am closing this and will use `__has_include` for now.
