### ISSUE TITLE
cudaFree error? Bug in the code or bug in hipsycl with cuda backend?

### ISSUE THREAD

**Issue by csccva** [AdaptiveCpp/AdaptiveCpp#817]
Hello,

I am running a code from a training using USM and at the of the code I get the following errors:

```
[hipSYCL Error] from /local_scratch/cristian/spack-stage/spack-stage-hipsycl-develop-7blkudaivcxg773bmgkderu5pxxyq4rf/spack-src/src/runtime/cuda/cuda_allocator.cpp:92 @ free(): cuda_allocator: cudaFree() failed (error code = CUDA:46)
[hipSYCL Error] from /local_scratch/cristian/spack-stage/spack-stage-hipsycl-develop-7blkudaivcxg773bmgkderu5pxxyq4rf/spack-src/src/runtime/cuda/cuda_allocator.cpp:136 @ query_pointer(): cuda_allocator: query_pointer(): query failed (error code = CUDA:4)
[hipSYCL Error] from /local_scratch/cristian/spack-stage/spack-stage-hipsycl-develop-7blkudaivcxg773bmgkderu5pxxyq4rf/spack-src/src/runtime/cuda/cuda_allocator.cpp:136 @ query_pointer(): cuda_allocator: query_pointer(): query failed (error code = CUDA:4)
[hipSYCL Error] from /local_scratch/cristian/spack-stage/spack-stage-hipsycl-develop-7blkudaivcxg773bmgkderu5pxxyq4rf/spack-src/src/runtime/cuda/cuda_allocator.cpp:136 @ query_pointer(): cuda_allocator: query_pointer(): query failed (error code = CUDA:4)
``` 
The code seem to run correctly doing `axpy` operation. I am guessing that the cuda pointers are not properly deleted and I am wondering if the problem is in the code or in the hipsycl. 

HEre is the code I use:
```  
#include <cassert>
#include <iostream>

#include <sycl/sycl.hpp>

using namespace sycl;

// shortcuts for USM host and shared allocators classes
template <typename T>
using host_allocator = usm_allocator<T, usm::alloc::host>;
template <typename T>
using shared_allocator = usm_allocator<T, usm::alloc::shared>;

template <typename T>
std::vector<T, shared_allocator<T>>
axpy(
  queue& Q,
  T alpha,
  const std::vector<T, host_allocator<T>>& x,
  const std::vector<T, host_allocator<T>>& y)
{
  assert(x.size() == y.size());
  auto sz = x.size();

  std::vector z(sz, T { 0.0 }, shared_allocator<T>(Q));
  // get address of z, because we rely on by-copy capture in the kernel lambda.
  // Why?
  //  1. by-copy capture gives a const object in the kernel, resulting in a
  //  compiler error.
  //  2. by-reference capture gives a runtime error.
  auto ptrZ = z.data();

  Q.submit([&](handler& cgh) {
     cgh.parallel_for(range { sz }, [=](id<1> tid) {
       auto i  = tid[0];
       ptrZ[i] = alpha * x[i] + y[i];
     });
   })
    .wait();

  return z;
}

int
main()
{
  constexpr auto sz = 1024;

  constexpr auto alpha = 1.0;

  queue Q;

  std::cout << "Running on: " << Q.get_device().get_info<info::device::name>()
            << std::endl;

  auto h_alloc = host_allocator<double>(Q);

  // fill vector x with 0, 1, 2, ..., sz-1
  std::vector x(sz, 0.0, h_alloc);
  std::iota(x.begin(), x.end(), 0.0);
  // fill vector y with sz-1, sz-2, ..., 1, 0
  std::vector y(sz, 0.0, h_alloc);
  std::iota(y.rbegin(), y.rend(), 0.0);

  auto z = axpy(Q, alpha, x, y);

  std::cout << "Checking results..." << std::endl;
  auto message = "Nice job!";
  for (auto i = 0; i < sz; ++i) {
    if (std::abs(z[i] - (sz - 1)) >= 1.0e-13) {
      std::cout << "Uh-oh!" << std::endl;
      std::cout << z[i] << std::endl;
      message = "Not quite there yet :(";
      break;
    }
  }
  std::cout << message << std::endl;
}
```   

I am using the development branch and `A100` gpus with cuda version `11.5`.

**Comment by illuhad** [comment]
Hi!

I could not reproduce error code 46, but I can reproduce occasional CUDA error code 4 with your example.
The issue is that the kernel uses the vectors `x` and `y` directly. You already extract the data pointer for `z`, and you need to do the same thing for `x` and `y`.

It is absolutely not allowed to use `std::vector` directly inside SYCL kernels:
* `std::vector` may throw exceptions which is not supported in device code
* The destructor of `std::vector` in device code will still try to free the memory, which might either crash if the device cannot perform this operation, or will lead to a double free later since the `std::vector` on the host side cannot know that the device has already freed the memory.
* Some `std::vector` operations cause calls to the allocator for memory management; e.g. in order to resize the allocation. This will generate calls into the SYCL runtime library which is not available on device. So, the generated device code would call symbols that are undefined in device code.

It's surprising that this even compiles.

The concrete reason for the particular error code 4 is the following: Error 4 means that a CUDA operation was attempted while the program is already shutting down and the CUDA driver has already been unloaded.
hipSYCL deals with shutdown order by having all SYCL runtime objects like `queue`, `device`, `context` store a `shared_ptr` to the SYCL runtime. When no SYCL runtime object live anymore, the reference count to the runtime reaches zero, and the SYCL runtime library is unloaded, which will in turn also unload the CUDA runtime library.
Since SYCL objects die before the end of `main()`, this means that hipSYCL will have shutdown *before* the CUDA driver is shut down and everything is fine.
The USM allocators however need to store the `context` and `device` on which they operate because these objects are needed for allocation and deallocation of memory. This means that USM allocators will also participate in refcounting the runtime -- this is good, because it means that the SYCL runtime will stay alive as long as there are still allocators around that could need it to perform memory management.
So, when you capture an `std::vector` with USM allocator, you are capturing an object that is supposed to reference-count the SYCL runtime. There are multiple issues with that:
* There might be a potential for cyclic `shared_ptr` dependencies because now the SYCL runtime manages a kernel, the lambda capture of which contains a `shared_ptr` which in turn forces the runtime to stay alive;
* When moving a `shared_ptr` across the host-device boundary during kernel invocation, it is just bitcopied, and reference-counting does not work across host and device boundary. So therefore, the reference count might be incorrect afterwards.

These issues can lead to preventing the SYCL runtime from cleanly unloading at the end of `main()` and can potentially keep it alive to the point where the program shutdown has progressed as far as the CUDA driver having shut down.


Sidenote: Note that `x` and `y` are using host allocators. While SYCL host allocations are device-accessible, they reside in host memory, and so every memory access is going over PCIe and will therefore be super inefficient.

**Comment by csccva** [comment]
Hello,

Thank you for your reply. This code was from a training I attended to show an example of the Your explanation makes sense. I am not a C++ programmer, I thought  I could get into SYCL with  only knowing GPU programming. I see that I have a lot to learn before being able to program. 

For my programming needs I think I can get by with just using `buffers+assessors` or the USM with  the more familiar calls like: `z= malloc_shared<double>(size, Q);` 

Cristian

**Comment by illuhad** [comment]
Yes, the idea behind SYCL is to express heterogeneous computing with modern C++ constructs - for better or for worse :( 
However I've given you the maximum in-depth explanation. Understanding all these details is probably not required, for everyday use it's probably sufficient to just follow a couple of guidelines, such as: Using anything from `std::` is not guaranteed to work inside kernels.

May I ask which training presented this particular code? I would like to make sure that this is fixed, since the code is clearly incorrect.

**Comment by csccva** [comment]
Hello,

You were present once. An event from ENCSS:
`https://github.com/ENCCS/sycl-workshop/tree/main/content/code`. 


This above code is: `https://github.com/ENCCS/sycl-workshop/blob/main/content/code/day-1/07_axpy-usm_allocator/solution/axpy.cpp`. 
Not sure about the other exercises.

**Comment by illuhad** [comment]
Ah, yes, I remember this workshop :) Thank you, I have opened an issue in the ENCCS repository.

**Comment by csccva** [comment]
I hope it is ok to close this issue. Thanks for the answers.
