### ISSUE TITLE
How to combine SYCL and MPI

### ISSUE THREAD

**Issue by nordmoen** [AdaptiveCpp/AdaptiveCpp#820]
Hi,

I was wondering if anyone had any recommendations on how to combine SYCL with MPI communication. Specifically I would like to achieve GPU-to-GPU communication without copying data back to the host.

My initial attempt was something like the following:
```cpp
std::vector<int> result(N);                                                 
auto result_buf = sycl::buffer(std::begin(result), std::end(result));       
auto mpi_event = queue.submit(                                              
    [&](sycl::handler& h) {                                                 
      sycl::accessor dat{data_buf, h, sycl::read_only};                     
      sycl::accessor res{result_buf, h, sycl::write_only};                  
      h.host_task([=]() {                                                   
        MPI_Reduce(dat.get_pointer(), res.get_pointer(), N, MPI_INT, MPI_SUM, 0, MPI_COMM_WORLD);                    
      });                                                                   
    }                                                                       
  );                                                                        
mpi_event.wait();
```

However, this doesn't work yet since hipSYCL doesn't support `host_task`. Are there other alternatives? I sort of assume that if I use `sycl::host_accessor` then data will implicitly be moved back to the host if I do `get_pointer()` for the MPI call.

**Comment by sbalint98** [comment]
Hi! I think for this purpose you can try to use the `hipSYCL_enqueue_custom_operation` extension. You can read more about it under this [link](https://github.com/illuhad/hipSYCL/blob/develop/doc/enqueue-custom-operation.md).

**Comment by illuhad** [comment]
Hi!

>  I sort of assume that if I use sycl::host_accessor then data will implicitly be moved back to the host if I do get_pointer() for the MPI call.

This is correct; `get_pointer()` of a `host_accessor` will not return device pointers but a host pointer, which is not what you want I think.

`hipSYCL_enqueue_custom_operation` won't work because it assumes that you are enqueuing additional work on the *device*. As such, it is the prime mechanism for interop with libraries like cuBLAS, but it won't work here because MPI calls are not enqueued on a device queue, even if you use a GPU-aware MPI.

You can basically do two things:
1. Use USM in your program
2. Use hipSYCL's buffer-USM interoperability. In hipSYCL you can always turn a buffer into pointers (`buffer::get_pointer(device)`), or build a buffer on top of pointers.
https://github.com/illuhad/hipSYCL/blob/develop/doc/buffer-usm-interop.md

In buffer-USM interop, it is possible that allocations are written to without the buffer knowing about it. As such
* It is the programmer's responsibility to ensure that the data state that the buffer knows about, and the actual data state are coherent. You can use the update device extension for this purpose: https://github.com/illuhad/hipSYCL/blob/develop/doc/extensions.md#hipsycl_ext_update_device
* It is the programmer's responsibility to ensure that synchronization between operations using the buffer representation and operations using the pointer representation is done correctly.
* Be aware that buffers allocate lazily; i.e. device pointers will not exist until a buffer has been used on that particular device.

It is strongly recommended to have a thorough understanding of how the hipSYCL runtime handles buffers before attempting this: https://github.com/illuhad/hipSYCL/blob/develop/doc/runtime-spec.md

See also https://hipsycl.github.io/hipsycl/extension/hipsycl-091-buffer-usm-interop/

**Comment by nordmoen** [comment]
Thank you both for the comments.

I tried the USM approach (since my program was simply a single file example) and that worked as expected. I was able to combine one `sycl::malloc_device` and one `sycl::malloc_shared` in one `MPI_Reduce` call which worked without issue.
