### ISSUE TITLE
Sanitizer + omp backend = undefined reference during linking

### ISSUE THREAD

**Issue by tdavidcl** [AdaptiveCpp/AdaptiveCpp#886]
Hi,

I just came accros this weirdness, and after some cleaning, this simple main create an undefined symbol during linking 

```c++
#include <sycl/sycl.hpp>

int main() {
   
    sycl::queue queue;

    queue.submit([&] (sycl::handler& cgh) {
        
        cgh.parallel_for(sycl::nd_range<1>(32 , 32),[=] (sycl::nd_item<1> item) {

            size_t local_id = item.get_local_id(0);
            size_t global_id = item.get_global_id(0);
            
            item.barrier(sycl::access::fence_space::local_space);

        });
    });
    

    return 0;
}
```

The following compile command : 

```bash
./sycl_cpl/hipSYCL/bin/syclcc -std=c++17 -g -fsanitize=address\
    --hipsycl-config-file=./sycl_cpl/hipSYCL/etc/hipSYCL/syclcc.json\
    --hipsycl-targets='omp' --hipsycl-platform=cpu  test.cpp -o out
```

gives:

```
/usr/bin/ld: /tmp/test-61dbfd.o: in function `void hipsycl::glue::omp_dispatch::iterate_nd_range_omp<1, main::$_0::operator()(hipsycl::sycl::handler&) const::{lambda(hipsycl::sycl::nd_item<1>)#1}>(main::$_0::operator()(hipsycl::sycl::handler&) const::{lambda(hipsycl::sycl::nd_item<1>)#1}, hipsycl::sycl::id<1> const&&, hipsycl::sycl::range<1>, hipsycl::sycl::range<1>, hipsycl::sycl::id<1>, unsigned long, void*, std::function<void ()>&)':
......./hipSYCL/bin/../include/hipSYCL/glue/omp/omp_kernel_launcher.hpp:235: undefined reference to `__hipsycl_local_id_x'
/usr/bin/ld: ......./hipSYCL/bin/../include/hipSYCL/glue/omp/omp_kernel_launcher.hpp:235: undefined reference to `__hipsycl_local_id_x'
```

removing the ```-fsanitize=address``` solve the issue.

Note : i'm using the default config for hipsycl (commit 56b6c1f4198aced999a4199b272790a6e15adabe) : 

```
{
  "version-major" : "0",
  "version-minor" : "9",
  "version-patch" : "3",
  "plugin-llvm-version-major" : "14",
  "plugin-with-cpu-acceleration" : "true",
  "default-clang"     : "/usr/bin/clang++",
  "default-nvcxx"     : "NVCXX_COMPILER-NOTFOUND",
  "default-platform"  : "cuda",
  "default-cuda-path" : "/opt/cuda",
  "default-gpu-arch"  : "",
  "default-cpu-cxx"   : "/usr/bin/c++",
  "default-rocm-path" : "/opt/rocm",
  "default-use-bootstrap-mode" : "false",
  "default-is-dryrun" : "false",
  "default-use-accelerated-cpu" : "true",
  "default-clang-include-path" : "/usr/lib/clang/14.0.6/include/..",
  "default-sequential-link-line" : "-L/usr/lib -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib",
  "default-sequential-cxx-flags" : "-I/usr/include -D_ENABLE_EXTENDED_ALIGNED_STORAGE",
  "default-omp-link-line" : "-L/usr/lib -lboost_context -lboost_fiber -Wl,-rpath=/usr/lib -fopenmp",
  "default-omp-cxx-flags" : "-I/usr/include -fopenmp -D_ENABLE_EXTENDED_ALIGNED_STORAGE",
  "default-rocm-link-line" : "-Wl,-rpath=$HIPSYCL_ROCM_PATH/lib -Wl,-rpath=$HIPSYCL_ROCM_PATH/hip/lib -L/opt/rocm/lib -L/opt/rocm/hip/lib -lamdhip64",
  "default-rocm-cxx-flags" : "-isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike -isystem /usr/lib/clang/14.0.6/include/.. -U__FLOAT128__ -U__SIZEOF_FLOAT128__ -I$HIPSYCL_ROCM_PATH/include -I$HIPSYCL_ROCM_PATH/include --rocm-device-lib-path=$HIPSYCL_ROCM_PATH/amdgcn/bitcode --rocm-path=$HIPSYCL_ROCM_PATH -fhip-new-launch-api -mllvm -amdgpu-early-inline-all=true -mllvm -amdgpu-function-calls=false -D__HIP_ROCclr__",
  "default-cuda-link-line" : "-Wl,-rpath=$HIPSYCL_CUDA_LIB_PATH -L$HIPSYCL_CUDA_LIB_PATH -lcudart",
  "default-cuda-cxx-flags" : "-U__FLOAT128__ -U__SIZEOF_FLOAT128__ -isystem $HIPSYCL_PATH/include/hipSYCL/std/hiplike",
  "default-is-explicit-multipass" : "false",
  "default-save-temps" : "false"
}
```

**Comment by illuhad** [comment]
Hi!

> ./sycl_cpl/hipSYCL/bin/syclcc -std=c++17 -g -fsanitize=address\
    --hipsycl-config-file=./sycl_cpl/hipSYCL/etc/hipSYCL/syclcc.json\
    --hipsycl-targets='omp' --hipsycl-platform=cpu  test.cpp -o out

Please don't use `--hipsycl-platform`, it's deprecated and superseded by `--hipsycl-targets` (and will be ignored if `--hipsycl-targets` is present.

Since your hipSYCL has been compiled with accelerated CPU support, I believe `omp` is probbably resolved to the `omp.accelerated` compilation flow, where hipSYCL does additional compiler transformation to accelerate certain SYCL constructs when running on CPU.
To confirm, could you try `--hipsycl-targets=omp.library-only`, where it will instead function as a library for OpenMP compilers? If the issue is specific to the `omp.accelerated` flow, it should work in that case.

I'm not sure why this issue would arise when using `omp.accelerated`, but maybe @fodinabor has an idea?

**Comment by tdavidcl** [comment]
Hi,
I just tried with both ```omp.accelerated``` and ```omp.library-only```.
The issue is present only with ```omp.accelerated```

> Please don't use --hipsycl-platform, it's deprecated and superseded by --hipsycl-targets (and will be ignored if --hipsycl-targets is present.

Thanks i didn't noticed it, it was in a old makefile.

**Comment by fodinabor** [comment]
Jup, this should definitely only occur with `accelerated`, as this is an internal symbol that is defined in the accelerated code path only: https://github.com/illuhad/hipSYCL/blob/develop/include/hipSYCL/glue/omp/omp_kernel_launcher.hpp#L223

Since it's explicitly undefined, this has to be cleaned up after the compiler transformations that needed it are through with it. This should happen in: https://github.com/illuhad/hipSYCL/blob/develop/src/compiler/cbs/RemoveBarrierCalls.cpp#L75  
But I assume that activating ASAN adds some references to this, so the [check](https://github.com/illuhad/hipSYCL/blob/develop/src/compiler/cbs/RemoveBarrierCalls.cpp#L32) whether it's dead is not successful.

Will try to dig into it later..

**Comment by fodinabor** [comment]
Could you test with `omp.accelerated` after applying #887?

(Had that fix flying around in a branch already..)
