### ISSUE TITLE
Kernel is not dispatched as soon as possible?

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#890]
I was just surprised that in the code below the kernel is not dispatched until it is called `wait` or `queue` is destroyed. I thought it would dispatch right after the call to `single_task` asynchronously and there should be enough time for it to dispatch within 5 seconds.

``` c++
	sycl::queue q;
	q.single_task([]()
	{
		printf("kernel\n");
	});
	this_thread::sleep_for(5s);
	printf("host\n");
```
```
host
kernel
```

**Comment by illuhad** [comment]
SYCL does not make any forward progress guarantees just by invoking `submit()` or other kernel invocation APIs like `queue::single_task()`.
A SYCL implementation may want to batch kernels together. There are no guarantees when kernels are actually executed, the only guarantee you have is that once you invoke some synchronization mechanism like `wait()` work will be processed so that `wait()` can eventually complete.

**Comment by psalz** [comment]
See also #599.

**Comment by misos1** [comment]
It would be nice to have an `eager` queue or `queue::flush_async`. So for now it is `q.get_context().hipSYCL_runtime()->dag().flush_async();`.

**Comment by illuhad** [comment]
You can also just set the environment variable `HIPSYCL_RT_MAX_CACHED_NODES=0` to achieve the same effect.
https://github.com/illuhad/hipSYCL/blob/develop/doc/env_variables.md
