### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by alexschroeter** [AdaptiveCpp/AdaptiveCpp#891]
Hello,

Since Ubuntu 18.04 LTS will be end of life soon we had to upgrade. We decided to move to 22.04 LTS but I see now it is not in the list of supported Operating Systems and we have some issues with hipSYCL after the upgrade. The available prebuild images are quite old and I was wondering if there are any plans to upgrade to the newer Ubuntu versions now that it is also supported by AMD.

Best Alex

**Comment by illuhad** [comment]
I use hipSYCL with Ubuntu 22.04 all the time. Where do we say that we do not support 22.04? If we do say that somewhere, we should remove that statement :)

If you are referring to the binary packages, those are indeed outdated because we are trying to migrate to a new approach how to package things (and got stuck on some issues :( ). For now my recommendation is to build from source until binary packages are updated.

**Comment by alexschroeter** [comment]
Thanks, for the help. I have tried on a different server with a fresh install. I feel the upgraded server is broken in some way. Yes I was talking about the packages and since building from source segfaulted on that machine, I assumed it is not supported. I would consider this solved.
