### ISSUE TITLE
Should it be possible to use malloc_host without specifying sycl namespace?

### ISSUE THREAD

**Issue by misos1** [AdaptiveCpp/AdaptiveCpp#894]
I just accidentally forgot to prepend `sycl::` and it compiled. And I do not think that it is a good idea to put such thing in the global namespace.

``` c++
#include <sycl/sycl.hpp>

int main()
{
	sycl::queue q;
	malloc_host(4096, q);
}
```

**Comment by illuhad** [comment]
It's not in the global namespace. What you are seeing is the effect of C++ argument dependent lookup (ADL). C++ compilers will also consider namespaces of function arguments during overload resolution. This is why e.g. `std::operator<<` is found even though it is in `std` namespace when passing `std::cout` as argument.

In this case, since a `sycl::queue` is one of the arguments, the `sycl` namespace will be investigated by C++ compilers.

You will see the same behavior with other SYCL implementations. It's regular C++ at work :)

https://en.cppreference.com/w/cpp/language/adl
