### ISSUE TITLE
Long compilation times

### ISSUE THREAD

**Issue by philipturner** [AdaptiveCpp/AdaptiveCpp#900]
I've been compiling the `generic-llvm-sscp` branch for macOS, and the `tests` directory routinely takes several minutes to compile. It's only a few files. For larger code bases like GROMACS, it might take hours. Is this expected?

**Comment by illuhad** [comment]
Welcome to the world of modern C++ ;) `make -j<ncores>` is your friend ;)

There are around 50 source files in that directory. Since every SYCL program as tested by the test cases is a modern C++ program too due to SYCL being built on top of modern C++, you can easily expect several seconds per source file. So, several minutes are expected simply because of C++.

Additionally, many of those test cases instantiate C++ template code for a lot of different data types or dimensionalities to have better test coverage. This might increase compile times further compared to average C++ programs, or more real-world apps like Gromacs.

If you compile the tests for compilation flows that rely on a multipass compilation model, you will also roughly multiply compile times because source code will have to be parsed and codegened multiple times.

If you build the tests using the generic SSCP compiler (`--hipsycl-targets=generic`), source files will only be parsed once. Compile times should only be slightly slower compared to pure C++ library use cases without SYCL-specific compiler magic (`--hipsycl-targets=omp.library-only`).

Note that while all tests are expected to compile with `--hipsycl-targets=generic`, not all of them are expected to run correctly currently because the generic SSCP compiler does not yet support all functionality.
